### ISSUE TITLE
Players stuck in my server

### ISSUE THREAD

**Issue by lspublic** [dreamstalker/rehlds#1001]
Hello, i dont know why some players stuck in my server i try to include screenshot ?
https://prnt.sc/TwDkyFCrW6pe
You can see this player not have steamid or IP . I try to kick when i write amx_last not show anything:
https://prnt.sc/L97lq5smoR57
I try to find solution in google its nothing i change cvar sv_allowupload 0 again same, i update rehlds again same

Dropped Player from server
Reason:  Client sent 'drop'
77.109.144.90:27005:reconnect
0
SZ_GetSpace: overflow on (3)<Warrior> Player

Do you know somebody how can i fixed ?

**Comment by Maxi605** [comment]
You can try using ReAuthChecker to limit the connections from one IP so he can't just flood your server with connections, also you could modify mp_timeout (or sv_timeout) to a lower value (60 by default) so he gets kicked faster and you could always do addip "0" "IP", he doesn't really need to be connected to be banned by that command and it will prevent him from even trying to connect.

**Comment by dystopm** [comment]
> You can try using ReAuthChecker to limit the connections from one IP so he can't just flood your server with connections, also you could modify mp_timeout (or sv_timeout) to a lower value (60 by default) so he gets kicked faster and you could always do addip "0" "IP", he doesn't really need to be connected to be banned by that command and it will prevent him from even trying to connect.

It is mostly a rehlds feature, both can be used. Check readme:

https://github.com/dreamstalker/rehlds/blob/93f5775ac26240782981f47ee8e052fb53d30877/README.md?plain=1#L54

**Comment by lspublic** [comment]
Thanks for comment but i make one mistake i touch the timeout cvar and this are problem i back again in normaly everything its okey. Thank you for your help ;)
