### ISSUE TITLE
Missing Sv_busters on the new ReHLDS, Mp5 reload

### ISSUE THREAD

**Issue by stylez1989** [dreamstalker/rehlds#1009]
25th HLDS has sv_busters cvar which will be nice to have in this update.
Mp5 on hlds will be at 50 full ammo instead of the previous 25 where you had to reload.

**Comment by s1lentq** [comment]
This CVar `sv_busters` is registered and has a presence only in server gamedll Half-Life `dlls/hl.dll`,  `dlls/hl.so`
Therefore, it has no related to with HLDS or REHLDS.
