### ISSUE TITLE
Procedure entry point SteamApps could not be found

### ISSUE THREAD

**Issue by wolverine998** [dreamstalker/rehlds#1013]
Installed the latest HLDS using SteamCMD. Runs fine. But when i replace the engine with ReHLDS, HLDS.exe crashes with error **Procedure entry point SteamApps could not be found in Dynamic library C:\steamcmd\steamapps\common\Half-Life\swds.dll**. It worked before.

**Comment by wolverine998** [comment]
Seems no one wants to help. Such nad support. So guess stick back to original HLDS.

**Comment by Nord1cWarr1or** [comment]
Have you tried using a search?

https://github.com/dreamstalker/rehlds/issues/999#issuecomment-1826375535
