### ISSUE TITLE
Confusing Fast Download issue

### ISSUE THREAD

**Issue by TnE-CsTrk** [dreamstalker/rehlds#1022]
Confusing Fast Download problem: When I update h5ai to the latest version.
Really "Fast" Download all files. The file size is all 2KB. It records text messages like html/css styles.

ps. directly through the file link can be correctly downloaded, the old version h5ai deployment fastdl did not encounter similar problems, I am not a Web Developer, just curious.

txt ---open-->  .mdl
`
<!DOCTYPE html><html class="no-js" lang="en"><head><meta charset="utf-8"><meta http-equiv="x-ua-compatible" content="ie=edge"><title>index - powered by h5ai v0.30.0 (https://larsjung.de/h5ai/)</title><meta name="description" content="index - powered by h5ai v0.30.0 (https://larsjung.de/h5ai/)"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="shortcut icon" href="/_h5ai/public/images/favicon/favicon-16-32.ico"><link rel="apple-touch-icon-precomposed" type="image/png" href="/_h5ai/public/images/favicon/favicon-152.png"><link rel="stylesheet" href="/_h5ai/public/css/styles.css"><script src="/_h5ai/public/js/scripts.js" data-module="index"></script><link rel="stylesheet" href="//fonts.lug.ustc.edu.cn/css?family=Ubuntu:300,400,700%7CUbuntu+Mono:400,700" class="x-head"><style class="x-head">#root,input,select{font-family:"Ubuntu","Roboto","Helvetica","Arial","sans-serif"!important}pre,code{font-family:"Ubuntu Mono","Monaco","Lucida Sans Typewriter","monospace"!important}</style></head><body class="index" id="root"><div id="fallback-hints"><span class="noJsMsg">Works best with JavaScript enabled!</span><span class="noBrowserMsg">Works best in <a href="http://browsehappy.com">modern browsers</a>!</span><span class="backlink"><a href="https://larsjung.de/h5ai/" title="h5ai v0.30.0 - Modern HTTP web server index.">powered by h5ai</a></span></div><div id="fallback"><table><tr><th class="fb-i"></th><th class="fb-n"><span>Name</span></th><th class="fb-d"><span>Last modified</span></th><th class="fb-s"><span>Size</span></th></tr><tr><td class="fb-i"><img src="/_h5ai/public/images/fallback/folder-parent.png" alt="folder-parent"/></td><td class="fb-n"><a href="..">Parent Directory</a></td><td class="fb-d"></td><td class="fb-s"></td></tr></table></div></body></html>
`

**Comment by SmilexGamer** [comment]
Uh, what? I don't understand what is the problem.

**Comment by TnE-CsTrk** [comment]
> Uh, what? I don't understand what is the problem.

![Uploading screenprint.png…]()

**Comment by TnE-CsTrk** [comment]
> Uh, what? I don't understand what is the problem.

![screenprint](https://github.com/dreamstalker/rehlds/assets/58636831/89a12a76-6d37-48a3-b956-2fb16130eadc)

**Comment by TnE-CsTrk** [comment]
I entered the wrong download path, it has nothing to do with the version, sorry about that.
