### ISSUE TITLE
Flooding console

### ISSUE THREAD

**Issue by Pejic99** [dreamstalker/rehlds#1025]
Greetings, 

I am currently experiencing an issue with flood attacks on my console, specifically the "ping of death" method, which involves players spamming the console. This results in significant server lag, leading to an increase in ping for all players. I am seeking recommendations for measures I can implement to prevent such flooding in the console and effectively address the problem.

I would appreciate your expertise and any recommendations you may offer in this regard. 

Thank you for your assistance.

**Comment by justgo97** [comment]
Show us the console output or paste some logs and maybe we can know how to prevent it.

**Comment by Pejic99** [comment]
They are mostly flooding with this commands "ping" "pingservers" and "mcache"

**Comment by Pejic99** [comment]
L 03/02/2024 - 22:39:14: "debeli gmaz<97><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:39:14: "debeli gmaz<97><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:39:16: "debeli gmaz<97><STEAM_0:1:767933152><CT>" triggered "time" (time "0:02")
L 03/02/2024 - 22:39:16: "debeli gmaz<97><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:39:16: "debeli gmaz<97><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:39:16: "debeli gmaz<99><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:39:16: "debeli gmaz<99><STEAM_0:1:767933152><>" STEAM USERID validated
L 03/02/2024 - 22:39:20: "debeli gmaz<99><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:39:20: "debeli gmaz<99><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:39:23: "debeli gmaz<99><STEAM_0:1:767933152><CT>" triggered "time" (time "0:02")
L 03/02/2024 - 22:39:23: "debeli gmaz<99><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:39:23: "debeli gmaz<99><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:39:23: "debeli gmaz<100><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:39:23: "debeli gmaz<100><STEAM_0:1:767933152><>" STEAM USERID validated
L 03/02/2024 - 22:39:27: "debeli gmaz<100><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:39:27: "debeli gmaz<100><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:39:29: "debeli gmaz<100><STEAM_0:1:767933152><CT>" triggered "time" (time "0:02")
L 03/02/2024 - 22:39:29: "debeli gmaz<100><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:39:29: "debeli gmaz<100><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:39:29: "debeli gmaz<101><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:39:30: "debeli gmaz<101><STEAM_0:1:767933152><>" STEAM USERID validated
L 03/02/2024 - 22:39:32: "KVӨƬΛ v2<6><STEAM_0:0:554601062><CT>" committed suicide with "trigger_hurt" (world)
L 03/02/2024 - 22:39:34: "debeli gmaz<101><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:39:34: "debeli gmaz<101><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:39:36: "debeli gmaz<101><STEAM_0:1:767933152><CT>" triggered "time" (time "0:02")
L 03/02/2024 - 22:39:36: "debeli gmaz<101><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:39:36: "debeli gmaz<101><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:39:37: "debeli gmaz<102><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:39:37: "debeli gmaz<102><STEAM_0:1:767933152><>" STEAM USERID validated
L 03/02/2024 - 22:39:40: "debeli gmaz<102><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:39:40: "debeli gmaz<102><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:39:42: "TyS | Stosicka<83><STEAM_0:1:537871873><CT>" committed suicide with "trigger_hurt" (world)
L 03/02/2024 - 22:39:43: "debeli gmaz<102><STEAM_0:1:767933152><CT>" triggered "time" (time "0:02")
L 03/02/2024 - 22:39:43: "debeli gmaz<102><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:39:43: "debeli gmaz<102><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:39:43: "debeli gmaz<103><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:39:44: "debeli gmaz<103><STEAM_0:1:767933152><>" STEAM USERID validated
L 03/02/2024 - 22:39:47: "debeli gmaz<103><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:39:47: "debeli gmaz<103><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:39:49: "debeli gmaz<103><STEAM_0:1:767933152><CT>" triggered "time" (time "0:00")
L 03/02/2024 - 22:39:49: "debeli gmaz<103><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:39:49: "debeli gmaz<103><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:39:49: "debeli gmaz<104><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:39:49: "debeli gmaz<104><STEAM_0:1:767933152><>" STEAM USERID validated
L 03/02/2024 - 22:39:53: "debeli gmaz<104><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:39:53: "debeli gmaz<104><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:39:56: "debeli gmaz<104><STEAM_0:1:767933152><CT>" triggered "time" (time "0:02")
L 03/02/2024 - 22:39:56: "debeli gmaz<104><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:39:56: "debeli gmaz<104><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:39:56: "debeli gmaz<105><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:39:56: "debeli gmaz<105><STEAM_0:1:767933152><>" STEAM USERID validated
L 03/02/2024 - 22:40:00: "debeli gmaz<105><STEAM_0:1:767933152><>" entered the game
L 03/02/2024 - 22:40:00: "debeli gmaz<105><STEAM_0:1:767933152><>" joined team "CT"
L 03/02/2024 - 22:40:03: "debeli gmaz<105><STEAM_0:1:767933152><CT>" triggered "time" (time "0:02")
L 03/02/2024 - 22:40:03: "debeli gmaz<105><STEAM_0:1:767933152><CT>" triggered "latency" (ping "0")
L 03/02/2024 - 22:40:03: "debeli gmaz<105><STEAM_0:1:767933152><CT>" disconnected
L 03/02/2024 - 22:40:03: "debeli gmaz<106><STEAM_0:1:767933152><>" connected, address "188.2.182.12:27005"
L 03/02/2024 - 22:40:04: "debeli gmaz<106><STEAM_0:1:767933152><>" STEAM USERID validated

**Comment by Pejic99** [comment]
What I need is a server console that blocks flooding commands such as "ping", "status", and "mcache".

**Comment by SmilexGamer** [comment]
How are those commands slowing down your server? Maybe the machine that is hosting your server can't handle it well?

**Comment by Pejic99** [comment]
I guess its not those commands then , I think they are doing something like this : https://www.youtube.com/watch?v=s0sRyELVQJk&ab_channel=DNG%2a
