### ISSUE TITLE
"-heapsize 131072"

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#1030]
needed to add `-heapsize 131072` on rehlds/regamedll_cs for running  [de_beishan](https://gamebanana.com/mods/466280) .
afterwards some amxx-plugins didnt work correct anymore.
is this normal or worth investigating?

**Comment by StevenKal** [comment]
Yeah some maps trigger than "Heap Size" engine error & so need increasing the value on parameters.
I personnaly have heap size defined at 48000 (default is 40960 from that I recall) & no AMX plugins problems.

**Comment by fred0r** [comment]
thx - will check

**Comment by fred0r** [comment]
thx - will check

**Comment by fred0r** [comment]
Seems to work - THANK YOU!
