### ISSUE TITLE
Crash caused by AMX module "cstrike"

### ISSUE THREAD

**Issue by fr0zert** [dreamstalker/rehlds#1037]
Recently decided to run a local server to play with friends and encountered the problem that the cstrike module crashes the server.

rehlds 3.13.0.788
Metamod-r version 1.3.0.149 / Official Metamod v1.20
AMX Mod X version 1.8.2 base + addon pack Counter-Strike

just in case tried different metamods, that's why I specified 2

no errors in the server console

crash occurs at the stage of connecting to the server

as soon as I remove the cstrike module in the amxmode settings, the server stops crashing

I will also attach mdmp files generated after the crash

[crash mdmp files.zip](https://github.com/user-attachments/files/16216536/crash.mdmp.files.zip)

**Comment by Nord1cWarr1or** [comment]
try  AMXX 1.9.0 or 1.10.0

**Comment by fr0zert** [comment]
Yes it solved the problem, for some reason I just now found that there is such a version amxx
