### ISSUE TITLE
[HELP] Arch Linux (steam) package conflict with HLDS

### ISSUE THREAD

**Issue by SmileYzn** [dreamstalker/rehlds#1043]
Hi folks, HLDS or ReHLDS is not starting when you install steam package on arch Linux.

Is not a bug with HLDS itself, but is not being compatible with installed steam in arch Linux

![image](https://github.com/user-attachments/assets/8d8b5425-5866-49e9-b11e-baa0404ba221)

More specific with this folder (The Steam folder)

![image](https://github.com/user-attachments/assets/64339bbe-8290-42a0-8d91-f3c4103a9249)

But if i rename or remove that <code>/home/eu/.local/share/Steam</code> folder, HLDS runs fine.

![image](https://github.com/user-attachments/assets/02dc986b-5a00-4efc-a019-5a44562e3ff5)

Ps.
The Arch Linux package recommended is  and installed **steam** (Not steam-runtime).

There is any chance to discover why HLDS insists to import something from /home/eu/.local/share/Steam?

I'm trying to run HLDS and Steam at same time basically,

**Comment by Nord1cWarr1or** [comment]
Try [this](https://github.com/xxkfqz/rehlds/releases/tag/libfix)

**Comment by SmileYzn** [comment]
Thanks for help!

I found the real problem:

HLDS really looks for home folder of current user and try to load something from there

https://github.com/dreamstalker/rehlds/blob/7073363c885c8f0c6e9967c09f41fcd733306ab1/rehlds/filesystem/FileSystem_Stdio/src/pathmatch.cpp#L503

Just change HOME environment variable when launch HLDS works and fix that problem.

```
#!/bin/bash
clear
export HOME=
./hlds_run -steam_dir . -game cstrike -steam -master -secure -pingboost 3 -bots +port 27020 +ip 192.168.100.100 +maxplayers 32 +map de_inferno +sys_ticrate 1000
```
