### ISSUE TITLE
how to install rehlds?

### ISSUE THREAD

**Issue by artstylee** [dreamstalker/rehlds#1046]
hi! its now an issue just misunderstanding.
i want to setup my own cs 1.6 server
i dont have anything, no hlds nothing
i just cloned your repo and build it
but what next? i need original hlds server?
can you make a full tutorial pls?
debian 12

**Comment by Nord1cWarr1or** [comment]
1. install clean hlds server (steam_legacy branch)
2. Overwrite hlds files with rehlds files

**Comment by artstylee** [comment]
rcon status before

```
version :  48/1.1.2.7/Stdio 9907 secure  (10)
tcp/ip  :  127.0.1.1:27015
map     :  de_dust2 at: 0 x, 0 y, 0 z
players :  10 active (32 max)

```
1. build rehlds
2. dropped all files from build/rehlds to original hlds folder (where cstrike folder and hlds_run) and got 
3. run ./hlds_run +map  de_dust2 -game cstrike - pingboost 3 -maxplayers 32
4. error
engine_i486.so: undefined symbol: steamgameserver_init
unable to load engine image is corrupt

**Comment by artstylee** [comment]
opps missed ur comment about legacy branch
anyway there is an error 
Error:./libstdc++.so.6:version 'GLIBCXX_3.4.29'

**Comment by artstylee** [comment]
apt list --installed
libstdc++-12-dev/stable,now 12.2.0-14 amd64 [installed,automatic]
libstdc++6/stable,now 12.2.0-14 amd64 [installed]
libstdc++6/stable,now 12.2.0-14 i386 [installed,automatic]
