### ISSUE TITLE
Unable to load engine, image is corrupt

### ISSUE THREAD

**Issue by h266579110** [dreamstalker/rehlds#1050]
![image](https://github.com/user-attachments/assets/d77dbad2-97bb-4ba8-8359-7b48bcc8b67b)

Tried do a fresh install, issue not solve. (Original HLDS is working)

1. Download HLDS from SteamCMD.
2. Install ReHLDS
3. Starting the server, popup the error.

**Comment by Nord1cWarr1or** [comment]
Download "steam_legacy" branch
