### ISSUE TITLE
Animation skip during m4/ak spray

### ISSUE THREAD

**Issue by Maxpain177** [dreamstalker/rehlds#11]
You can fix [this bug](https://github.com/ValveSoftware/halflife/issues/1183)?
I want to put your engine on all servers fastcup.net

**Comment by s1lentq** [comment]
If I'm not mistaken.
It's probably a problem in the gamedll (mp.dll / cs.so), that has nothing to do with engine

**Comment by dreamstalker** [comment]
@s1lentq You're correct, the code causing this problem is located inside gamedll (probably both on server and client side)
So, I'm afraid, it's not possible to fix this problem in rehlds
