### ISSUE TITLE
NonSteam client don't connect from favorites.

### ISSUE THREAD

**Issue by mforce95** [dreamstalker/rehlds#115]
NonSteam client don't connect from favorites.
Query port changed to 0??? 

Here is the video of it.
https://www.youtube.com/watch?v=7VVgiZXk7mU

**Comment by s1lentq** [comment]
what does this have to do with rehlds?

**Comment by mforce95** [comment]
With HLDS it works perfect...

**Comment by s1lentq** [comment]
if you have a module that allows players to go to the server, you should ask questions in module Official topic.
This problem does not apply to rehlds.

**Comment by latinas** [comment]
Write here http://www.dedicated-server.ru/vbb/showthread.php?t=26486

**Comment by mforce95** [comment]
It isn't have connection with https://github.com/dreamstalker/rehlds/issues/116 ??

**Comment by theAsmodai** [comment]
No, it's another problem. Try to update metamod plugins or ask help on their support forums.
