### ISSUE TITLE
Gametracker not tracked.

### ISSUE THREAD

**Issue by mforce95** [dreamstalker/rehlds#116]
After I moved to reHLDS, (on my top server) Gametracker isn't track it.
And after I search for it, i found this post:
https://www.gametracker.com/forums/forum.php?site=1&post=390815

**Comment by OZone998** [comment]
I have had the same problem, but I finally found a solution.
Do you have ReUnion module installed on your server?
You just have to set ServerInfoAnswerType to 2 in config and server will be visible on GT.

**Comment by mforce95** [comment]
yes

**Comment by S0m3Th1nG-AwFul** [comment]
Strange, that with the same value of ServerInfoAnswerType (zero) on old HLDS+DProto everything works fine (with GameTracker at least).

**Comment by mforce95** [comment]
Yes, we know. :smile:

**Comment by theAsmodai** [comment]
Should be fixed.
