### ISSUE TITLE
Сrash after bot disconnect

### ISSUE THREAD

**Issue by riva2014** [dreamstalker/rehlds#118]
OS Windows XP SP3 32 bit
ReHLDS 624 bugfixed

[drwtsn32.txt](https://github.com/dreamstalker/rehlds/files/80803/drwtsn32.txt)

**Comment by theAsmodai** [comment]
Try this http://teamcity.rehlds.org/repository/download/Rehlds_Publish/1620:id/rehlds-dist-0.2-SNAPSHOT.zip and post logs before crash.

**Comment by riva2014** [comment]
Простите , я не понимаю что я должен сделать ? Я зарегистрировался там .

**Comment by latinas** [comment]
Download ReHLDS build from link Asmodai given and install it. After this, when server will crash, show your logs

**Comment by riva2014** [comment]
ReHLDS 637 bugfixed
[drwtsn32.txt](https://github.com/dreamstalker/rehlds/files/83806/drwtsn32.txt)

**Comment by theAsmodai** [comment]
Please provide the last line of server log before crash.

**Comment by riva2014** [comment]
Тест утром :
L 01/10/2016 - 07:47:07: "eDYrraFbiNKymCgPvxXKpwCKobQpp<17><STEAM_1:0:1104233168
><>" connected, address "201.240.223.214:60561"                                 
L 01/10/2016 - 07:47:09: World triggered "Round_Start"                          
L 01/10/2016 - 07:47:12: "Nur1k<14><STEAM_3:0:1834871286><CT>" say "Liza bot?"  
L 01/10/2016 - 07:47:12: "Nur1k<14><STEAM_3:0:1834871286><CT>" say "Liza bot?"  
L 01/10/2016 - 07:47:15: Kick: "Liza<16><UNKNOWN><>" was kicked by "Console"    
L 01/10/2016 - 07:47:15: "Liza<16><BOT><TERRORIST>" disconnected                
Dropped Liza from server                                                        
Reason:  Kicked                                                                 
Crash Info: sock 0 seq 0 time 1718.511796 realtime 1718.511796 slot -1

**Comment by riva2014** [comment]
Второе падение 
[drwtsn32.txt](https://github.com/dreamstalker/rehlds/files/83925/drwtsn32.txt)
[console_log.txt](https://github.com/dreamstalker/rehlds/files/83926/console_log.txt)

**Comment by theAsmodai** [comment]
Try lastest build, bug should be fixed.

**Comment by riva2014** [comment]
Было всё хорошо , сервер работал в течение 6 часов . На ночь обновил ReChecker , Reunion , SRDetector до последних версий . К сожалению отключил создание дампов , за ночь сервер упал 12 раз . В консоле сервера нечего нет , кроме того что падения происходили при смене карты . Сейчас откатил ReChecker до 1.2 , поскольку 1.4 выложенная на neugomon.ru не загружается .

**Comment by riva2014** [comment]
Exe build: 16:44:12 Jan 10 2016 (638)
[console_log.txt](https://github.com/dreamstalker/rehlds/files/86847/console_log.txt)
[drwtsn32.txt](https://github.com/dreamstalker/rehlds/files/86848/drwtsn32.txt)

**Comment by theAsmodai** [comment]
Second bug is also fixed
