### ISSUE TITLE
"Your .dll (cl_dlls/client.dll) differs from the server's" fix - accepting p48 clients

### ISSUE THREAD

**Issue by Jozodezokokotar** [dreamstalker/rehlds#121]
Hi

While I admire your work, especially the performance boost, the Re-HLDS is so good in mimicking HLDS 6153 behavior - as it keeps rejecting older clients (probably sending incorrect CRC).

I'm getting following error on client "Your .dll cl_dlls/client.dll differs from the server's". And then client disconnects.

Client and server's client.dll do match and I still get an error.
This error can be circumvented if you change few bytes in client-side hw.dll to skip the received CRC check for client.dll.

I also managed to circumvent this by replacing swds.dll with the one from build 5758 and having client.dll matching on client/server.
I tried to disassemble swds.dll and find and remove these checks but I failed. 

I did couple of tests and debugging.
swds 6153 + serverside client.dll new  --> error
swds 6153 + serverside client.dll old (same as clientside) --> error
swds 5758 + serverside client.dll new --> error
swds 5758 + serverside client.dll old (same as clientside) --> client can connect now, all is working
swds 5758 + serverside client.dll old + any (new/old) clientside client.dll always works.

I'm willing to be long-term tester, I'm having private server with public IP, running Opposing Force.
My goal is to make server accept all p48 clients (even those non-steam older ones, by using revemu)

All I'm asking you is to fix the infamous "your .dll(cl_dlls/client.dll) differs from the server's" error.
Could please have a look into the issue?
Let me know if you need more info, affected hl version or temporary RDP access to my server.

[HLDS5758.zip](https://github.com/dreamstalker/rehlds/files/83309/HLDS5758.zip)

Thx!

**Comment by LevShisterov** [comment]
crcclientdll "1"
in liblist.gam should solve this.

**Comment by Jozodezokokotar** [comment]
crcclientdll "1" - tested, as well as crcclientdll "0" - does not work.
