### ISSUE TITLE
ReHLDS does not handle pingboost commandline option

### ISSUE THREAD

**Issue by ViBENo1** [dreamstalker/rehlds#127]
i don't know how should i prove it. i think it's not necessary. everyone can test it. may i'm not the only one who tried to figure out what's wrong. i compared the ReHLDS latest stable and some recent snapshots with the original HLDS. the result is that `pingboost` does not affects on ReHLDS. no matter what value i use and what version i try it does not set any priorities.

**Comment by ViBENo1** [comment]
any answers...?

**Comment by LevShisterov** [comment]
`pingboost` parameter is solely handled by hlds_linux module and shoudn't be affected by engine. So you have to prove your words with steps to reproduce and meter.

**Comment by ViBENo1** [comment]
anyone can prove it. just install the latest HLDS on Linux and test `pingboost` with parameter `1` to `3`. it should change the priority and the performance. then do the same with ReHLDS and compare it.

**Comment by LevShisterov** [comment]
You should tell what you did and what results you got.

**Comment by ViBENo1** [comment]
simply installed the latest build on my test server. then i tested the performance with the servers performance with `pingboost` `1` to `3`. very settings have different outputs. setting `3` adds the most priority, setting `2` set less priority but more than setting `1`. then i installed ReHLDS engine on the same server and did the same tests. ReHLDS with `pingboost` command acts like setting `2` i guess. it looks like the server runs with some priority. but if i try to change it no matter which setting i use the output of `rcon stats` commands is always the same. same CPU usage, same performance.

**Comment by theAsmodai** [comment]
LevShisterov, pingboost uses this: https://github.com/dreamstalker/rehlds/blob/267c7eb327d48ffa5e37280506130f9713407f2e/rehlds/engine/net_ws.cpp#L1058
I recheck socket code later.

**Comment by LevShisterov** [comment]
@ViBENo1 
> then i tested the performance
You still didn't specified how did you tested, nor you specified exact data you got.
> it looks like the server runs with some priority
"Some"? What exactly? How did you check it?
> output of rcon stats
Depends on players, map, etc... So you should specify conditions at least.

**Comment by ViBENo1** [comment]
@LevShisterov as i said everyone can test it...i don't know why you cling on this. i can copy tons of outputs but it's not an evidence till i can fake everything if i want. i installed a ZM server with a bunch of plugins for example with 24 slots and with `sys_ticrate 1050`. the only player on the server was me. i also did a test with a DM config with P0DBot too. but whatever. anybody can setup the most common server environments for testing purposes. the real difference will be only the CPU load.

why did i write that the server has some priority? cause if i setup ReHLDS with `pingboost 2` the output will be very similar like HLDS and the server runs about 700-900FPS. if i set `pingboost 3` only HLDS will reach 1000FPS and it runs more stable with it. that's the real problem. ReHLDS acts like nothing changed and till use the same sources and runs with the same performance.

**Comment by LevShisterov** [comment]
Much better.
So, the main problem you see is that FPS with pingboost 3 is lower comparing to usual HLDS on ZM server with one (and the same) player, right?

**Comment by ViBENo1** [comment]
basically yes. ReHLDS cannot reach the same performance with `pingboost 3` as expected. it behaves like you did not set it to 3.
