### ISSUE TITLE
Prevent server/client from sending/requesting same file twice

### ISSUE THREAD

**Issue by Jozodezokokotar** [dreamstalker/rehlds#130]
Hi guys,

just want to ask you if you can implement a solution to avoid this issue?

I've seen this as a request and I encountered the issue myself.
https://github.com/ValveSoftware/halflife/issues/1345

Thx!

**Comment by WPMGPRoSToTeMa** [comment]
In .res file there are should be only resources, that can't be precached by map entities.

**Comment by Jozodezokokotar** [comment]
Well, that's not just about .res files. The problem in original hlds is that same resource might be cached by server many times, thus sending/requesting it to client x times.
I might be wrong, but it seems that server does not check (for example if it reads resources from .res files) whether those files are already cached or not.

**Comment by theAsmodai** [comment]
Done.

**Comment by Jozodezokokotar** [comment]
Wunderbar!
Many thanx!
