### ISSUE TITLE
Function Host_Kick_f is not working correctly

### ISSUE THREAD

**Issue by latinas** [dreamstalker/rehlds#140]
![2016-01-25_00002](https://cloud.githubusercontent.com/assets/10776436/12551024/91ef6316-c378-11e5-8647-cc90c2ce175c.jpg)
Oke. I'll kick myself on userid
![2016-01-25_00003](https://cloud.githubusercontent.com/assets/10776436/12551037/a64500aa-c378-11e5-8c61-b962f85d953b.jpg)
But i am still on the server, was not kicked
And now let's write
![2016-01-25_00004](https://cloud.githubusercontent.com/assets/10776436/12551045/b041a702-c378-11e5-90ad-76992e71ccaf.jpg)
And it's working
![2016-01-25_00005](https://cloud.githubusercontent.com/assets/10776436/12551052/b61ae076-c378-11e5-9a29-8d5fbf5c3b98.jpg)
Please, fix "kick 'userid'" cmd, this cmd absolutely not working. "kick 'name'" cmd is working nice

**Comment by sh4id** [comment]
kick #1

**Comment by latinas** [comment]
@sh4id, not working too

**Comment by latinas** [comment]
Wtf? I checked this now and i was kicked from the server. But when i tried to this an hour it wasn't working. Strange. Thanks for you, @sh4id
