### ISSUE TITLE
Longjump not working (bugged) when using CTF powerup (item_ctflongjump)

### ISSUE THREAD

**Issue by Jozodezokokotar** [dreamstalker/rehlds#143]
Hi
I've been testing rehlds thoroughly on Opposing Force. There are basically two options how to get long jump - by grabbing the well known **item_longjump** or by taking powerup **item_ctflongjump** (it can be dropped)

I noticed that long jump works correctly for the default item_longjump, but is bugged for item_ctflongjump (your jump stops midair like if you hit invisible wall).

Maybe it's related to the following bool value:
https://github.com/dreamstalker/rehlds/blob/101a5f3ea11418abc57370fbcc5804553ab11dff/rehlds/dlls/player.h#L169

Plz fix it guys.

I'm running a password protected server with bugfixed version (rehlds-0.2-20160128.133207-120).
Run the following commands in opfor console to connect the server (will turn it off in a week)
`password rehlds`
`connect 31.31.73.85`

test map 
[longjumptest.zip](https://github.com/dreamstalker/rehlds/files/110444/longjumptest.zip)

Thanks

**Comment by theAsmodai** [comment]
It's a part of the Opposing Force mod, not rehlds.

**Comment by Jozodezokokotar** [comment]
I must disagree. CTF longjump works perfectly with original swds.dll. It's just that rehlds can't emulate this behavior.

If it was part of the original half-life (valve mod) and longjump did not work in any game with rehlds, then it would be ok for you?
In other words, both item_longjump and  item_ctflongjump does not refer to an engine.

Please reopen :-)

**Comment by LevShisterov** [comment]
@Jozodezokokotar 
Please describe your configuration (type of OS, server build) and steps how to reproduce so it works.
And how to use LJ powerup (usual forward+crouch+jump or differently?), also how it looks when works (like usual long jump or differently?).

**Comment by KORDaghlru** [comment]
@Jozodezokokotar
I tried to use longjump and item_ctflongjump on my own server with rehlds, everyting was fine. I tried to play on your server ( 31.31.73.85 ) and longjump worked well, but i couldn't test item_ctflongjump, because CTF map was not available.

**Comment by LevShisterov** [comment]
@Jozodezokokotar 
Investigation revealed that valve removed code that did super jump for LJ powerup. Approximately it was present in 5758 builds and removed in 6xxx. You can fix that in HEX editor: open opfor.dll(.so), search for "jpj" string and replace with "slj". It should be surrounded with other noticeably strings. Don't replace if it is surrounded with a mess of symbols - this is possibly the code area. In op4.6132 .dll "jpj" meets once, in .so it meets two times: string and somewhere in the code.

**Comment by Jozodezokokotar** [comment]
Exactly, you are right. I managed that yesterday, that's why it worked on my server.
I disassembled opfor.dll and found that too. I moved the pointers from jpj to slj for ctf long jump and it works.

Hence, there is a workaround at least.

Anyway, thanks guys for you interest!
I appreciate it.
