### ISSUE TITLE
reHLDS UDP Queries /PHP/

### ISSUE THREAD

**Issue by val4o0o0** [dreamstalker/rehlds#144]
How to get information like server name, players, max players, players list, map, os and etc.. ?
On the web there are bunch of working variants for HLDS, but now for reHLDS i cannot get properly information about the server.
The mainserverinfo is \xFF\xFF\xFF\xFFTSource Engine Query\x00 or something new ?
Can someone give me working variant for php ?

**Comment by IgnacioFDM** [comment]
Any working query for p48 HLDS will be the same for ReHLDS. Anyway, try this one maybe https://github.com/amwdrizz/ServerQuery

**Comment by theAsmodai** [comment]
IgnacioFDM is right.
