### ISSUE TITLE
Raise precache limit

### ISSUE THREAD

**Issue by nEpBep3HuK** [dreamstalker/rehlds#180]
Could you raise the precache limit? 512 is not enough for fun servers such as zombie plague and jailbreak...

**Comment by Arkshine** [comment]
You can't do that unless the client is updated as well.

**Comment by WPMGPRoSToTeMa** [comment]
Resource type?

**Comment by OZone998** [comment]
Well, probabably there is a way to do it without client modification: https://forums.alliedmods.net/showthread.php?t=200826
Of course noew it's not compatible with ReHLDS, but there is source code.

**Comment by Arkshine** [comment]
@OZone998 It's unrelated to the 512 precache limit. This modules is essentially management of sv_downloadurl and unlock limit of 1280 items you can send on a client, which I think has been increased in reHLDS to 4092 (?).

**Comment by OZone998** [comment]
It can reduce number of sound in precache, so it could help in some way.
Yeah, I saw that in pull #161. Unfortunately server with current version of ReHLDS is still crashing when resources exceed 512 limit.

**Comment by WPMGPRoSToTeMa** [comment]
@OZone998 you can use PrecacheGeneric for sounds which are played by SendAudio/"spk"/"speak" etc, but not by EmitSound/EmitAmbientSound. Also you can use PrecacheGeneric for player models.
Generic precache is already extended to max resource count (4096).

**Comment by hellmoss** [comment]
Seek through a sound to go around this?

Example: we have a 10-second sound which has different samples within, for example one from 0:00-0:03 ; 0:04-0:06 ; etc..

Could we somehow set a parameter for the starting point for the emit_sound? (end point is easier to work around, just emit a null sound from same ent, channel through a set_task)

**Comment by hellmoss** [comment]
@In-line @WPMGPRoSToTeMa @Arkshine 

Seek through a sound to go around this?

Example: we have a 10-second sound which has different samples within, for example one from 0:00-0:03 ; 0:04-0:06 ; etc..

Could we somehow set a parameter for the starting point for the emit_sound? (end point is easier to work around, just emit a null sound from same ent, channel through a set_task)

**Comment by hellmoss** [comment]
@In-line @WPMGPRoSToTeMa @Arkshine 

Seek through a sound to go around this for the emitsound type?

Example: we have a 10-second sound which has different samples within; say, from 0:00-0:03 ; 0:04-0:06 ; etc..

Could we somehow set a parameter for the starting point for the emit_sound? (end point is easier to work around, just emit a null sound from same ent, channel through a set_task)

Linking this with .wav format cues somehow? If I observe correctly, wav file cues enable looping for instance..

@dystopm @s1lentq @StevenKal

**Comment by dystopm** [comment]
> @In-line @WPMGPRoSToTeMa @Arkshine
> 
> Seek through a sound to go around this for the emitsound type?
> 
> Example: we have a 10-second sound which has different samples within; say, from 0:00-0:03 ; 0:04-0:06 ; etc..
> 
> Could we somehow set a parameter for the starting point for the emit_sound? (end point is easier to work around, just emit a null sound from same ent, channel through a set_task)
> 
> Linking this with .wav format cues somehow? If I observe correctly, wav file cues enable looping for instance..
> 
> @dystopm @s1lentq @StevenKal

You only pass the sound index through those related sound messages:

> via EmitSound/EmitAmbientSound/SVC_SOUND/SVC_SPAWNSTATICSOUND

And there would be no way to alter engine behaviour to achive that with no client side further modifications

**Comment by hellmoss** [comment]
@dystopm What if we change the volume dynamically, theres a starting parameter for that or that would also require client-side modification?
