### ISSUE TITLE
which metamod version should we use ?

### ISSUE THREAD

**Issue by omertelli** [dreamstalker/rehlds#189]
my question is clear.
Which metamod version should we use for the best performance ?
metamod 1.21.1-am or what ?

**Comment by Phantom-J** [comment]
[url=http://metamod-p.sourceforge.net/]Metamod-p 1.21p37[/url]

**Comment by omertelli** [comment]
what is the diffrent [this ](https://github.com/dreamstalker/metamod-p) and [this ](http://metamod-p.sourceforge.net/) version ?

**Comment by Phantom-J** [comment]
Metamod from the first link you given is not usable for server. That fork is just for making benchmark tests. [More details about benchmark and about changes in dreamstalker's Metamod version](https://github.com/dreamstalker/rehlds/wiki/The-performance-optimization-month:-results#metamod-stock-vs-optimized)
