### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by omertelli** [dreamstalker/rehlds#190]
I got a few erros

> [root@localhost
> rehlds]#  ./gradlew --max-workers=1 clean buildRelease
> :buildSrc:compileJava UP-TO-DATE
> :buildSrc:compileGroovy UP-TO-DATE
> :buildSrc:processResources UP-TO-DATE
> :buildSrc:classes UP-TO-DATE
> :buildSrc:jar UP-TO-DATE
> :buildSrc:assemble UP-TO-DATE
> :buildSrc:compileTestJava UP-TO-DATE
> :buildSrc:compileTestGroovy UP-TO-DATE
> :buildSrc:processTestResources UP-TO-DATE
> :buildSrc:testClasses UP-TO-DATE
> :buildSrc:test UP-TO-DATE
> :buildSrc:check UP-TO-DATE
> :buildSrc:build UP-TO-DATE
> :dep/bzip2:clean
> :dep/cppunitlite:clean UP-TO-DATE
> :flightrec/decoder:clean UP-TO-DATE
> :flightrec/decoder_api:clean UP-TO-DATE
> :rehlds:clean
> :dep/bzip2:compileReleaseBzip2StaticLibraryBzip2Bz2_main
> :dep/bzip2:compileReleaseBzip2StaticLibraryBzip2Bz2_pch
> :dep/bzip2:createReleaseBzip2StaticLibrary
> :dep/bzip2:releaseBzip2StaticLibrary
> :rehlds:generateAppVersion
> :rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_pch
> In file included from /home/genki/rehlds/rehlds/rehlds/public/rehlds/osconfig.h(92),
>                  from /home/genki/rehlds/rehlds/rehlds/rehlds/precompiled.h(5),
>                  from /home/genki/rehlds/rehlds/rehlds/rehlds/precompiled.cpp(1):
> /usr/lib/gcc/x86_64-redhat-linux/4.4.7/include/smmintrin.h(32): error: #error directive: "SSE4.1 instruction set not enabled"
>   # error "SSE4.1 instruction set not enabled"
>     ^
> compilation aborted for /home/genki/rehlds/rehlds/rehlds/rehlds/precompiled.cpp (code 2)
> :rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_pch FAILED
> FAILURE: Build failed with an exception.
> - What went wrong:
>   Execution failed for task ':rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_pch'.
>   A build operation failed.
>     C++ compiler failed while compiling precompiled.cpp.
>   See the complete log at: file:///home/genki/rehlds/rehlds/rehlds/build/tmp/compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_pch/output.txt
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
>   BUILD FAILED
>   Total time: 18.264 secs

---

> [root@localhost rehlds]# cat /etc/_release_
> CentOS release 6.7 (Final)
> CentOS release 6.7 (Final)
> CentOS release 6.7 (Final)
> 
> [root@localhost rehlds]# uname -a
> Linux localhost.localdomain 2.6.32.71 #2 SMP Wed Mar 23 01:01:07 EET 2016 x86_64 x86_64 x86_64 GNU/Linux
> 
> [root@localhost rehlds]# uname -r
> 2.6.32.71

**smmintrin.h 31-33 lines**

> # ifndef **SSE4_1**
> 
> #error "SSE4.1 instruction set not enabled"
> # else

**Cpu information**

> [root@localhost rehlds]# cat /proc/cpuinfo
> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 44
> model name      : Intel(R) Xeon(R) CPU           X5660  @ 2.80GHz
> stepping        : 2
> cpu MHz         : 2792.990
> cache size      : 12288 KB
> physical id     : 1
> siblings        : 12
> core id         : 0
> cpu cores       : 6
> apicid          : 32
> initial apicid  : 32
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 11
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 popcnt aes lahf_lm ida arat tpr_shadow vnmi flexpriority ept vpid
> bogomips        : 5585.98
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 40 bits physical, 48 bits virtual
> power management:

**Comment by theAsmodai** [comment]
Try add an '-xHost' option to https://github.com/dreamstalker/rehlds/blob/master/rehlds/build.gradle#L159
It allows all optimizations for your processor. If it will not help then add '-DSSE4_1' to same line.

**Comment by omertelli** [comment]
@theAsmodai  thats work thanks but i get another error now

> [root@localhost rehlds]# ./gradlew --max-workers=1 clean buildRelease
:buildSrc:compileJava UP-TO-DATE
:buildSrc:compileGroovy UP-TO-DATE
:buildSrc:processResources UP-TO-DATE
:buildSrc:classes UP-TO-DATE
:buildSrc:jar UP-TO-DATE
:buildSrc:assemble UP-TO-DATE
:buildSrc:compileTestJava UP-TO-DATE
:buildSrc:compileTestGroovy UP-TO-DATE
:buildSrc:processTestResources UP-TO-DATE
:buildSrc:testClasses UP-TO-DATE
:buildSrc:test UP-TO-DATE
:buildSrc:check UP-TO-DATE
:buildSrc:build UP-TO-DATE
:dep/bzip2:clean
:dep/cppunitlite:clean UP-TO-DATE
:flightrec/decoder:clean UP-TO-DATE
:flightrec/decoder_api:clean UP-TO-DATE
:rehlds:clean
:dep/bzip2:compileReleaseBzip2StaticLibraryBzip2Bz2_main
:dep/bzip2:compileReleaseBzip2StaticLibraryBzip2Bz2_pch
:dep/bzip2:createReleaseBzip2StaticLibrary
:dep/bzip2:releaseBzip2StaticLibrary
:rehlds:generateAppVersion
:rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_pch
:rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_src
"/home/genki/rehlds/rehlds/rehlds/rehlds/rehlds_api_impl.cpp": using precompiled header file "/home/genki/rehlds/rehlds/rehlds/build/pch/releaseRehldsFixesRehlds_swds_engineSharedLibrary_x86_release_rehldsFixes/sv_main.pchi"
/home/genki/rehlds/rehlds/rehlds/rehlds/rehlds_api_impl.cpp(36): error: namespace "std" has no member "vector"
  std::vector<plugin_api_t *> g_PluginApis;
       ^
/home/genki/rehlds/rehlds/rehlds/rehlds/rehlds_api_impl.cpp(36): error: expected a ";"
  std::vector<plugin_api_t *> g_PluginApis;
             ^
/home/genki/rehlds/rehlds/rehlds/rehlds/rehlds_api_impl.cpp(39): error: identifier "g_PluginApis" is undefined
        for (auto it = g_PluginApis.begin(), end = g_PluginApis.end(); it != end; ++it) {
                       ^
/home/genki/rehlds/rehlds/rehlds/rehlds/rehlds_api_impl.cpp(143): error: identifier "g_PluginApis" is undefined
                g_PluginApis.push_back(api);
                ^
compilation aborted for /home/genki/rehlds/rehlds/rehlds/rehlds/rehlds_api_impl.cpp (code 2)
:rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_src FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':rehlds:compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_src'.
> A build operation failed.
      C++ compiler failed while compiling rehlds_api_impl.cpp.
  See the complete log at: file:///home/genki/rehlds/rehlds/rehlds/build/tmp/compileReleaseRehldsFixesRehlds_swds_engineSharedLibraryRehlds_swds_engineRehlds_src/output.txt
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 28.282 secs

**Comment by theAsmodai** [comment]
Try to update g++ package.

**Comment by omertelli** [comment]
> [root@localhost home]# Package gcc-c++-4.4.7-16.el6.x86_64 already installed and latest version

i try put #include <vector> in rehlds_api_impl.cpp now i got this error

> `See file:///home/genki/rehlds/rehlds/rehlds/build/tmp/linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary/output.txt for all output for linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary.
> linking libengine_i486.so failed.
> icpc: warning #10237: -lcilkrts linked in dynamically, static library not available
> ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.4.7//libstdc++.a when searching for -lstdc++
> ld: cannot find -lstdc++
> 
> Finished linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary, see full log file:///home/genki/rehlds/rehlds/rehlds/build/tmp/linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary/output.txt.
> `

already installed glibc and libstdc

**Comment by theAsmodai** [comment]
You need libstdc++-static

**Comment by omertelli** [comment]
i did compile it another machine , thanks @theAsmodai

**Comment by jkerh** [comment]
wtf. this retard @omertelli (csduragi.com owner) heard rehlds project. this guy force fake slowhacking servers.

https://github.com/ValveSoftware/steam-for-linux/issues/1014#issuecomment-40568748

**Comment by LevShisterov** [comment]
Linking of libstdc++ was changed from static to dynamic, so probably this issue was resolved.
