### ISSUE TITLE
When you walk up on a ramp it get's really jerky

### ISSUE THREAD

**Issue by strazdinsivars** [dreamstalker/rehlds#193]
When i run my server same map for few hours it stars to lag when walking up ramp
I found thread with same problem, but they have no resolution
http://forums.steampowered.com/forums/showthread.php?t=142350

**Comment by theAsmodai** [comment]
I think it's caused by decreasing in accuracy of `double realtime` over long time.

**Comment by In-line** [comment]
Bug fix was confirmed only for HL and CS. Other mods are still in TODO state.

**Comment by WPMGPRoSToTeMa** [comment]
@In-line the problem is fixed for all mods (because basically it is mode-independent), but the problem is clientdata variables that can send non-fixed gametime.

**Comment by hajimura** [comment]
Should be closed as fixed
