### ISSUE TITLE
Metamod Plugins: DProto & VoiceTranscoder Not Working

### ISSUE THREAD

**Issue by Ghost90** [dreamstalker/rehlds#194]
Metamod Plugins: DProto & VoiceTranscoder Not Working ( HLDS Downloaded From SteamCMD )

DProto Not Working Ver 0.9.548 & 0.9.356

**Comment by Ni3znajomy** [comment]
Dproto won't work on ReHLDS. Use Reunion instead. http://cs.rin.ru/forum/viewtopic.php?f=29&t=69235
VTC support ReHLDS since 2.0. http://cs.rin.ru/forum/viewtopic.php?f=29&t=63814 or you can use revoice http://www.dedicated-server.ru/vbb/showthread.php?t=26598
