### ISSUE TITLE
Null pointer in memcpy function

### ISSUE THREAD

**Issue by Chuvi-w** [dreamstalker/rehlds#2]
https://github.com/dreamstalker/rehlds/blob/master/rehlds/testsuite/player.cpp#L530
The null pointer is passed into 'memcpy' function.
Probably, there should be memcpy(&m_CurrentTm, t, sizeof(m_CurrentTm)); ?

**Comment by dreamstalker** [comment]
Thank you for reporting the bug!
To be honest, I'm surprised how it was working with this flaw. Probably this code is unreachable during app execution, but I have to check it.
I'm just curious, how did you found this bug? Have you used any code analyzers or just caught a crash?
And btw, you may send pull request to fix it :)
