### ISSUE TITLE
Problem with this *.amxx code

### ISSUE THREAD

**Issue by levsan** [dreamstalker/rehlds#203]
Hello,
By using ReHLDS engine, this part of *.amxx scripting code doesn't work at all:

```
    static iButton; iButton = pev(id, pev_button)
    static iOldButton; iOldButton = pev(id, pev_oldbuttons)

    if((iButton & IN_USE) && !(iOldButton & IN_USE))
    {
        --------------------
    }

```

Is there any way of getting it works, or maybe it's a bug?
I tried old ReHLDS builds, but the only possible fix is the original engine.

---

Thanks and sorry for my poor English.

**Comment by levsan** [comment]
Nobody knows?

**Comment by IgnacioFDM** [comment]
Give us a test plugin to reproduce this bug, not just a snippet

**Comment by levsan** [comment]
[zp_zclass_houndeye.zip](https://github.com/dreamstalker/rehlds/files/251109/zp_zclass_houndeye.zip)

Hello,
For example, this zombie class (attached)

**Comment by LevShisterov** [comment]
Please reduce it to minimal plugin that will show the issue.

**Comment by levsan** [comment]
[test.zip](https://github.com/dreamstalker/rehlds/files/253489/test.zip)
Hello,
I reduced to a simple plugin only with that function. Again, if I use the plugin on a server with normal engine, it works, but on ReHLDS, it doesn't.

---
Thanks for your support.

**Comment by WPMGPRoSToTeMa** [comment]
```public CmdStart(id)```
->
```public CmdStart(id, uc)```

```pev(id, pev_button)```
->
```get_uc(uc, UC_Buttons)```

**Comment by WPMGPRoSToTeMa** [comment]
https://github.com/dreamstalker/rehlds/blob/df6b4a6f915e8a1d11c34d37764c51d8a8beb524/rehlds/engine/sv_user.cpp#L1621

**Comment by IgnacioFDM** [comment]
@WPMGPRoSToTeMa

Anyway, I would probably consider this a bug. ReHLDS should have the same behavior as HLDS

**Comment by WPMGPRoSToTeMa** [comment]
@IgnacioFDM anyway getting buttons from entvars in CmdStart is incorrect.

**Comment by In-line** [comment]
Closing as non active.
