### ISSUE TITLE
How do I filter server-sent commands? (not directly related to project)

### ISSUE THREAD

**Issue by satnatantas** [dreamstalker/rehlds#204]
Hi.

I have an urge problem: https://github.com/ValveSoftware/halflife/issues/1497
 `cl_filterstuffcmd` does not screen commands well. I wanted to screen them using simple firewall (like WinDivert's `netfilter`) but I could not find plaintext commands in dump of server traffic (ip.SrcAddr == server address).

How do I do it?

From demo record I know that server sends me the following:

```
cl_filterstuffcmd 0
fps_max 102
cl_pitchspeed 225 
m_yaw 0.022 
default_fov 90
lookspring 0
```

Attached the dump of traffic going to localhost: 27005, 27015, 27025, 62128, 62129 (hl.exe does not have other ports open) which should contain these commands.
[dump2.zip](https://github.com/dreamstalker/rehlds/files/236616/dump2.zip)

**Comment by LevShisterov** [comment]
Basically the traffic in GoldSource is encrypted so you can't do text lookup.

**Comment by satnatantas** [comment]
Can I decrypt it using sinffed keys?

**Comment by LevShisterov** [comment]
It is possible, but you have to monitor connection from the beginning. Anyway, it doesn't looks like a good idea for firewall task. For client side it is easier and better to use some protector plugin.

**Comment by satnatantas** [comment]
I cannot inject unknown DLLs in Steam version.

It is perfectly fine for me to monitor connection from the start: WinDivert has a common library for sniffin packets.

I am all ears.

**Comment by theAsmodai** [comment]
VAC detects cheats only by their md5 hash. I don't know anyone who was banned for protector.

**Comment by satnatantas** [comment]
How do I find one? Cannot find anything interesting ATM.

WIll I be able to understand encryption by reading ReHLDS sources?

**Comment by theAsmodai** [comment]
Check Netchan_Process

**Comment by satnatantas** [comment]
Should I be interested in `void COM_UnMunge2(unsigned char *data, int len, int seq)`? Is this all the encryption?

Is there any initialisation vector transferred upon connection?

**Comment by theAsmodai** [comment]
> Is there any initialisation vector transferred upon connection?

No, all you need is to read a packet header and decrypt the data.

**Comment by satnatantas** [comment]
Does it depend on protocol version?

**Comment by LevShisterov** [comment]
No.

2016-04-28 20:48 GMT+05:00 satnatantas <notifications@github.com>:

**Comment by satnatantas** [comment]
May I ask more questions trying to save my time or is it undesirable?

Is `COM_Munge2` symmetrical to `COM_UnMunge2`?

**Comment by theAsmodai** [comment]
One function is the inverse of the other.

**Comment by satnatantas** [comment]
I have more questions.

`void COM_UnMunge2(unsigned char *data, int len, int seq)`

So, I need to maintain a valid `seq` throuout the stream. Is the `seq` value included in every packet without obfuscation? 

```C++
        ...
	// Prepare the packet header
	w1 = chan->outgoing_sequence | (send_reliable << 31);
        ...
	MSG_WriteLong(&sb_send, w1);
        ...
		COM_Munge2(sb_send.data + 8, sb_send.cursize - 8, (unsigned char)(chan->outgoing_sequence - 1));
```

What I see here is:
- the outgoing sequence is ORed with the a flag
- the result is prepended to the message
- the obfuscation skips first 8 bytes (two sequence numbers).

Am I getting it right?

The most important question is: are the client commands (such as `cd eject`, `record DEMO`, etc) sent using reliable channel? The problem is that dropping certain packets would induce excessive traffic drown because of resent packets.

**Comment by satnatantas** [comment]
And the third question: what is QCC/QCC2? I read about some protectors and I see that it is used to control client CVars but I cannot find it in code.

**Comment by theAsmodai** [comment]
Yes, you are right.
QCC = QueryClientCvar value.

**Comment by satnatantas** [comment]
The most important question is: are the client commands (such as cd eject, record DEMO, etc) sent using reliable channel? The problem is that dropping certain packets would induce excessive traffic drown because of resent packets.

Will I need to modify every packet after I drop even one?

**Comment by theAsmodai** [comment]
You can fill packet payload with 0x1 bytes (clc_nop) instead of dropping reliable packets. It will be simplier solution.

**Comment by satnatantas** [comment]
`void EXT_FUNC QueryClientCvarValue(const edict_t *player, const char *cvarName)`

What function passes the client response to server/plugins?

**Comment by satnatantas** [comment]
Found them.
`void SV_ExecuteClientMessage(client_t *cl)`
->
`void EXT_FUNC SV_HandleClientMessage_api(IGameClient* client, int8 opcode)`
-> through lookup table
`void SV_ParseCvarValue2(client_t *cl)`

**Comment by satnatantas** [comment]
Does the server expects any response from client CMD?

**Comment by theAsmodai** [comment]
You asking about cmd from client to server or vice versa?

**Comment by satnatantas** [comment]
Server executes a command in client's console, does it expect any result?

This list makes me think that there is no such functionality:
```C++
clc_func_t sv_clcfuncs[] = {
		{ clc_bad, "clc_bad", NULL },
		{ clc_nop, "clc_nop", NULL },
		{ clc_move, "clc_move", &SV_ParseMove },
		{ clc_stringcmd, "clc_stringcmd", &SV_ParseStringCommand },
		{ clc_delta, "clc_delta", &SV_ParseDelta },
		{ clc_resourcelist, "clc_resourcelist", &SV_ParseResourceList },
		{ clc_tmove, "clc_tmove", NULL },
		{ clc_fileconsistency, "clc_fileconsistency", &SV_ParseConsistencyResponse },
		{ clc_voicedata, "clc_voicedata", &SV_ParseVoiceData },
		{ clc_hltv, "clc_hltv", &SV_IgnoreHLTV },
		{ clc_cvarvalue, "clc_cvarvalue", &SV_ParseCvarValue },
		{ clc_cvarvalue2, "clc_cvarvalue2", &SV_ParseCvarValue2 },

		{ clc_endoflist, "End of List", NULL },
};```

**Comment by WPMGPRoSToTeMa** [comment]
@satnatantas if server sends unknown command to client then client sends it back to server via clc_stringcmd.

**Comment by satnatantas** [comment]
Thanks.

I have tried making a static lib from ReHLDS and using it from another project. I almost succeeded (I fixed compilation settings in several places to reflect ReHLDS ones) but I cannot fix this one:

```
3>------ Build started: Project: netdump, Configuration: Release Win32 ------
...skipped...
3>firewall\rehlds-master\rehlds\engine\tmessage.cpp(403): error C4703: potentially uninitialized local pointer variable 'pCurrentText' used```

Question is: why is this thing being compiled if I did not include `tmessage.cpp` from anywhere?

**Comment by satnatantas** [comment]
What I expect: I include headers only and my own code gets linked against swdsd.lib without compiling anything.
What I get: some source file gets compiled despite being outside the source directories.

`swdsd.lib(common.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance (TaskId:103)` - is this message relevant?

**Comment by satnatantas** [comment]
I am including `precompiled.h` from ReHLDS, `tmessage.h` gets included as well. What I do not understand is why `tmessage.cpp` is recompiled despite the library present.

**Comment by satnatantas** [comment]
Interestingly, I get exactly the same message if I delete `tmessage.cpp`. This makes me think that there is some information included in `.lib` files which makes VS emit this error.

**Comment by satnatantas** [comment]
I am getting following error while building ReHLDS after I disable `Whole program optimisation` (`/GL`) and switch to static library building (I need it to reuse the code).

```
...skipped some log...
3>firewall\rehlds-master\rehlds\engine\tmessage.cpp(403): error C4703: potentially uninitialized local pointer variable 'pCurrentText' used.
```

Why does it treat warning (https://msdn.microsoft.com/en-us/library/jj851030.aspx) as an error? `/wd4703` does not suppress it.

I do not get this error when I build ReHLDS as DLL with `/GL`, I do not get this error when I build ReHLDS as static library with `/GL`, I start getting this after I switch to static library and switch `/GL` off.

**Comment by satnatantas** [comment]
Changing 
`	char *pCurrentText;`

to 
`	char *pCurrentText=0;`

fixed it. I hope that it won't change the program behaviour.

**Comment by satnatantas** [comment]
I know I asked many questions, ignore this one if you want.

I am inversing this piece of code which I gathered from Netchan_Transmit.

```C++
	w1 = outgoing_sequence | (send_reliable << 31);
	w2 = incoming_sequence | (incoming_reliable_sequence << 31);

	send_reliable_fragment = false;

	if (send_reliable && send_reliable_fragment)
	{
		w1 |= (1 << 30);
	}

	chan->outgoing_sequence++;

	MSG_WriteLong(&sb_send, w1);
	MSG_WriteLong(&sb_send, w2);
	COM_Munge2(sb_send.data + 8, sb_send.cursize - 8, (unsigned char)(outgoing_sequence - 1));
```

Here is what I turned it into:
```C++
	net_message.data=data;
	MSG_BeginReading();
	w1 = MSG_ReadLong();
	w2 = MSG_ReadLong();

	if (w1 & (1 << 30))
	{
		send_reliable = true;
		send_reliable_fragment = true;
		w1 ^= (1 << 30);
	}

	outgoing_sequence = w1 & ~(1 << 31);
	incoming_sequence = w2 & ~(1 << 31);

	incoming_reliable_sequence = w2 >> 31;
	COM_UnMunge2(&net_message.data[8], net_message.cursize - 8, outgoing_sequence );
```


Problem is, it is not giving any intelligible output.
[Release.zip](https://github.com/dreamstalker/rehlds/files/545085/Release.zip)

Here is a sample traffic which should at very least contain the server-sent command `fps_max 100`. dmp contains the output of modified WinDivert's netdump utility which now deobfuscates the HLDS traffic and spits it after raw traffic dump. `unobf_s_bin` contains the output of following code:

```C++
			uint64_t plen = packet_len;
			static char pad[7] = { 0 };
			fwrite(&plen, sizeof(plen), 1, out);
			fwrite(packet, plen, 1, out);
			fwrite(pad, 1, 7 - (plen + sizeof(plen)) % 8, out);
```

i.e. the packet length is written, then the packet and then the padding. You may try sending commands to yourself.

**Comment by WPMGPRoSToTeMa** [comment]
> I am inversing this piece of code which I gathered from Netchan_Transmit.

You can just take code from `Netchan_Process`.

**Comment by satnatantas** [comment]
Receiving code from `Netchan_Process` seems to be different: 
Netchan_Process: `COM_UnMunge2(&net_message.data[8], net_message.cursize - 8, sequence & 0xFF);`
Netchan_Transmit: `COM_Munge2(sb_send.data + 8, sb_send.cursize - 8, (unsigned char)(chan->outgoing_sequence - 1));
In the former the `sequence` is ANDed with 0xFF, in the latter it isn't.

Anyways, I tried this code as well and it did not produce intelligible output:
```C++
	MSG_BeginReading();
	unsigned int sequence = MSG_ReadLong();
	unsigned int sequence_ack = MSG_ReadLong();

	unsigned int reliable_message = sequence >> 31;
	unsigned int reliable_ack = sequence_ack >> 31;
	qboolean message_contains_fragments = sequence & (1 << 30) ? true : false;
	
	COM_UnMunge2(&net_message.data[8], net_message.cursize - 8, sequence & 0xFF);
```

**Comment by satnatantas** [comment]
Is `m_pfnProcessIncomingNet` in any way important for decoding?

**Comment by WPMGPRoSToTeMa** [comment]
> Receiving code from `Netchan_Process` seems to be different:

Cast to `unsigned char` is the same as `& 0xFF`.
> Is `m_pfnProcessIncomingNet` in any way important for decoding?

No.
> Anyways, I tried this code too and it did not produce intelligible output as well:

Can you show any packet?

**Comment by satnatantas** [comment]
>Cast to unsigned char is the same as & 0xFF.

I see that `seq` is used as `int` in `COM_Unmunge2`. For example, here it is XORed with `int`: `c ^= seq;`Am I wrong?

>Can you show any packet?

Sure. Archive includes output of my code.
[one packet.zip](https://github.com/dreamstalker/rehlds/files/545850/one.packet.zip)

**Comment by WPMGPRoSToTeMa** [comment]
You should read only UDP data from packet, but you read all data from packet including IPv4 and UDP headers.

**Comment by satnatantas** [comment]
>You should read only UDP data from packet, but you read all data from packet including IPv4 and UDP headers.

I am not, it is payload. Am I wrong? I.e. do you see any specific data which makes you think that it is not just payload?

**Comment by satnatantas** [comment]
I am finally getting the output which I expect.

Really though, is the coding happening in `Netchan_transmit` just the same as in decoding in`Netchan_Process` despite some visual difference?

**Comment by WPMGPRoSToTeMa** [comment]
@satnatantas yep, the difference is only in call `COM_Munge2`/`COM_UnMunge2`.

**Comment by satnatantas** [comment]
I see that every command which server sends looks like that: `0x33 (opcode) 0x05 (the length of a command with null terminating byte) "echo" 0x00`

Yet, I cannot see any occurrence of regex `MSG_WriteByte\(.*51.*\)` or `MSG_WriteByte\(.*0x33.*\)`. What part of code produces the 0x33 byte?

**Comment by theAsmodai** [comment]
51 is svc_director message.  It's used by gamedll.

**Comment by satnatantas** [comment]
I do not see `svc_director` mentioned anywhere either. Is it a part of closed binary?

**Comment by satnatantas** [comment]
Where is `pfnClientCommand` pointer initialised?

**Comment by satnatantas** [comment]
Are all messages built this way: `opcode length message`? I am deciding whether I should parse messages or rely on the luck.

**Comment by satnatantas** [comment]
Will I break anything if I search for `0x33 Length 0x10 string` (so that length of the string matches `Length`) and replace found commands?

**Comment by theAsmodai** [comment]
You should check that the message is long enough for a replacement.

**Comment by satnatantas** [comment]
@theAsmodai thanks for the tip, fixed it. Other than that, how likely is it that I will replace useful data?

I am thinking about using std::isprint from cctype but this is not future proof from my PoV.

**Comment by LevShisterov** [comment]
Probably it is not a code forum.
