### ISSUE TITLE
amx_map server crash 

### ISSUE THREAD

**Issue by vase070** [dreamstalker/rehlds#208]
so when i change map via amx_map lets say "amx_map fy_snow" the server will crash with 
"Segmentation fault" in server console these are the plugins i use 

http://prntscr.com/b4mdvu

**Comment by IgnacioFDM** [comment]
You will need to narrow down the issue. First make sure it doesn't crash if you disable amxmodx entirely. Then, by trial and error disable plugins until you can figure the specific plugin causing the server to crash.

**Comment by WPMGPRoSToTeMa** [comment]
> First make sure it doesn't crash if you disable amxmodx entirely.
@IgnacioFDM how will he do that without amxmodx?

**Comment by LevShisterov** [comment]
Possibly via **changelevel**.

**Comment by IgnacioFDM** [comment]
Yes, use ```changelevel``` of course to test without amxmodx

**Comment by Arkshine** [comment]
AMXX dev version?

**Comment by csoyuncu** [comment]
amxx v1.8.3-d-5066 has no problem.

**Comment by In-line** [comment]
Closing as non active.
