### ISSUE TITLE
Map Overview bugged

### ISSUE THREAD

**Issue by Nemesis31** [dreamstalker/rehlds#209]
Hello,

the overview's maps on CS 1.6 are bugged when your resolution in-game is greater than 1024: see screenshots (the 2nd screenshot is here to prove that the placement of the CT in the overview is wrong).

![overview_bug_cs](https://cloud.githubusercontent.com/assets/16542379/15306461/006252a4-1bcb-11e6-928b-b9e60f2f22a7.jpg)
![overview_bug_cs_1](https://cloud.githubusercontent.com/assets/16542379/15306462/006b1628-1bcb-11e6-915f-0c531d1ed068.jpg)

It would be very nice if you can fix this "minor" problem !

Thanks in advance !

**Comment by voed** [comment]
Its client-side problem.
