### ISSUE TITLE
wrong build number?

### ISSUE THREAD

**Issue by ViBE-HU** [dreamstalker/rehlds#210]
the latest pure version identify itself as build **6132**. why not **6153**? is it a bug?

**Comment by theAsmodai** [comment]
No, this is not essential.

**Comment by ViBE-HU** [comment]
@theAsmodai oh, okay. it just really tricked me out when i did some tests and i tried to figure out which engine/version runs. is it possible to change it manually anyway?

**Comment by LevShisterov** [comment]
See `build_number` function and `__BUILD_DATE__` define.
