### ISSUE TITLE
multicore support

### ISSUE THREAD

**Issue by csoyuncu** [dreamstalker/rehlds#218]
rehlds doesnt support multicore. How can we fix this at i7 cpu ?

**Comment by theAsmodai** [comment]
No. HLDS has a singe-threaded design.

**Comment by Maxpain177** [comment]
Еще один идиот, который даже близко не понимает понятие мультипоточности в приложениях.

**Comment by Phantom-J** [comment]
@Maxpain177, if you have right term of the multithreading, explain him too. No need to insult

**Comment by csoyuncu** [comment]
@Maxpain177 stupid.

**Comment by Maxpain177** [comment]
@csoyuncu You have no brains. How can we fix this?

**Comment by csoyuncu** [comment]
@theAsmodai thanks.
