### ISSUE TITLE
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.

### ISSUE THREAD

**Issue by csoyuncu** [dreamstalker/rehlds#219]
when i opened my server, console gives this error "[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed."

any fix for this error ? linux centos 5.10 32 bit.

version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 23:08:30 Jun 15 2016 (795)
ReHLDS API version 2.13

**Comment by velesgs** [comment]
Эту хрень нельзя вырезать совсем?

**Comment by s1lentq** [comment]
Try [this](https://developer.valvesoftware.com/wiki/SteamCMD#Unable_to_locate_a_running_instance_of_Steam)
