### ISSUE TITLE
sv_downloadurl 

### ISSUE THREAD

**Issue by Cira95** [dreamstalker/rehlds#223]
sv_downloadurl doesn't work.Do you have solution for that ?

**Comment by LevShisterov** [comment]
Please supply more info on this. At least client console output on joining the server (set developer 1 on the client before connecting).

**Comment by Cira95** [comment]
https://imgur.com/9rdFT0n
I am not sure,but now i think that this isn't rehlds problem,am i right?

**Comment by WPMGPRoSToTeMa** [comment]
What do you mean by that screenshot?

**Comment by Cira95** [comment]
We use fdl,i was thought that it didn't work.I listened Lev,and gave him "more" info.As you can see when i try to connect on server,i downloaded files from fdl which mean that everything is ok and i don't have a problem with rehlds.I was thought that fdl didn't work cause rehlds :D . From this ss you can see that fdl is working.
