### ISSUE TITLE
Unique IDs of non-steam players?

### ISSUE THREAD

**Issue by satnatantas** [dreamstalker/rehlds#228]
I am playing on at least two servers with ReHLDS and I have noticed that non-steam players now have IDs like
STEAM_0:1:6755399441056321

instead of (for example):
STEAM_0:0:9185091438328296010

What it means for me is that I can no longer identify non-steam players even if they do not fake their hardware IDs while I theoretically could do it earlier (with subtracting constant value from that big 64bit number).

What's the reason for that? Is it a matter of some plugin or is it how the core of ReHLDS behaves?

**Comment by theAsmodai** [comment]
Rehlds core supports only the steam clients.

**Comment by satnatantas** [comment]
Sure it does, but there are dual proto patches. You said that ReHLDS is binary compatible with HLDS, does it mean that all patches should work or are there exceptions from that rule?

**Comment by WPMGPRoSToTeMa** [comment]
Patch can be binary incompatible.

**Comment by theAsmodai** [comment]
satnatantas, you need to ask your questions in a support topics of these patches/mods.

**Comment by forid786** [comment]
Why would you even bother with patches? Just use Reunion. Spoofing will always be an issue on nonsteam servers, unless someone can create us a  binary file. Which emulates an ID for a client based on a more reliable method, and it is injected through server precache + MD5 checked always. But that's a whole different topic, not for here. By the way, if anyone can help me accomplish this, message me. I know TrackerUI.dll (created by KGB hosting) and as such block DLL downloads from servers, but I know it can be bypassed.

**Comment by satnatantas** [comment]
Reunion is what I call a patch.

Right now IDs which I see in Complexity analyzer are kind of 0x1800.....00xxx . I know that VALVE_ID may be faked but right now I cannot even distinguish players who don't fake it.

**Comment by forid786** [comment]
@satnatantas As stated above, you need to ask these questions specifically related to Reunion in their designated forums / threads. This isn't a ReHLDS issue at all.
