### ISSUE TITLE
Question about precache

### ISSUE THREAD

**Issue by Ghost90** [dreamstalker/rehlds#233]
Does ReHLDS supports more than 512 precache limit ?

**Comment by Mistrick** [comment]
Without clientside changes this impossible.

**Comment by Ghost90** [comment]
yea i know but if i change

server.h ->

#define HL_MODEL_MAX 512
#define HL_GENERIC_MAX 512
#define HL_EVENT_MAX 256

will work on server?

**Comment by Mistrick** [comment]
If you change server side, you need client which can use that server. Default client can't connect for changed server or smth else.

**Comment by mittorn** [comment]
Apply my gcc patch, run GDB and check it.
It is possible to increase server limit, but maybe you need to modify netcode to send only limited amount of data to clients (for example, only 512 visible models and model indexes should be rebased for each client).

**Comment by In-line** [comment]
Dup. #180
