### ISSUE TITLE
Update Signatures for gamedata (Amxmodx 1.8.3)

### ISSUE THREAD

**Issue by Skumek** [dreamstalker/rehlds#237]
We have several problems because you provide bad signatures in Re-Amxmodx build.

L 08/13/2016 - 18:23:07: [CSTRIKE] BuyGunAmmo is not available
L 08/13/2016 - 18:23:07: [CSTRIKE] GiveNamedItem is not available
L 08/13/2016 - 18:23:07: [CSTRIKE] AddAccount is not available
L 08/13/2016 - 18:23:07: [CSTRIKE] CanPlayerBuy is not available
L 08/13/2016 - 18:23:07: [CSTRIKE] CanBuyThis is not available
L 08/13/2016 - 18:23:07: [CSTRIKE] Some functions are not available - forwards CS_OnBuy[Attempt] have been disabled
L 08/13/2016 - 18:23:07: [CSTRIKE] GiveDefaultItems is not available - native cs_set_no_knives has been disabled
L 08/13/2016 - 18:23:07: [CSTRIKE] CREATE_NAMED_ENITTY is not available - native cs_create_entity() has been disabled
L 08/13/2016 - 18:23:07: [CSTRIKE] UTIL_FindEntByString is not available - native cs_find_ent_by_class() has been disabled
L 08/13/2016 - 18:23:07: [CSTRIKE] GetWeaponInfo is not available - native cs_get_weapon_info() and forward CS_OnBuy have been disabled
L 08/13/2016 - 18:23:07: [CSTRIKE] g_pGameRules is not available - Forward CS_OnBuy has been disabled
L 08/13/2016 - 18:23:07: [FAKEMETA] get/set_gamerules_* natives have been disabled because g_pGameRules address could not be found.

**Comment by Arkshine** [comment]
This has nothing to do with reHLDS, Skumek.

**Comment by Skumek** [comment]
Well, he made a thing named "re-amxmodx". and i could not find anywhere to post so he would be notified about it.

Can you do something about this problem though?
