### ISSUE TITLE
Bug with trains

### ISSUE THREAD

**Issue by spark512** [dreamstalker/rehlds#238]
I read somewhere that trains are bugged on cs 1.6 because they dont follow the new round event. If a train gets activated and the round ends before it reaches the destination, when a new round starts, the train is not properly reset, it's position is set back to start, but it is still active and going towards the destination. Can anything be done to fix this and make trains properly reset on new round?

Is this an issue for ReHLDS or should i ask in ReGameDLL_CS?

**Comment by s1lentq** [comment]
It is to ReGameDLL_CS, you have a map to reproduce the issue?

**Comment by spark512** [comment]
yes, usually zombie escape maps. I can send you one where i know the problem happens, for you to test.

**Comment by spark512** [comment]
Posted in ReGameDLL_CS issue #55 - https://github.com/s1lentq/ReGameDLL_CS/issues/55

**Comment by spark512** [comment]
Under work at ReGameDLL_CS. Issue can be closed here.
