### ISSUE TITLE
ReHLDS and AMXX Files Check

### ISSUE THREAD

**Issue by spark512** [dreamstalker/rehlds#239]
Hello,

I'm having a problem with file consistency checks. I'm using the AMXX plugin Files Check (https://forums.alliedmods.net/showthread.php?p=595209) to enforce model consistency, the plugin works fine with the pure version of ReHLDS, but it's misbehaving on the bugfixed version. It's giving an inconsistency error on all listed models, even tho they are the correct ones.

Is there a plugin that forces file consistency like the AMXX Files Check which is compatible with the bugfixed version of ReHLDS?

**Comment by Mistrick** [comment]
For filecheck use [this](http://www.dedicated-server.ru/vbb/showthread.php?t=26550) but only russian description.

**Comment by spark512** [comment]
> For filecheck use this but only russian description.

I am already using ReChecker, but for checking hack files. The AMXX Files Check checks the model's size (mins, maxs) to make sure the client model is an exact match to the server model. ReChecker doesnt do that, ReChecker checks the file's name and hash.

**Comment by spark512** [comment]
The issue is fixed, tested and working on windows. Thank you @WPMGPRoSToTeMa and @theAsmodai .
