### ISSUE TITLE
Do we need .res files now?

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [dreamstalker/rehlds#244]
With these commits:
4cd651d8659add3cd74e00dfcca40b6eccff558a
e2cc869086cb19c6d127b0a59a863f1e1a4fcdfc
9080b9b7e82fd4bdb84b9f965f940728144b1925
a300a4c84dd23b5e1868f91b70ce136d703e2894
81d5369e97fda1f0a5b626a1b92c9c902dccb9be

**Comment by LevShisterov** [comment]
No sense in removing a feature if it is not in the way.
