### ISSUE TITLE
Message spamming in console

### ISSUE THREAD

**Issue by Sylvert0** [dreamstalker/rehlds#247]
I have this spamming all over the console:

> Malformed packet number (7/8)
> Malformed packet number (7/8)
> Malformed packet number (7/8)
> Malformed packet number (7/8)
> Malformed packet number (7/8)
> Malformed packet number (7/8)

What could be the reason?

**Comment by Adidasman1** [comment]
Flood packets. Server on Linux? iptables has access to?

**Comment by Sylvert0** [comment]
Linux: CentOS release 6.8 (Final)

Yes, i have access to the firewall

**Comment by WPMGPRoSToTeMa** [comment]
I think we should move all messages of this sort to debugged printf (`Con_DPrintf`) or make cvar for this logging.

**Comment by Adidasman1** [comment]
# add rules iptables
# 27015 game port server

iptables -A INPUT -p udp -m udp --dport 27015 -m state --state ESTABLISHED -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 27015 -m state --state NEW -m length --length 33:250 -j ACCEPT
iptables -A INPUT -p udp -m udp --dport 27015 -j DROP

**Comment by theAsmodai** [comment]
Why only up to 250?

**Comment by Adidasman1** [comment]
Because the "new" requests valid to such threshold

**Comment by theAsmodai** [comment]
Really? It's a dump of valid client connection:
http://oi65.tinypic.com/flvmnl.jpg

**Comment by Adidasman1** [comment]
В данном скрине, соединение попадет на 1 правило, так как у него состояние "ESTABLISHED", потому что до этого был пакет "NEW" длинной в "51" с содержанием "get challenge steam" после и поменялось состояние соединения на "ESTABLISHED".

Вообще для клиента тут валидное значение длинны для пакетов "new" 51 (getchallenge steam
) и 53 (TSource Engine Query), но в этом правиле надо еще не забыть про мониторинги и запросы A2S, такие как "A2S_PLAYER" и "A2S_RULES" длинной в "37", поэтому данное правило не превышает длину в "150", почему указал 250, чтобы был запас на корявые скрипты хотя это их проблемы (изначально стояла у меня длина до 60, потом некоторые скрипты не могли получить инфу, и пришлось завышать до 150).

P.s пересмотрел логи, правило которое дропает пакет "NEW" длинной выше "150" за 2 года ни разу не сработало.

**Comment by mo0nsniper** [comment]
Great, thanks.
I really needed that rule to protect from a flood attack.
