### ISSUE TITLE
Cvar Utilities Compatiblity ?

### ISSUE THREAD

**Issue by NewZMLife** [dreamstalker/rehlds#250]
hi,
there is problem with Cvar Utilities using ReHLDS, if i start server while running Cvar Utilities by arkshine, server crashes.
can someone rewrite this plugin or at least compatible it with ReHLDS ?

https://forums.alliedmods.net/showthread.php?t=154642

**Comment by Arkshine** [comment]
I suggest you don't this module, it contains probably a lot of shit code. This would need to be rewritten.
But well, most of features are available in AMXX 1.8.3-dev. 
Maybe you should take a look at ReAMXX as well.

**Comment by NewZMLife** [comment]
AMX MOD X 1.8.3 has some bugs i think , thats right ? cuz it stills in Dev version not stable.

**Comment by IgnacioFDM** [comment]
I don't think it has any known regressions. It has a lot of important fixes.

**Comment by In-line** [comment]
Closing as non active
