### ISSUE TITLE
Reunion Bug Report

### ISSUE THREAD

**Issue by NewZMLife** [dreamstalker/rehlds#252]
Hello,
as you know, in Dproto 0.9.548, if you set these for AUTHID settings, the steam will be generated from SXE HardwareID:

```
# For Legit Steam clients (default is real STEAM_xx:xx:xx [1])
cid_Steam = 1

# For SXEI Clients
# default is real STEAM_xx:xx:xx [1]
cid_SXEI = 1

# EnableSXEIdGeneration (0 / 1)
# Turns on steamid generation based on info sent by sXeI client
# Enable this ONLY if you have sXeI server installed!
EnableSXEIdGeneration = 1
```

but in Reunion, the steam will generate from STEAM Account (cid_Steam)
can someone make a action to fix it?
also there are some other bugs in reunion i will report them again here, if applied

@theAsmodai 
@s1lentq

**Comment by s1lentq** [comment]
@NewZMLife 
you need to ask your questions in a support topics of these mods, but not there.

**Comment by NewZMLife** [comment]
@s1lentq 
can you give me the link of support topic ?
its not a question its only a bug report...
i hope you take a action to fix it ... you are the author of Reunion

**Comment by LevShisterov** [comment]
Use google please.
