### ISSUE TITLE
Server Crash: NET_GetLong: Duplicated Packet

### ISSUE THREAD

**Issue by Hembi** [dreamstalker/rehlds#259]
Hello,

I running so much CS 1.6 server with ReHLDS. Some server crashed and in screenlog stay:
NET_GetLong:  Ignoring duplicated split packet 1 of 2 ( 3 bytes )

**Comment by mforce95** [comment]
Is it in connection with #271?

**Comment by mforce95** [comment]
Is it in connection with #241

**Comment by mforce95** [comment]
Is it in connection with #247 ?

**Comment by abhishekdeshkar** [comment]
Same here. Sometimes player's game crashes and sometimes ReHLDS. I have latested compiled one.

**Comment by Hembi** [comment]
Any solution?

**Comment by WPMGPRoSToTeMa** [comment]
@Hembi these messages are already fixed. Are sure that you are running the latest version of ReHLDS? Show me `version` command output.

**Comment by Hembi** [comment]
@WPMGPRoSToTeMa In which version did you fix it?
Okay I said wrong with all, because I didn't have time to install the latest version now.
However when I asked my question on Oct 30 we had the latest of ReHLDS, I don't know whitch version was it, and yes the bugfixed.

**Comment by Hembi** [comment]
We have a server hosting here in my country and we give the ability to the users to choose theirs HLDS engine( like ReHLDS, but without autoupdate yet ). Some user wrote messages about this problem in October and they servers were on the latest version of the ReHLDS, I checked it and this is the reason why I asked here my question.

**Comment by WPMGPRoSToTeMa** [comment]
@Hembi hmmm this was fixed 19 Oct https://github.com/dreamstalker/rehlds/commit/e2be6491ba9c2616a23ab9cefd4a201b5db8221e. Better to check `version` output.

**Comment by Hembi** [comment]
@WPMGPRoSToTeMa Hmm. Okay, thank you for the information.
Now we are on:
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 19:18:26 Nov  1 2016 (934)
ReHLDS API version 2.13
We update to the latest version all servers at this weekend and if the users write me any problem I post it here. Thank you for your time. Have a nice day!
