### ISSUE TITLE
reconnect ddos

### ISSUE THREAD

**Issue by xlenonz** [dreamstalker/rehlds#260]
server
rehlds-0.2-20161019.192431-177
reunion_0.1.73
reauthcheck_0.1.4
amxx 1.8.2

still they can attack with fakeplayers like this

tons of reconnect packets.

i used to ban with these orpheu amxx plugin ( antiflood kanagava )
but since orpheu not work rehlds i cant do anthing

88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect
88.x.x.x:49330:reconnect
88.x.x.x:49331:reconnect
88.x.x.x:49332:reconnect
88.x.x.x:49333:reconnect
88.x.x.x:49334:reconnect
88.x.x.x:49335:reconnect

**Comment by abhishekdeshkar** [comment]
same. +1 for this.

**Comment by shelru** [comment]
plugin by kanagava can't help u also on HLDS

**Comment by ish12321** [comment]
If not that
Any thing by someone here to block ddos

**Comment by In-line** [comment]
http://www.dedicated-server.ru/vbb/showthread.php?t=26787
