### ISSUE TITLE
[Bug Report] issue with setting cs_set_user_model

### ISSUE THREAD

**Issue by indraraj26** [dreamstalker/rehlds#263]
It does not change the model.

Tested in windows/linux
version 
Protocol version 48
Exe version 1.1.2.7 (cstrike)
Exe build: 18:25:31 Nov  1 2016 (934)
ReHLDS API version 2.13 

you can test with my code : 
`#include <amxmodx>
#include <cstrike>

public plugin_init()
{
register_clcmd("say /model","set_model");
}

public set_model(id)
{
cs_set_user_model(id,"guerilla");
client_print(id,print_chat,"Your model is set to ts(guerilla)");
log_amx("Your model is set to ts(guerilla)");
}
`

**Comment by NewZMLife** [comment]
use ReAMXMODX

**Comment by indraraj26** [comment]
NewZMLife already using, this issue is from rehlds API as re-amxmodx haven't update anything in cstrike module as far as I know 
cs_set_user_model is common native btw have you tried my code ?

**Comment by OsweRRR** [comment]
forgot precache_model..

**Comment by indraraj26** [comment]
@OsweRRR You don't need to precache default model it was Reamxmodx fault
I have update the Amxmodx now its working
