### ISSUE TITLE
Not visible in HLSW if started with -nomaster

### ISSUE THREAD

**Issue by LevShisterov** [dreamstalker/rehlds#270]
Didn't checked what A2S stops to work, probably all that rely on steam.
Please confirm if that happen to anyone else.

**Comment by theAsmodai** [comment]
I don't see this problem in HLSW v1.4.0.5

**Comment by LevShisterov** [comment]
I use 1.4.0,2, but I don't think that this is HLSW problem.
Tried several times with original swds.dll and ReHLDS one before posting. But now it happens with original dll too, so not ReHLDS issue.
