### ISSUE TITLE
512MB Precache limit?

### ISSUE THREAD

**Issue by TatuEugen** [dreamstalker/rehlds#271]
Hello, i have big problems with this error... is there any way, any fix, anything? Please help!!!
 ...

**Comment by LevShisterov** [comment]
MB? More details please.

**Comment by TatuEugen** [comment]
I get error when i have more resources than 512 MegaBites in server... and server crash....
I search for a fix long time... nothing found... no one can fix it...

Is impossible ? ....

**Comment by LevShisterov** [comment]
If server crash for some reason, sure we can try to fix it.
But supply us with error info and crash dumps.

**Comment by lespaul64** [comment]
He meant 512 precache count, this has been discussed many times, we need reClient_CS.

**Comment by faKee91** [comment]
You can try this https://github.com/In-line/metamod_unprecacher, but I don't know if it is compatible with rehlds.

**Comment by In-line** [comment]
Yes, it is compatible with ReHLDS.
