### ISSUE TITLE
Modules are not working.

### ISSUE THREAD

**Issue by abhishekdeshkar** [dreamstalker/rehlds#275]
Hello,

After installing the latest swds.dll. Metamod modules stopped working.

```
[REUNION]: REHLDS Api major version mismatch; expected 2, real 3
[REUNION]: Failed to locate REHLDS API
[REAUTHCHECK] Version: 0.1.4 Linux 'Counter-Strike 1.6'
[REAUTHCHECK] REHLDS Api major version mismatch; expected 2, real 3.
[REVOICE]: REHLDS Api major version mismatch; expected 2, real 3
[REVOICE]: Failed to locate REHLDS API
[ReSemiclip] REHLDS Api major version mismatch; expected 2, real 3.

[ReSemiclip]: ReHLDS error load.
[WHB] Warning: REHLDS Api major version mismatch; expected 2, real 3
[SRD] Warning: REHLDS Api major version mismatch; expected 2, real 3
[AMXX]: ReHLDS Api major version mismatch; expected 2, real 3
```

**Comment by simeonniko** [comment]
The same...
[HACKD] ReHLDS engine with less than required API version (needed 2:10, got 3:0)!
[ReAimDetector] REHLDS Api major version mismatch; expected 2, real 3.
[ReAimDetector] Failed to locate retrieve rehlds api interface from engine module, return code is 1.

**Comment by s1lentq** [comment]
just wait for the release the update modules or go back to a compatible build. (before 4 Nov)

**Comment by shelru** [comment]
Поговорим об индус*8ком коде.

**Comment by ish12321** [comment]
Check again... Updated

**Comment by In-line** [comment]
Closing as non active
