### ISSUE TITLE
ReHLDS API 3.x ??

### ISSUE THREAD

**Issue by NewZMLife** [dreamstalker/rehlds#277]
where can i download ReHLDS API 3.x ??

mine is 2.14

**Comment by theAsmodai** [comment]
http://nexus.rehlds.org/nexus/content/repositories/rehlds-dev/rehlds/rehlds/

**Comment by NewZMLife** [comment]
@theAsmodai 

ok, but there is a problem: akk metamod plugins like reunion, re amx mod x, reauthchecker, rechecker, ... will fail on server start ...

**Comment by LevShisterov** [comment]
This is by design. Major version should match on engine and modules. You can move to 3.x when you will have all modules for 3.x API version.
