### ISSUE TITLE
Problem with "Pure" version

### ISSUE THREAD

**Issue by axent93** [dreamstalker/rehlds#278]
Hello,

I had used HLDS Build (6153) for long time and i wanted to try ReHlds "pure" (Just to emphasize that i don't need bugfixed). 

Everything went ok, server was running great until i discovered a "bug"... Players were kicked from the server with this output.

Error: server failed to transmit file 'AY & SY Yr?'
Last 32 messages parsed.
17813 0008 svc_time
17813 0013 svc_clientdata
17813 0033 svc_deltapacketentities
17814 0018 svc_time
17814 0023 svc_clientdata
17814 0043 svc_deltapacketentities
17814 0062 ShowTimer
17814 0063 RoundTime
17814 0066 Scenario
17814 0008 svc_time
17814 0013 svc_clientdata
17814 0033 svc_deltapacketentities
17814 0000 svc_updateuserinfo
17814 0252 svc_print
17814 0282 ScoreAttrib
17814 0285 TextMsg
17814 0327 ScoreInfo
17814 0337 TeamInfo
17814 0351 Location
17814 0355 svc_updateuserinfo
17814 0378 svc_updateuserinfo
17814 0630 svc_updateuserinfo
17814 0882 svc_updateuserinfo
17814 1134 svc_updateuserinfo
17814 1386 svc_updateuserinfo
17814 1638 svc_updateuserinfo
17814 1890 svc_updateuserinfo
17814 2142 svc_updateuserinfo
17814 2394 CurWeapon
17814 2398 CurWeapon
17814 2402 svc_filetxferfailed
BAD: 2413: svc_bad
Host_Error: CL_ParseServerMessage:

I don't have this problem on HLDS build 6153 with exact the same plugins and server configuration.. 

Can you update pure version and try to fix this. I had search for this kind of bug and i find this guy that explained more detailed. I think this was a early bug on HLDS so it maybe can use to you: https://forums.alliedmods.net/showthread.php?t=67028?t=67028

Appreciate for help!

**Comment by LevShisterov** [comment]
Hi!
Its a bit funny to remove fixed version, install a version with the bug that is fixed in bugfixed and then ask to fix it again.
https://github.com/dreamstalker/rehlds/issues/38

**Comment by axent93** [comment]
Yeah it sounds funny to you. But this version works fine except this bug, with bugfixed version i have another problems.

If they publishing both versions i think i have right to report bug for both of them, doesn't matter if is pure or bugfixed.

**Comment by LevShisterov** [comment]
Pure version designed to behave exactly as original HLDS. So don't expect it will have any bugfixes.

**Comment by axent93** [comment]
If is designed to work exactly why do i have this problem on pure but not on HLDS original.. 

I don't wanna be rude, am just looking for a solution... 

When i use bugfixed i have problem with ping, first few minutes everythnig is ok, then ping start to inc 100+ to all players... With pure and original ping is ok..

**Comment by LevShisterov** [comment]
Because it is an infrequent case bug. It might happen on all HLDS builds. There are a lot of proofs out there, [for example](https://forums.alliedmods.net/showthread.php?t=95179).

To get help with bugfixed version problems, please create an issue with all info you have.

**Comment by axent93** [comment]
Ok, ty for replay. I'll open new topic about it.
