### ISSUE TITLE
mp_tkpunish

### ISSUE THREAD

**Issue by strazdinsivars** [dreamstalker/rehlds#281]
mk_tkpunish 1 doesn't work client gets this
```
Server tried to send invalid command:"kill
"
```

**Comment by s1lentq** [comment]
this refers to the gamedll and it was fixed.
[nofix](https://github.com/s1lentq/ReGameDLL_CS/blob/7238f21/regamedll/dlls/player.cpp#L3698-L3701) -> [fix](https://github.com/s1lentq/ReGameDLL_CS/blob/7238f21/regamedll/dlls/player.cpp#L3722-L3727)
