### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#283]
Is the rechecker working for the latest reHLDS and reGAMEDLL_CS
If so, also provide me link the latest version of it :)

**Comment by Adidasman1** [comment]
http://www.dedicated-server.ru/vbb/showthread.php?t=26550

**Comment by spark512** [comment]
@Adidasman1 sorry to jump in here, when can we expect ReAuthCheck to be compatible with the newest ReHLDS and ReGameDLL? It's the only thing keeping me from upgrading...

**Comment by Adidasman1** [comment]
In the near future

**Comment by spark512** [comment]
@Adidasman1 Can i also suggest a small change?
I think it would be better if we had output logs as yyyy.mm.dd instead of mm.dd.yyyy format.

Oh and could you implement REU_IsRevemuWithoutAdminRights() in your check for duplicate steam ids? Maybe make it show it's value in the logs?

**Comment by ish12321** [comment]
Adidasman I'm unable to create account on link you said
I don't know that language

Please any alternative site

**Comment by Adidasman1** [comment]
try to register it, because it is the official topic

**Comment by ish12321** [comment]
Ihad really tried but failed in security questions
