### ISSUE TITLE
NOXREF functions have XREF's

### ISSUE THREAD

**Issue by Chuvi-w** [dreamstalker/rehlds#292]
For example, `NOXREF void Sys_CheckOSVersion(void)` is called from `void __cdecl Sys_InitHardwareTimer()`
Does it OK?

**Comment by LevShisterov** [comment]
No.
All NOXREF functions should have
`	NOXREFCHECK;`
at start to prevent such situations.

**Comment by Chuvi-w** [comment]
Em... 
![image](https://cloud.githubusercontent.com/assets/3652659/21519527/e8be5fa4-ccfe-11e6-9e16-6701e051a072.png)

**Comment by LevShisterov** [comment]
That is why this function shouldn't be NOXREF.

**Comment by Chuvi-w** [comment]
Fixed?
https://github.com/dreamstalker/rehlds/commit/b9c8be8aec22fdf4afdb7899ef683c32c5a0e6e8
