### ISSUE TITLE
Accuracy fix.

### ISSUE THREAD

**Issue by abhishekdeshkar** [dreamstalker/rehlds#296]
Hello,

I have been using accuracy plugin. Do I still need to use accuracy plugin after updates ? Please do let me know. :)

Thanks!

**Comment by Adidasman1** [comment]
regamedll it refers to and it is not required where

**Comment by WPMGPRoSToTeMa** [comment]
ReGameDLL has no changes about accuracy.

**Comment by Adidasman1** [comment]
What plugin do you use? this is not the case https://forums.alliedmods.net/showthread.php?p=1549133?
