### ISSUE TITLE
AMXX Profiler in ReHLDS engine ?

### ISSUE THREAD

**Issue by iNexus3** [dreamstalker/rehlds#299]
Is it a good idea to import anything like amxx profiler in rehlds? 
Or log system which detect bad coded plugins, spike cpu, eat ram,  overflow, etc.

**Comment by theAsmodai** [comment]
No, because all thing related to plugins should be integrated in amxmodx.

**Comment by iNexus3** [comment]
Nothing to do about the problem ?

**Comment by In-line** [comment]
Closing as non active

**Comment by In-line** [comment]
@iNexus3 No. It is like adding scope to a bullet.
