### ISSUE TITLE
Change recommended ICC version

### ISSUE THREAD

**Issue by NuTTeR** [dreamstalker/rehlds#302]
There are some incompatibilities between ICC < 16.0.2 and modern distros, like Ubuntu 16.04 (maybe others), that resulting in compilation fail. 
It takes some time before I [found](https://software.intel.com/en-us/forums/intel-c-compiler/topic/565143) problem.
Maybe we can change recommend ICC version to 16.0.2 in readme.md, so other users can compile without a problem?

**Comment by theAsmodai** [comment]
Latest version is recommended.

**Comment by In-line** [comment]
Closing as non active
