### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#308]
Please can someone make ctf/capture the flag mod for rehlds please

**Comment by In-line** [comment]
99% of ordinary mods created for HLDS will work, also for ReHLDS.

**Comment by ish12321** [comment]
it uses orpheu so won't work
so please someone 
make it work with reHLDS

**Comment by lespaul64** [comment]
It use orpheu just to block round end and uncap mp_roundtime limit. ReGameDLL already both of it. So all you need is use the ReGameDLL and remove all code related to orpheu in ctf amxx plugin.

**Comment by ish12321** [comment]
I'll try if i can do it by I'm not good at scripting so if possible could anyone do it for me and give me

**Comment by ish12321** [comment]
PLEASE @lespaul64 could you help me in cTf  ?

Please do in this CTf out of the loads of cTF available on net
https://forums.alliedmods.net/showthread.php?t=132115

**Comment by IgnacioFDM** [comment]
Stop asking for plugins on github. I really doubt anyone here will code one for you.
