### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by raiz0x** [dreamstalker/rehlds#310]
Precache limit is fixed?
I can modify this limit?
What is the difference between rehlds & regame?
reHlds pure or bugfix?

**Comment by Phantom-J** [comment]
1. Precache limit was just extended
2. Yep
3. ReGameDLL does all functions which applies only to Cunter-Strike: weapon logic, entity conduct, Terrorists and Counter-Terrorirsts interaction, endround conditions. All the rest does ReHLDS
4. Bugfix

**Comment by Mistrick** [comment]
Change precache limit on server useless without client.

**Comment by raiz0x** [comment]
I got it. Thank you(phantom,mistrick) for the reply.
@Mistrick , the customer has no limit(than the GB from Pc), download any is sent by the server.
Can you to modify limit & compile for me?...

**Comment by Mistrick** [comment]
@raiz0x Client has same limits. It can't get more than 512 files in precache.
If you change limit on server, you need client which can understand that limit.

**Comment by raiz0x** [comment]
Ok. Thanks!

**Comment by In-line** [comment]
[https://github.com/In-line/metamod_unprecacher](url)

**Comment by Phantom-J** [comment]
@In-line, 404

**Comment by In-line** [comment]
@Phantom-J  fixed.

**Comment by raiz0x** [comment]
@In-line , must to be modified manually, and i can't see all files what need to be fixed..Or can work alone? Can precache alone(without .ini modifications) files with problem?

**Comment by In-line** [comment]
@raiz0x click on link, read text on page.

**Comment by raiz0x** [comment]
@In-line are u Jesus?? Woow, i did not know that we have to do something :O . What i saied 'can you make binary(.so) for me?' Because i don't want to INSTALL programs.
It would have been better and for you to leave a link where to be binaries
You didn't answered to my questions.

**Comment by In-line** [comment]
@raiz0x https://github.com/In-line/metamod_unprecacher/releases . Funny.

**Comment by raiz0x** [comment]
I'm funny :P . Thanks!

'@In-line , must to be modified manually, and i can't see all files what need to be fixed..Or can work alone? Can precache alone(without .ini modifications) files with problem?'
