### ISSUE TITLE
a problem with windows xp, hlds.exe unable to load engine image is corrupted

### ISSUE THREAD

**Issue by RealHumanWithHair** [dreamstalker/rehlds#323]
Hi all, I have this problem. http://www.dedicated-server.ru/vbb/showpost.php?p=298400&postcount=1150

From 1 week i searching trying some stuff but can't fix this error.

Someone running server on xp, have same problem?

**Comment by LevShisterov** [comment]
Find highest version that works and tell the number
[http://nexus.rehlds.org/nexus/content/repositories/rehlds-dev/rehlds/rehlds/](http://nexus.rehlds.org/nexus/content/repositories/rehlds-dev/rehlds/rehlds/)

**Comment by RealHumanWithHair** [comment]
No one and  rehlds_0.2_20160909.200340_173.zip same error.

Maybe need preinstall OS but is fresh install.

**Comment by WPMGPRoSToTeMa** [comment]
XP SP3?

**Comment by RealHumanWithHair** [comment]
Yes

**Comment by LevShisterov** [comment]
Full console dump please (start with `+log on`).

**Comment by RealHumanWithHair** [comment]
can't start hlds.exe

**Comment by LevShisterov** [comment]
`hlds.exe -console +log on`?
If not console copy, do a screenshot, please.

**Comment by RealHumanWithHair** [comment]
![vewa](https://cloud.githubusercontent.com/assets/25377012/22405090/a33f67d8-e645-11e6-983f-962be5c7871e.jpg)

I'm sorry for late answer, 2 days no access to PC.

**Comment by LevShisterov** [comment]
Try to check that file is correctly extracted from archive. [Calculate MD5](http://onlinemd5.com/). It should be 05A4EFF035D7EF4F16A289DE49963BDA for 3.0.0.411.

**Comment by RealHumanWithHair** [comment]
6F7217ECB5E191961EC2F1E55DE06929 hlds.exe right?

**Comment by LevShisterov** [comment]
No, ofc, swds.dll.

**Comment by RealHumanWithHair** [comment]
F8B2E895C528A710D162332D2DBAECC8

but I trying with different swds files and give same error.

**Comment by LevShisterov** [comment]
Please try with recent version: [3.0.0.411](http://teamcity.rehlds.org/repository/download/Rehlds_Publish/5420:id/rehlds-dist-3.0.0.411-dev.zip)
Use swds.dll from bugfixed folder (for starting server and MD5 check).

**Comment by RealHumanWithHair** [comment]
nope, same error.

**Comment by LevShisterov** [comment]
Your MD5 is different. Which means that you use different or damaged binary.

**Comment by RealHumanWithHair** [comment]
i trying donwload new server from steamcmd for so buggy. non stop need spaming app_update 90 validate to download.

**Comment by RealHumanWithHair** [comment]
05a4eff035d7ef4f16a289de49963bda 3.0.0.411. like your. (this is only bonus information).

**Comment by LevShisterov** [comment]
Just to remove some doubts, try [these binaries](http://teamcity.rehlds.org/repository/download/Rehlds_Publish/5474:id/rehlds-dist-3.0.0.417-dev.zip) from the [pull request](https://github.com/dreamstalker/rehlds/pull/331#partial-pull-merging).

**Comment by RealHumanWithHair** [comment]
still no

**Comment by RealHumanWithHair** [comment]
Now I think maybe is virus, when I have direct access to PC will share what happen after scaning or preinstall OC.

**Comment by RealHumanWithHair** [comment]
Before 1 hour I finish with preinstall Windows XP sp3.  Still can't start hlds.exe same error. But I try to install and AVG but won't to install. 

Something else I wanna start hasher.exe (easy program to check md5 
![untitled](https://cloud.githubusercontent.com/assets/25377012/22598746/39c594ca-ea3d-11e6-98ec-638192a36e6f.jpg)
has) but cannot. ReHLDS not support WinXP or just this release of WinXP missing something.

**Comment by LevShisterov** [comment]
Download CPU-Z and show us info from it. Probably you are running on old CPU that doesn't support required instruction set.

**Comment by RealHumanWithHair** [comment]
Exactly that I thinking yesterday about, but i think this is not possible. But maybe exactly this is the problem. I forget to share this with you.

w8 5 minutes to connect with PC.

**Comment by RealHumanWithHair** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25377012/22622410/ca853470-eb41-11e6-9cd2-1675beb1610f.jpg)

**Comment by LevShisterov** [comment]
Now the people will came and say that you have to have at least SSE2. I am not sure what sets we are currently using. Probably we have to mention that in readme.
All you can do about this is to install visual studio and compile without these.

**Comment by RealHumanWithHair** [comment]
Thanks again mate, I will try with Visual Studio if won't run I will change this CPU with another AMD Sempron +2600 I check right now and see is support SSE2.

**Comment by theAsmodai** [comment]
On Duron you can run original HLDS build 4883 or older. After 5xxx+ builds HLDS is using SSE2.
Rehlds is using SSE3 (Athlon 64, Pentium D, or higher).

**Comment by LevShisterov** [comment]
If so original 6xxx build should fail with the same reason.

**Comment by RealHumanWithHair** [comment]
Full fail with Sempron, problem with boot hard disk however this is not important. 

I take a whole new pc(old), was in the corner.
![untitled](https://cloud.githubusercontent.com/assets/25377012/22659914/36105550-eca8-11e6-9028-f5d0bf5309bc.jpg)

ReHLDS running only have a problem with Reamxmodx and WHBlocker(use sse4.1) but it is not for here. 

In Wednesday will reinstall Duron with another release of WinXP just wanna see if will give different error or same.

Thank you very much for your time to spend on my problem I really appreciate that.

Will share in Wednesday  what happen.

Thank you again!

**Comment by theAsmodai** [comment]
WHBlocker is using SSE4.1 only if it's supported by hardware.

**Comment by RealHumanWithHair** [comment]
This is nice information. Thank you.

**Comment by RealHumanWithHair** [comment]
Only for information:
I make this preinstall on Windows XP on old CPU from main topic and hlds is starting. Just for information. 
How ever.

something else:
Windows XP is not support new rehlds hlds.exe but we already 2017 so thig is not big deal.

Thank you again for your time!
