### ISSUE TITLE
ReLocalizeBugFix or SaveNameandChat

### ISSUE THREAD

**Issue by Hembi** [dreamstalker/rehlds#328]
Dear Developers,

Is it important to install one of the two plugin?
Is the problem fixed in ReHLDS what this plugins fix?

Version command:
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.0.0.409-dev
Build date: 00:09:03 Jan 27 2017 (1021)
Build from: https://github.com/dreamstalker/rehlds/commit/8513a0e

Current meta list:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2    ini   Start ANY  
 [ 2] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
 [ 3] ReAuthCheck      RUN   -    reauthcheck_mm_i  v0.1.5    ini   Start Never
 [ 4] Revoice          RUN   -    revoice_mm_i386.  v0.1.26   ini   Start Never
 [ 5] Rechecker        RUN   -    rechecker_mm_i38  v2.3      ini   Chlvl ANY  
 [ 6] SafeNameAndChat  RUN   -    SafeNameAndChat.  v1.0      ini   ANY   ANY  
 [ 7] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl1   ANY   ANY  
 [ 8] CStrike          RUN   -    cstrike_amxx_i38  v1.8.2-d  pl1   ANY   ANY  
 [ 9] CSX              RUN   -    csx_amxx_i386.so  v1.8.2    pl1   ANY   ANY

**Comment by faKee91** [comment]
ReLocalizeBugFix will not work on dev version, so use SaveNameandChat. But you can try ReAMXModX build 7 in which was fixed bug with localized strings in chat.

**Comment by Hembi** [comment]
Thank you for ypur answer.
Yes, I noticed that it doesn't work. I installed the SaveNameandChat instead, but it is older then the another plugin. It really fix the problem? ReLocalizeBugFix didn't know more than the other one?
The core of ReAmxModX is 1.8.3 and some older plugin doesn't work the same on the new version.

**Comment by simeonniko** [comment]
In ReHLDS are fixed the bugs in name https://github.com/dreamstalker/rehlds/commit/40b3a5e646b5c502b8b7f36902998da60cd1bc0b

**Comment by Hembi** [comment]
It is an important info, thank you simeonniko. What is about the chat?

**Comment by faKee91** [comment]
ReLocalizeBugFix and SaveNameandChat fixes bug in chat. If you have rehlds dev version and AMXModX 1.8.2 you must use SaveNameandChat.

**Comment by spark512** [comment]
ReLocalizeBugFix and SaveNameandChat do the same thing, they both fix the bug in chat and in name. The difference is that ReLocalizeBugFix is dependent on ReHLDS, while SafeNameandChat works in both HLDS and ReHLDS. ReLocalizeBugFix is curently outdated and doesn't work on ReHLDS 3.0, so you have to use SafeNameandChat..

Another difference is that ReLocalizeBugFix removes certain characters completely, while SafeNameandChat only replaces them with safe ones, so you will be able to see the %, # and others in name and chat, without them causing the bug.

Also, the bug is fixed in ReHLDS directly, but since you are using amxmodx plugins which have this bug in them, you have to run one of these metamod plugins to prevent a badly coded amxx plugin from allowing the bug to be used..

**Comment by Hembi** [comment]
@faKee91 @spark512 Thank you for the informations. :)

**Comment by Raiz3n1312** [comment]
Egyik sem javasolt Hembi.. Ehelyett van egy Lite_Chat nevű kis plugin. Pár sor az egész. Ez az optimalizált verizója az ichat-nek. Hlmodon utána tudsz nézni. Mforce rakta ki a plugint neugomon írta.

**Comment by Hembi** [comment]
A Lite Chat gondolom csak a chatben okozott problémát javítja. Nem csak ott jelentenek gondot ezek a szövegek.
Például, ha bekerül egy HUD üzenetet kiíró plugin, akkor én úgy tudom ott ugyanúgy gondot jelentenek ezek a kódok egy játékos nevében.

**Comment by In-line** [comment]
@Hembi English only.

**Comment by Hembi** [comment]
@In-line Yes, I know. Sorry for it!

**Comment by Raiz3n1312** [comment]
The rehlds devs was fixed this charaters. Try 1.8.3 reamxmodx and not need + modules for server. :dancing_women:

**Comment by In-line** [comment]
Closing as non active.
