### ISSUE TITLE
[Noob question #2] What is meaning of NOXREF/NOXREF_CHECK?

### ISSUE THREAD

**Issue by In-line** [dreamstalker/rehlds#330]
NOXREF_CHECK crashes server with Sys_Error.
NOXREF is just define to indicate that function is not called at all.
As I googled and understood that type of functions has no use and will be removed at compile time.
So there is no point to work on that kind of functions. 
Am I right?

**Comment by WPMGPRoSToTeMa** [comment]
They can be useful for exporting in API or for future enhancements.

**Comment by In-line** [comment]
@WPMGPRoSToTeMa thx.
