### ISSUE TITLE
Roundend on hostage rescued

### ISSUE THREAD

**Issue by uGamers** [dreamstalker/rehlds#335]
The round don't end when all hostage are rescued

No errors 

Will end on roundend but not on event hostage rescued. 

Any help?

**Comment by Phantomsq** [comment]
Was you playing on empty server at this moment?

**Comment by uGamers** [comment]
what is it then?

**Comment by In-line** [comment]
@uGamers probably https://github.com/s1lentq/ReGameDLL_CS

**Comment by LevShisterov** [comment]
@uGamers does the same happen if you change engine to original HLDS?

**Comment by uGamers** [comment]
@LevShisterov  

No works fine

**Comment by spark512** [comment]
@LevShisterov I think this is a bug from an older regamedll version, s1lent fixed it a few updates ago...

**Comment by In-line** [comment]
Closing as non active
