### ISSUE TITLE
gcc compiler branch compiler fixes

### ISSUE THREAD

**Issue by ghost** [dreamstalker/rehlds#340]
using gcc 6.3.0-5 on debian stretch

add  #include < vector >to rehlds/rehlds/rehlds/rehlds_api_impl.cpp
add #include < cmath > to dep/cppunitlite/src/Assertions.cpp

change 'if (abs(expected - actual) > epsilon)' to  'if (std::abs(expected - actual) > epsilon)' in dep/cppunitlite/src/Assertions.cpp

Or using a gcc5.4.1 32bit OS: on debian stretch it compiles without modification

**Comment by LevShisterov** [comment]
Can you copy compilation errors here?
Thanks.

**Comment by In-line** [comment]
Closing as non active.
