### ISSUE TITLE
[QUESTION] ENGINE_LAUNCHER_API_VERSION 1  

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [dreamstalker/rehlds#343]
Hello ReHLDS Team!
I have a question for you and hope you can answer me
The question is - does current GS code (6153) contains impl for ENGINE_LAUNCHER_API_VERSION 1?
I'm talking about the old structure with func-pointers interface called engine_api_t that seems to be used by old dedicated launcher code and game code's soundsystem.cpp:
https://github.com/Sh1ft0x0EF/hlsdk-core/blob/rev/common/engine_launcher_api.h
https://github.com/ValveSoftware/halflife/blob/master/cl_dll/soundsystem.cpp
Current codebase doesn't have it but maybe you just didn't reverse it?

**Comment by LevShisterov** [comment]
Hi. Probably this is outdated feature. Engine binaries from original HLDS even in 4xxx builds contains only VENGINE_LAUNCHER_API_VERSION002 string.

**Comment by Sh1ft0x0EF** [comment]
So that's how things are going
Thank you
