### ISSUE TITLE
64bit possible ?

### ISSUE THREAD

**Issue by omertelli** [dreamstalker/rehlds#345]
[WSL](https://msdn.microsoft.com/en-us/commandline/wsl/faq) doesnt support 32bit libraries. 
64 bit  rehlds is that possible ?

**Comment by shelru** [comment]
https://github.com/Microsoft/BashOnWindows/issues/1403#issuecomment-278197677

**Comment by LevShisterov** [comment]
While theoretical possibility exists, it will require a lot of work on data types. Also all used modules (like AMXX, metamod, etc) also should be 64bit. So, probably, not in any nearest future.
