### ISSUE TITLE
System Error Log File

### ISSUE THREAD

**Issue by shelru** [dreamstalker/rehlds#346]
https://github.com/dreamstalker/rehlds/blob/2f64cfc873b25ca16f96db43727fe7d681b92cd3/rehlds/engine/sys_dll.cpp#L471

Не создается
Hosting myarena, мб хоть тут они увидят.

**Comment by shelru** [comment]
P.s рехлдс собирается без  REHLDS_FIXES, то есть стоят не bugfixed билды.
Доступа к engine не предоставляют.

**Comment by In-line** [comment]
@shelru данная функция доступна только для rehlds fixes. И пишите на английском

**Comment by Phantomsq** [comment]
> И пишите на английском
You too
