### ISSUE TITLE
ReHLDS 3.0.0.422-dev crashes at Linux with ReGameDLL 5.2.0.177-dev

### ISSUE THREAD

**Issue by S0m3Th1nG-AwFul** [dreamstalker/rehlds#347]
_CentOS Linux release 7.3.1611 (Core)_
Crash happens instantly after startup without any loaded metamod-plugins:
[Console_output.txt](https://github.com/dreamstalker/rehlds/files/768361/Console_output.txt)
[debug.log.txt](https://github.com/dreamstalker/rehlds/files/768363/debug.log.txt)
Full core dump also can be provided if necessary.

**Comment by LevShisterov** [comment]
via #348
