### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#356]
Can anyone in detail and easy way tell me how to compile the reHLDS and reGAMEDLL_CS and others locally ? 
I'm having none compilation app so please tell what to install how and all from start please.

**Comment by Phantomsq** [comment]
Read [this](https://github.com/dreamstalker/rehlds/blob/master/README.md)

**Comment by LevShisterov** [comment]
@ish12321, under what OS you are planning to compile?

**Comment by ish12321** [comment]
Windows

**Comment by LevShisterov** [comment]
Download and install Visual Studio 2013, 2015 or 2017. Probably Express or Community Edition would be enough. Open .sln file from msvc folder, select configuration and hit build.
