### ISSUE TITLE
Virus Total detected Malware in bugfixed hlds.exe & swds.dll

### ISSUE THREAD

**Issue by souvikdas95** [dreamstalker/rehlds#363]
@LevShisterov  -https://www.virustotal.com/en/file/6aca06d89a6b6d7cfd6df7fc0da7ee3a5678369948d59d72e4afc329c49691e5/analysis/1487303867/
https://www.virustotal.com/en/file/f4005fc01f74e7de0de1ef802d1c32fad027943bf6c92e01fea7e1c32f47c883/analysis/1487304582/

**Comment by theAsmodai** [comment]
It's failure of heuristic analysis.

**Comment by In-line** [comment]
Closing as non active.
