### ISSUE TITLE
Bug fire sound, decal bullet and not muzzleflash sprite showing.

### ISSUE THREAD

**Issue by Zetz512** [dreamstalker/rehlds#381]
Hello, i have a problem when i created a server dedicated, after i joining to server...

When i fire don't show the decal bullet on the wall, and no fire sound, only animation....

I use the latest dev version (3.0.0.478)
sry for my bad english

**Comment by In-line** [comment]
Does it happen with hlds ?

**Comment by Zetz512** [comment]
Yes, i use the bugfixed version

**Comment by Zetz512** [comment]
Here a video https://youtu.be/dqgUKUr3xgI with the problem

**Comment by WPMGPRoSToTeMa** [comment]
cl_lw?

**Comment by Zetz512** [comment]
cl_lw "1"

**Comment by WPMGPRoSToTeMa** [comment]
Did you try smokegrenade? Do you have `events` folder in gamedir? Is it empty or not?

**Comment by Zetz512** [comment]
No...I'll try it, yes i have events folder and have files... if it explained.... i play in other servers (obviously server with build 5758 or 6153) and i not have problem with this...

**Comment by Zetz512** [comment]
I am so sorry. i fixed this.....

That happen because a delete these files...
http://prntscr.com/ee39x4

**Comment by LevShisterov** [comment]
Just for the reference, image mention: halflife-cs.fgd, delta.lst and
GameServerConfig.vdf.

2017-02-27 23:30 GMT+05:00 Zetz512 <notifications@github.com>:
