### ISSUE TITLE
ShouldCollide not called

### ISSUE THREAD

**Issue by justgo97** [dreamstalker/rehlds#382]
```
#include <amxmodx>
#include <fakemeta>

public plugin_init()
{
	register_forward(FM_ShouldCollide, "ShouldCollide")
}

public ShouldCollide(playerindex, entindex)
{
	client_print(0, print_chat, "Called")
}
```

i don't know if i should post this here or in reapi section any ways once i use rehlds this forawrd is not called i tryed both sv_force_ent_intersection 0/1 if thats matters can we have it fixed ? or it should be added to reapi ?

**Comment by In-line** [comment]
Does it work with hlds?

**Comment by WPMGPRoSToTeMa** [comment]
Did you try to collide grenade with glass for example?

**Comment by justgo97** [comment]
it works with hlds.

i tryed grenade with player which worked on hlds but i when i installed rehlds it didn't, i will try grenade with glass now.

**Comment by WPMGPRoSToTeMa** [comment]
Do you use regamedll? What metamod version do you use? Can you try to hook `OnFreeEntPrivateData`?

**Comment by justgo97** [comment]
i tryed with out regamedll but same result, i use metamod 1.21p37, How to hook OnFreeEntPrivateData ?
liblist.gam:
```
game "Counter-Strike"
url_info "www.counter-strike.net"
url_dl ""
version "1.6"
size "184000000"
svonly "0"
secure "1"
type "multiplayer_only"
cldll "1" 
hlversion "1111"
nomodels "1"
nohimodel "1"
mpentity "info_player_start"
gamedll "dlls\mp.dll"
gamedll "addons\metamod\dlls\metamod.dll"
trainmap "tr_1"
edicts	"1800"
```

**Comment by WPMGPRoSToTeMa** [comment]
Comment this line in `liblist.gam`:
`gamedll "dlls\mp.dll"`

**Comment by justgo97** [comment]
all works now.  :+1:

**Comment by In-line** [comment]
@justgo97 You should close the issue
