### ISSUE TITLE
Amxmodx 1.8.3 Windows Signature

### ISSUE THREAD

**Issue by omertelli** [dreamstalker/rehlds#389]
Error ;
L 03/03/2017 - 11:22:26: Binding/Hooking cvars have been disabled - check your gamedata files.
L 03/03/2017 - 11:22:26: client_disconnected forward has been disabled - check your gamedata files.

Any idea ?

**custom/functions.engine.txt**
"Games"
{
	"#default"
	{
		"Signatures"
		{
			"SV_DropClient" // void SV_DropClient(client_t *cl, qboolean crash, const char *fmt, ...);
			{
				"library"   "engine"
				"windows"   "\x55\x8B\xEC\x81\xEC\x2A\x2A\x00\x00\xA1\x2A\x2A\x2A\x2A\x33\xC5\x89\x45\xFC\x53\x8B\x5D\x08\x56"
				"linux"     "@_Z22SV_DropClient_internalP8client_siPKc"
				"mac"       ""
			}
			"Cvar_DirectSet" // void Cvar_DirectSet(struct cvar_s *var, char *value);
			{
				"library"   "engine"
				"windows"   "\x55\x8B\xEC\x81\xEC\x2A\x2A\x00\x00\xA1\x2A\x2A\x2A\x2A\x33\xC5\x89\x45\xFC\x53\x56\x8B\xF1\x8B\xDA\x57\x85\xF6"
				"linux"     "@_Z14Cvar_DirectSetP6cvar_sPKc"
				"mac"       ""
			}
		}
	}
}

version
Protocol version 48
Exe version 1.1.2.7 (cstrike)
ReHLDS version: 3.0.0.418-dev
Build date: 20:38:00 Feb  6 2017 (1031)
Build from: https://github.com/dreamstalker/rehlds/commit/b0cd67b

**Comment by In-line** [comment]
It's not open source, but will help http://www.dedicated-server.ru/vbb/showthread.php?t=27127

**Comment by omertelli** [comment]
I cant use it , i need source code for fix some security things

**Comment by In-line** [comment]
@omerteli Contribute to amxmodx https://github.com/alliedmodders/amxmodx

**Comment by Arkshine** [comment]
(AMXX is going to have Re* support soon.)

**Comment by In-line** [comment]
@omerteli You can write small plugin with ReAPI that calls `client_disconnected`.

**Comment by spark512** [comment]
@Arkshine looking forward to that :)

**Comment by In-line** [comment]
Closing as non active
