### ISSUE TITLE
Auto health problem

### ISSUE THREAD

**Issue by csoyuncu** [dreamstalker/rehlds#402]
hello. Auto health plugin not working with rehlds engine. please fix.

**Comment by LevShisterov** [comment]
Hi.
More description required to say or do something about this.

**Comment by csoyuncu** [comment]
https://forums.alliedmods.net/showthread.php?p=702749 -> this plugin was working with oldest rehlds version. And, i upgraded my servers to new rehlds engine. After i upgraded my servers, this plugin didnot work...

**Comment by Phantomsq** [comment]
Are you sure the problem is in the engine update? What engine version was installed before the update?

**Comment by WPMGPRoSToTeMa** [comment]
Do you have ReGameDLL installed on your server?

**Comment by csoyuncu** [comment]
@Phantomsq i was using engine number 844 before update.

@WPMGPRoSToTeMa yes i installed regamedll version 180.

**Comment by Phantomsq** [comment]
There was done too many changes between the last build and your old 844 build. Maybe you have any logs about the plugin?

**Comment by In-line** [comment]
You​ really need to install an update, it can fix your issue.

**Comment by LevShisterov** [comment]
@csoyuncu, if I got you right, this plugin works on older ReHLDS version, right?
Can you please try versions between old and new and find on which version it stopped to work?

**Comment by csoyuncu** [comment]
@LevShisterov yes i am right. This plugin working with rehlds version 844. but not working with latest update. But i cant try all engine because i am gaming hosting and no free time. Thanks.

**Comment by WPMGPRoSToTeMa** [comment]
I've tested and it doesn't refers to ReHLDS, it refers only to ReGameDLL, autohealer doesn't work on next round.

**Comment by csoyuncu** [comment]
@WPMGPRoSToTeMa yes, you are right. Is there any fix for this problema?

**Comment by WPMGPRoSToTeMa** [comment]
@csoyuncu @s1lentq should fix this in regamedll in the near future.

**Comment by csoyuncu** [comment]
@WPMGPRoSToTeMa @s1lentq  thanks for your helps !
