### ISSUE TITLE
just a question

### ISSUE THREAD

**Issue by darth19** [dreamstalker/rehlds#404]
i should use rehlds from here  -> http://nexus.rehlds.org/nexus/content/repositories/rehlds-snapshots/rehlds/rehlds/0.2-SNAPSHOT/

or here -> http://nexus.rehlds.org/nexus/content/repositories/rehlds-dev/rehlds/rehlds/

¿?

**Comment by In-line** [comment]
http://teamcity.rehlds.org/guestAuth/downloadArtifacts.html?buildTypeId=Rehlds_Publish&buildId=lastSuccessful

**Comment by In-line** [comment]
Closing as non active.
