### ISSUE TITLE
ERROR: couldn't open custom.hpk.

### ISSUE THREAD

**Issue by justgo97** [dreamstalker/rehlds#416]
ERROR: couldn't open custom.hpk.

i get this in my consol alot.

any cvars to disable it or to fix it ?

**Comment by Raiz3n1312** [comment]
Give chmod 777 to server directory and all files restart server from webadmin or rcon with quit command and u can see the server generating custom.hpk file. 
ERROR: couldn't open custom.hpk
Generating custom.hpk beacuse not found.

**Comment by ivani6651** [comment]
Is there any solution to this thing, because when players start on the server of each player, they spam this message in 5 to 6 lines with this message.
ERROR: couldn't open custom.hpk

**Comment by In-line** [comment]
Closing as non active.
