### ISSUE TITLE
Reverse Engineered Stuffs causing LAG 

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#418]
Hello, 
My server 139.59.72.10:27015 is having lag.. !
when i asked our host they told all servers running HLDS aren't having lag and since only im having ReHLDS im having llags...
Please can anyone help fix the lag  ?

**Comment by Phantomsq** [comment]
Very doubtfully

**Comment by ish12321** [comment]
`Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-R  ini   Start ANY  
 [ 2] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
 [ 3] ReSemiclip       RUN   -    resemiclip_mm_i3  v2.3.9    ini   Chlvl ANY  
 [ 4] Revoice          RUN   -    revoice_mm_i386.  v0.1.26   ini   Start Never
 [ 5] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.684  ini   Chlvl ANY  
 [ 6] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-R  pl1   ANY   ANY  
 [ 7] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-R  pl1   ANY   ANY  
 [ 8] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-R  pl1   ANY   ANY  
 [ 9] ReAPI            RUN   -    reapi_amxx_i386.  v5.1.0.1  pl1   ANY   Never
 [10] Engine           RUN   -    engine_amxx_i386  v1.8.3-R  pl1   ANY   ANY  
10 plugins, 10 running`

**Comment by ish12321** [comment]
> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> ReHLDS version: 3.0.0.518-dev
> Build date: 20:24:57 Mar 20 2017 (1073)
> Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65

**Comment by ish12321** [comment]
@Phantomsq 
Please check this and help me .. !

**Comment by ish12321** [comment]
If anything else needed pls tell but please help me

**Comment by OsweRRR** [comment]
The module ReSemiclip, always lag

**Comment by ish12321** [comment]
Then what shall i use?

**Comment by OsweRRR** [comment]
Test disabled semiclip

**Comment by ish12321** [comment]
Can't as players need it too much.... 
If any alternative? 

BTW i removed reamxmodx and it solved by alot

**Comment by In-line** [comment]
You actually don't say what you meant by "lag". Is it low fps? Do you subjectively feel
 that weapon fire is delayed? Do you walk few steps in a game then server send you back?

I really doubt that resemiclip or (re)amxmodx (except when bad coded plugins are installed) can cause any issue with "lags".

**Comment by ish12321** [comment]
The ping goes to 1000s at randomly some time... 
About plugin same plugin at amxmodx works well..

**Comment by In-line** [comment]
Why don't you write about it? 😆

**Comment by ish12321** [comment]
What?

**Comment by In-line** [comment]
Plugin name and etc.. Nobody can read your mind dude.

**Comment by ish12321** [comment]
Bro plugins are all fine as told same are working fine on hlds...
However I'll give it to you once I'm on PC

**Comment by ish12321** [comment]
Sorry not hlds normal reamxmodx...

**Comment by In-line** [comment]
You wont know, unless somebody who have knowledge will see the source code

**Comment by ish12321** [comment]
Is it possible to give them to you in pm or somewhere as sharing all open source not possible... 
Some are private :D

**Comment by In-line** [comment]
Do you use latest amxmodx?

**Comment by ish12321** [comment]
1.8.2 i think
Will have to check as i used the one's pre-installed on my host

**Comment by In-line** [comment]
Latest 1.8.3 natively supports regamedll and rehlds, so try it out.

**Comment by ish12321** [comment]
Since this is working nice i wish not to change but would love to revert to reamxmodx once we got to know the reason of this..

**Comment by ish12321** [comment]
If you think checking the plugins will help is there any placei can privately send you so that you check them but let them be private :)

**Comment by ish12321** [comment]
BUMP ! my players checked it...
Reduced lag but not ended T_T

**Comment by WPMGPRoSToTeMa** [comment]
What lags do you mean? Can you record a video?

**Comment by ish12321** [comment]
Cl_flushentity with high ping frequently...
Camt record as my players lag

**Comment by WPMGPRoSToTeMa** [comment]
Let them check loss in net_graph.

**Comment by ish12321** [comment]
I've resetted server... 
To see if it's because of this rehlds and all..
I probably think it may not be because if this so had done it
...

**Comment by ish12321** [comment]
Lag is solved.. ! 
Was client side issue .. .
But btw im havign this log on my server start...
Is there any issues ?
OpTix | [ATG] | PuB 24x7

C

> ould not locate steam binary:steamcmd/steamcmd.sh, ignoring.
> 
> 
> 
> Console initialized.
> 
> Using breakpad crash handler
> 
> Setting breakpad minidump AppID = 10
> 
> Forcing breakpad minidump interfaces to load
> 
> dlopen failed trying to load:
> 
> /home/ogp_agent/.steam/sdk32/steamclient.so
> 
> with error:
> 
> /home/ogp_agent/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
> 
> Looking up breakpad interfaces from steamclient
> 
> Calling BreakpadMiniDumpSystemInit
> 
> Protocol version 48
> 
> Exe version 1.1.2.7/Stdio (cstrike)
> 
> Exe build: 20:24:57 Mar 20 2017 (1073)
> 
> STEAM Auth Server
> 
> 
> Server IP address 139.59.72.10:27015
> 
> 
> 
> Metamod version 1.21p37 Copyright (c) 2001-2013 Will Day
> 
> Patch: Metamod-P (mm-p) v37 Copyright (c) 2004-2013 Jussi Kivilinna
> 
> Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
> 
> This is free software, and you are welcome to redistribute it
> 
> under certain conditions; type `meta gpl' for details.
> 
> 
> 
> 
> 
> AMX Mod X version 1.8.3-Re Copyright (c) 2004-2016 AMX Mod X Development Team (modification ReHLDS Team)
> 
> AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
> 
> This is free software and you are welcome to redistribute it under 
> 
> certain conditions; type 'amxx gpl' for details.
> 
> 
> 
> [WHB] Version: 1.5.684 Linux (Usage SSE 4.1)
> 
> [WHB] Success: Build ReHLDS version defined Linux '1073'
> 
> [WHB] Success: Configuration executed.
> 
> ReGameDLL version: 5.2.0.181-dev
> 
> L 03/27/2017 - 16:29:32: -------- Mapchange to de_minidust2 --------
> 
> L 03/27/2017 - 16:29:32: ERROR : Important File [models/shove/shove.mdl] Not Found. Switching Off The Feature.
> 
> L 03/27/2017 - 16:29:32: ERROR : No Valid File To Play On Shove. Turning off the feature.
> 
> L 03/27/2017 - 16:29:32: ERROR : No Valid File To Play On Shove. Turning off the feature.
> 
> Executing ReGameDLL Configuration File 
> 
> [AMXX] Ð—Ð°Ð³Ñ€ÑƒÐ¶ÐµÐ½Ð¾ 10 Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑ‚Ñ€Ð°Ñ‚Ð¾Ñ€Ð¾Ð² Ð¸Ð· Ñ„Ð°Ð¹Ð»Ð°
> 
> [S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
> 
> dlopen failed trying to load:
> 
> /home/ogp_agent/.steam/sdk32/steamclient.so
> 
> with error:
> 
> /home/ogp_agent/.steam/sdk32/steamclient.so: cannot open shared object file: No such file or directory
> 
> Looking up breakpad interfaces from steamclient
> 
> Calling BreakpadMiniDumpSystemInit
> 
> 
> 
> Executing AMX Mod X Configuration File 
> 
> Ð§Ð°ÑÑ‚Ð¾Ñ‚Ð° Ð¿Ð¾ÑÐ²Ð»ÐµÐ½Ð¸Ñ Ð±ÐµÐ³ÑƒÑ‰ÐµÐ¹ ÑÑ‚Ñ€Ð¾ÐºÐ¸: 10:00 Ð¼Ð¸Ð½ÑƒÑ‚
> 
> Connection to Steam servers successful.
> 
> VAC secure mode is activated.

**Comment by lspublic** [comment]
Bro for my opinion you have very low ip addres , cant make lag very much from plugin just yoo have low ip :D

**Comment by Raiz3n1312** [comment]
`hostname "servername"
rcon_password "never_give_this_out"
sv_downloadurl "fastdownload link"

// Логи
log "off"
sv_logbans "0"
sv_logecho "0"
sv_logfile "0"
mp_logdetail "0"

// Управление игроками
mp_allowNPCs "0"
mp_allowspectators "1"
mp_autocrosshair "0"
mp_autokick "0"
mp_autoteambalance "1"
mp_buytime "0.00"
mp_c4timer "45"	
mp_chattime "6"
mp_decals "200"	
mp_fadetoblack "0"
mp_falldamage "1"
mp_flashlight "0"
mp_forcecamera "1"
mp_fraglimit "0"
mp_freezetime "0"
mp_footsteps "1"
mp_roundtime "3.00"
mp_timelimit "0"
mp_startmoney "0"
mp_friendlyfire "0"
mp_hostagepenalty "0"
mp_limitteams "1"
mp_maxrounds "50"
mp_playerid "0"
mp_tkpunish "0"
mp_winlimit "0"

// Управление сервером
sv_airaccelerate "1000"
sv_allowdownload "1"
sv_allowupload "1"
sv_alltalk "1"
sv_cheats "0"
sv_consistency "1"
sv_contact "info@switchtogaming.hu"
sv_footsteps "1"
sv_friction "4"
sv_gravity "800"
sv_maxrate "50000"
map "de_dust2"
sv_maxspeed "320"
sv_maxunlag "1"
sv_maxupdaterate "210"
sv_minrate "5000"
sv_minupdaterate "30"
sv_pausable "0"	
sv_rcon_banpenalty "300"
sv_rcon_maxfailures "2"
sv_rcon_minfailures "1"
sv_rcon_minfailuretime "30"
sv_specaccelerate "5"
sv_specnoclip "1"
sv_specspeed "3"
sv_stepsize "18"
sv_stopspeed "75"
sv_timeout "60"	
sv_unlag "1"
sv_voiceenable "1"

// Другое.
dp_rejmsg_hltv = "Sorry, HLTV is not allowed on this server"
sv_rehlds_movecmdrate_max_avg 3000
sv_rehlds_movecmdrate_max_burst 5000
sv_rehlds_stringcmdrate_max_avg 3000
sv_rehlds_stringcmdrate_max_burst 5000
sv_auto_precache_sounds_in_models 1
sv_delayed_spray_upload 1`
Try it.
