### ISSUE TITLE
online player count problem

### ISSUE THREAD

**Issue by omertelli** [dreamstalker/rehlds#42]
Hello , 
we have little problem like this
branch : stack_align
![players_bug](https://cloud.githubusercontent.com/assets/6948947/8434711/ac6ab4a6-1f55-11e5-83d7-dd1605b9cd59.png)

**Comment by dreamstalker** [comment]
Hi again!
This strange number comes from the rehlds-nosteam plugin.
Please repost this bug to that repository

**Comment by omertelli** [comment]
ops sorry thanks for information
