### ISSUE TITLE
Couldn't get sound buffer status

### ISSUE THREAD

**Issue by justgo97** [dreamstalker/rehlds#420]
when i play in the server with steam for 5-10 min i get this error loop

Couldn't get sound buffer status

with no steam client i don't get this problem.

**Comment by In-line** [comment]
Do you got this issue in server console? Did server/client crash after this? Did client disconnect after this? Do you have any logs?

**Comment by justgo97** [comment]
when this happen my cs freeze for some seconds and in server consol i get overflowed message then when my cs stop freezing it start looping that message in my client consol and no more overflowed message in server consol but problem is the client can no longer hear or use mic, some clients get crashed when thier cs freeze.

**Comment by WPMGPRoSToTeMa** [comment]
Do you use ReVoice or VTC?

**Comment by justgo97** [comment]
i use vtc lastest version.

**Comment by WPMGPRoSToTeMa** [comment]
Try without ReVoice and VTC.

**Comment by justgo97** [comment]
doesn't seem to happens but not very sure it will not cause its random.

**Comment by justgo97** [comment]
i can confirm that vtc increases overflows in the server alot, can lowring voice quality or any thing will fix it ?

**Comment by WPMGPRoSToTeMa** [comment]
Overflows or error loop count?

**Comment by justgo97** [comment]
before i get the loop frequency starts my cs freezes for 3 sec during that time the consol of server shows that i m overflowed. for some clients when cs freezes it crashs and server consol shows that they overflowed till they timeout.

**Comment by justgo97** [comment]
the problem happens when i press K to speak my client crashs or freeze for some seconds then i get that loop and can't not speak/hear any one any more, i never got this problem when i was with hlds i m thinking problem not in vtc but in rehlds but not sure cause i was using vtc with hlds and didn't have this problem.

**Comment by Sylvert0** [comment]
On my server when the players speak, all players have a peak of ping. I use VTC 2017 RC2

**Comment by justgo97** [comment]
i moved to old hlds and the problem still occurs, so the problem is in vtc or a plugin that i have that deal with voice the only code i have with voice is this:

```
	register_forward(FM_Voice_SetClientListening, "FakeMeta_Voice_SetListening", false);

public FakeMeta_Voice_SetListening(iReceiver, iSender, bool:bListen)
{
	if(((IsSetBit(g_iBitUserAlive, iSender) && g_iUserTeam[iSender]==2) 
	|| IsSetBit(g_iBitUserAdmin,iSender) || IsSetBit(g_iBitUserVip,iSender)) 
	&& !is_user_gagged(iSender))
	{
		engfunc(EngFunc_SetClientListening, iReceiver, iSender, true);
		return FMRES_SUPERCEDE;
	}
	engfunc(EngFunc_SetClientListening, iReceiver, iSender, false);
	return FMRES_SUPERCEDE;
}
```
i will remove it and report back.

**Comment by Hembi** [comment]
Which is recommended ReVoice or VTC?

**Comment by spark512** [comment]
@Hembi VTC

**Comment by justgo97** [comment]
@WPMGPRoSToTeMa can we have a the old version of vtc 80 for rehlds cause i didn't have this problem like this with it.

**Comment by WPMGPRoSToTeMa** [comment]
Do you have this problem on other servers? Can you test this problem on hlds with vtc 80? I think it is steam problem.

**Comment by justgo97** [comment]
i joined another server with normal hlds and vtc and the problem happend, many steam players of my firends have this problem...

**Comment by justgo97** [comment]
any solution other then playing with no steam client ?

**Comment by WPMGPRoSToTeMa** [comment]
Is it also happened w/o VTC and ReVoice? If so you should write to Steam Support.

**Comment by justgo97** [comment]
doubt if steam will update/fix cs1.6 any more

**Comment by WPMGPRoSToTeMa** [comment]
It is not directly related to CS or any gold source game, this is the part of voice submodule of steam (in steamclient.dll).

**Comment by justgo97** [comment]
good thing i didn't delete the non steam cs, just one question i know may sound stupid but if i copy steamclient.dll from the non steam clien to steam will i get vac banned or somthing.

**Comment by In-line** [comment]
Closing as non active.

**Comment by raheem-cs** [comment]
I think it's related to game as @WPMGPRoSToTeMa said, it happens for me when i'm in the server and suddenly removed the speakers (Unplug them from your PC) will make this annoying message and loop forever.

Before you open the game remove speakers, then open the game and enter the server, you won't find this message.

Tested on both steam & non-steam games and they are same, both go in this loop.
