### ISSUE TITLE
uninitialized sizebuf_t: ??? and crashing server

### ISSUE THREAD

**Issue by csoyuncu** [dreamstalker/rehlds#421]
**L 23/03/2017 - 00:11:02: (map "de_rebel") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 24/03/2017 - 18:14:52: (map "de_dust2") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 24/03/2017 - 20:04:38: (map "de_dustyaztec") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 24/03/2017 - 21:07:30: (map "de_inferno") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 25/03/2017 - 03:14:12: (map "soccerjam") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 25/03/2017 - 19:18:06: (map "de_barcelona") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 27/03/2017 - 03:50:06: (map "aim_deagle") TEX_InitFromWad: couldn't open aim_deagle.wad

L 27/03/2017 - 11:58:23: (map "de_inferno") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 27/03/2017 - 17:46:51: (map "de_inferno") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???**

**Comment by In-line** [comment]
Write in console
```
version
game version
meta list
```
Then show the output for the each of the commands.

**Comment by csoyuncu** [comment]
version
> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> ReHLDS version: 3.0.0.518-dev
> Build date: 20:24:57 Mar 20 2017 (1073)
> Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65

game version
> ReGameDLL version: 5.2.0.181-dev
> Build date: 23:17:23 Mar 23 2017
> Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/328a1d2

meta list
> Currently loaded plugins:
>       description      stat pend  file              vers      src   load  unlod
>  [ 1] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
>  [ 2] ReAuthCheck      RUN   -    reauthcheck_mm_i  v0.1.6    ini   Start Never
>  [ 3] Rechecker        RUN   -    rechecker_mm_i38  v2.3      ini   Chlvl ANY
>  [ 4] Revoice          RUN   -    revoice_mm_i386.  v0.1.26   ini   Start Never
>  [ 5] ReSemiclip       RUN   -    resemiclip_mm_i3  v2.3.9    ini   Chlvl ANY
>  [ 6] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.684  ini   Chlvl ANY
>  [ 7] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-R  ini   Start ANY
>  [ 8] ImpulseFullUpda  RUN   -    ifuf.so           v1.0      ini   ANY   Never
>  [ 9] UserInfoNetOpti  RUN   -    uino.so           v1.0      ini   ANY   Never
>  [10] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-R  pl7   ANY   ANY
>  [11] Engine           RUN   -    engine_amxx_i386  v1.8.3-R  pl7   ANY   ANY
>  [12] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-R  pl7   ANY   ANY
>  [13] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-R  pl7   ANY   ANY
>  [14] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-R  pl7   ANY   ANY
>  [15] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-R  pl7   ANY   ANY
> 15 plugins, 15 running

**Comment by csoyuncu** [comment]
@In-line  i wrote.

**Comment by omertelli** [comment]
when i use weapon icon plugin on my server, i was get error like this.
If u use weapon icon plugin, remove it pampa

**Comment by In-line** [comment]
```
[ 8] ImpulseFullUpda RUN - ifuf.so v1.0 ini ANY Never
```
This is useless with ReAuthCheck
```
[ 9] UserInfoNetOpti RUN - uino.so v1.0 ini ANY Never
```
This is useless with ReHLDS. see `sv_rehlds_userinfo_transmitted_fields`

This 2 modules can~~will~~ cause undefined behavior, so completely disable them.

**Comment by In-line** [comment]
This type of `Sys_Error` will most likely happen, when some plugin tries to send message to a disconnected player

**Comment by csoyuncu** [comment]
@In-line when i disabled userinfonetopti, players are taking overflow error and kicking.

**Comment by In-line** [comment]
@csoyuncu `sv_rehlds_userinfo_transmitted_fields "\name\model\*sid\*hltv"`

**Comment by csoyuncu** [comment]
@omertelli  thanks pampa i will disable onları :dancing_men: 

@In-line okey bro i will test it. Also, is fullupdate bug fixed this version?

**Comment by In-line** [comment]
@csoyuncu Yes.

**Comment by csoyuncu** [comment]
@omertelli ömer pampa kapattım amk eklentisini ama yine çöküyor oç serverlar :dagger: 

@In-line  thanks for info's bro. I will try them.

**Comment by WPMGPRoSToTeMa** [comment]
> This 2 modules canwill cause undefined behavior, because they weren't designed to work with ReHLDS, so completely disable them.

Only UINO can, because it uses some engine hooks. IFUF uses only engine API, so its ok, but has no effect, because in ReHLDS it is already fixed.

**Comment by WPMGPRoSToTeMa** [comment]
@csoyuncu so, it is happened always on server start/map change? If it will happened after removing these meta plugins then show us your amxx plugins list.

**Comment by csoyuncu** [comment]
@WPMGPRoSToTeMa i will test those tonight and i write results to you. But i returned now engine version 506.

**Comment by csoyuncu** [comment]
@WPMGPRoSToTeMa  i use standart plugins. And server crashes again...

**Comment by WPMGPRoSToTeMa** [comment]
@csoyuncu crashes on startup? Can you show current meta list? Do you use some bots?

**Comment by csoyuncu** [comment]
@WPMGPRoSToTeMa crash is not  at startup, it is randomly. Example, it crashes time 13:00 and later crashes time ise 15:30 ... 

Currently loaded plugins:
description stat pend file vers src load unlod
[ 1] Reunion RUN - reunion_mm_i386. v0.1.75 ini Start Never
[ 2] ReAuthCheck RUN - reauthcheck_mm_i v0.1.6 ini Start Never
[ 3] Rechecker RUN - rechecker_mm_i38 v2.3 ini Chlvl ANY
[ 4] Revoice RUN - revoice_mm_i386. v0.1.26 ini Start Never
[ 5] ReSemiclip RUN - resemiclip_mm_i3 v2.3.9 ini Chlvl ANY
[ 6] WHBlocker RUN - whblocker_mm_i38 v1.5.684 ini Chlvl ANY
[ 7] AMX Mod X RUN - amxmodx_mm_i386. v1.8.3-R ini Start ANY
[ 8] FakeMeta RUN - fakemeta_amxx_i3 v1.8.3-R pl7 ANY ANY
[ 9] Engine RUN - engine_amxx_i386 v1.8.3-R pl7 ANY ANY
[10] CStrike RUN - cstrike_amxx_i38 v1.8.3-R pl7 ANY ANY
[11] Ham Sandwich RUN - hamsandwich_amxx v1.8.3-R pl7 ANY ANY
[12] CSX RUN - csx_amxx_i386.so v1.8.3-R pl7 ANY ANY
[13] Fun RUN - fun_amxx_i386.so v1.8.3-R pl7 ANY ANY
13 plugins, 13 running

**Comment by csoyuncu** [comment]
@In-line  @WPMGPRoSToTeMa  @omertelli server still crashes...

L 29/03/2017 - 18:52:34: (map "de_duhran") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 29/03/2017 - 22:42:40: (map "de_wadi") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???

**Comment by In-line** [comment]
It's very likely that your hosting added some custom plugins in default installation. So try to download amxmodx and install it from their officiall website.

**Comment by csoyuncu** [comment]
@In-line i am hosting bro. But no problem at oldest rehlds versiyon. After i updated to new rehlds, servers started crashing.

**Comment by s1lentq** [comment]
@csoyuncu try revert to a previous version of WHBlocker.

**Comment by csoyuncu** [comment]
@s1lentq i will try.

**Comment by csoyuncu** [comment]
@s1lentq i downgraded to version 1.672 and i will write results tomorrow from here.

**Comment by csoyuncu** [comment]
@s1lentq servers crash again after i downgraded whblocker to versyion 1.672

**Comment by In-line** [comment]
Same error ?

**Comment by csoyuncu** [comment]
@In-line yes.

**Comment by Hembi** [comment]
Hi!
We have the same problem here. We are a game server hosting too.
Only a few days have we this problem. Randomly crash on running time.

> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> ReHLDS version: 3.0.0.518-dev
> Build date: 20:24:57 Mar 20 2017 (1073)
> Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65

> ReGameDLL version: 5.2.0.181-dev
> Build date: 23:17:23 Mar 23 2017
> Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/328a1d2

> Currently loaded plugins:
>       description      stat pend  file              vers      src   load  unlod
>  [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.2-d  ini   Start ANY  
>  [ 2] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
>  [ 3] Revoice          RUN   -    revoice_mm_i386.  v0.1.26   ini   Start Never
>  [ 4] Rechecker        RUN   -    rechecker_mm_i38  v2.3      ini   Chlvl ANY  
>  [ 5] ReSemiclip       RUN   -    resemiclip_mm_i3  v2.3.9    ini   Chlvl ANY  
>  [ 6] ReAuthCheck      RUN   -    reauthcheck_mm_i  v0.1.6    ini   Start Never
>  [ 7] SafeNameAndChat  RUN   -    SafeNameAndChat.  v1.0      ini   ANY   ANY  
>  [ 8] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.672  ini   Chlvl ANY  
>  [ 9] Fun              RUN   -    fun_amxx_i386.so  v1.8.2    pl1   ANY   ANY  
>  [10] Engine           RUN   -    engine_amxx_i386  v1.8.2    pl1   ANY   ANY  
>  [11] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.2    pl1   ANY   ANY  
>  [12] CStrike          RUN   -    cstrike_amxx_i38  v1.8.2-d  pl1   ANY   ANY  
>  [13] CSX              RUN   -    csx_amxx_i386.so  v1.8.2    pl1   ANY   ANY  
>  [14] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.2    pl1   ANY   ANY  
>  [15] ReFreeLook       RUN   -    refreelook_amxx_  v1.5 (b)  pl1   ANY   Never
>  [16] ReAPI            RUN   -    reapi_amxx_i386.  v5.1.0.1  pl1   ANY   Never

On this server run a spectator bots plugin (Fakefull Original).
Here is the amxx: https://files.fm/u/g9bfyd9u

Which servers are in older version of ReHLDS and plugins they run without any problem.

**Comment by WPMGPRoSToTeMa** [comment]
Need dump.
> Which servers are in older version of ReHLDS and plugins they run without any problem.

How older?

**Comment by Hembi** [comment]
Where can I find the dump what you need?

In debug.log:

> CRASH: Sat Apr  1 23:37:44 CEST 2017
> Start Line: ./hlds_linux -pidfile hlds_27580 -game cstrike -secure +ip serverip +port 27580 +sv_lan 0 +maxplayers 20 +map de_dust2 +sys_ticrate 1000 -pingboost 2 -zone 8192
> End of crash report

The most of our servers are run on rehlds-3.0.0.435-dev, but we allow the users to update their servers manually.

**Comment by csoyuncu** [comment]
@In-line @WPMGPRoSToTeMa  @s1lentq  @Hembi i returned version 504 and crash problem solved nowly. I wont update my servers after this time...

**Comment by Hembi** [comment]
@csoyuncu So the 3.0.0.504 works. Thank you for the information.

**Comment by Hembi** [comment]
@WPMGPRoSToTeMa I found a dump file. I do not want to share here, because it contain some information abour our servers. I will send you in PM.

**Comment by WPMGPRoSToTeMa** [comment]
@Hembi skype?

**Comment by Hembi** [comment]
hembi5

**Comment by csoyuncu** [comment]
@WPMGPRoSToTeMa artem skype onur.uyar :dancing_men:

**Comment by kobra3** [comment]
Hello there,I encounter the same problem.

L 06/04/2017 - 11:03:53: (map "fy_snow") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 06/04/2017 - 19:12:24: (map "de_militia") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 06/04/2017 - 20:50:21: (map "de_dusferno2") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 06/04/2017 - 22:50:32: (map "awp_dust") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 07/04/2017 - 18:32:19: (map "de_dustyaztec") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 07/04/2017 - 19:48:26: (map "de_dust2") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 07/04/2017 - 20:10:19: (map "de_dust2") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 07/04/2017 - 21:32:51: (map "de_snow") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 08/04/2017 - 12:11:45: (map "de_zook") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 08/04/2017 - 12:34:28: (map "awp_lego_2_lite") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 08/04/2017 - 12:34:45: (map "awp_lego_2_lite") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 08/04/2017 - 14:20:05: (map "awp_zigzag") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 08/04/2017 - 14:29:33: (map "de_snow") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???
L 08/04/2017 - 16:55:55: (map "de_dust") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???

Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.0.0.518-dev
Build date: 20:24:57 Mar 20 2017 (1073)
Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65

ReGameDLL version: 5.2.0.181-dev
Build date: 23:17:23 Mar 23 2017
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/328a1d2

Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-R  ini   Start ANY  
 [ 2] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
 [ 3] ReSemiclip       RUN   -    resemiclip_mm_i3  v2.3.9    ini   Chlvl ANY  
 [ 4] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.684  ini   Chlvl ANY  
 [ 5] Rechecker        RUN   -    rechecker_mm_i38  v2.3      ini   Chlvl ANY  
 [ 6] ReAuthCheck      RUN   -    reauthcheck_mm_i  v0.1.6    ini   Start Never
 [ 7] ReAPI            RUN   -    reapi_amxx_i386.  v5.1.0.1  pl1   ANY   Never
 [ 8] hackdetector     RUN   -    hackdetector_amx  v0.15.32  pl1   ANY   ANY  
 [ 9] ReAimDetector    RUN   -    reaimdetector_am  v0.1.6    pl1   ANY   Never
 [10] Engine           RUN   -    engine_amxx_i386  v1.8.3-R  pl1   ANY   ANY  
 [11] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-R  pl1   ANY   ANY  
 [12] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-R  pl1   ANY   ANY  
 [13] MySQL            RUN   -    mysql_amxx_i386.  v1.8.3-R  pl1   ANY   ANY  
 [14] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-R  pl1   ANY   ANY  
 [15] GeoIP            RUN   -    geoip_amxx_i386.  v1.8.3-R  pl1   ANY   ANY  
 [16] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-R  pl1   ANY   ANY  
 [17] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-R  pl1   ANY   ANY  
17 plugins, 17 running

**Comment by justgo97** [comment]
i don't have this problem my setup is : 

```
version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.0.0.518-dev
Build date: 20:24:57 Mar 20 2017 (1073)
Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65

game version
ReGameDLL version: 5.2.0.181-dev
Build date: 23:17:23 Mar 23 2017
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/328a1d2

meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
 [ 2] hackdetector     RUN   -    hackdetector_amx  v0.15.32  ini   ANY   ANY
 [ 3] SafeNameAndChat  RUN   -    SafeNameAndChat.  v1.1      ini   ANY   ANY
 [ 4] VoiceTranscoder  RUN   -    VoiceTranscoder.  v2017 RC  ini   ANY   ANY
 [ 5] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-R  ini   Start ANY
 [ 6] Ultimate Unprec  RUN   -    libunprecacher.s  vBeta 1.  ini   ANY   ANY
 [ 7] SQLite           RUN   -    sqlite_amxx_i386  v1.8.3-R  pl5   ANY   ANY
 [ 8] Parachute        RUN   -    para_amxx_i386.s  v1.3      pl5   ANY   ANY
 [ 9] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-R  pl5   ANY   ANY
 [10] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-R  pl5   ANY   ANY
 [11] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-R  pl5   ANY   ANY
 [12] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-R  pl5   ANY   ANY
 [13] Engine           RUN   -    engine_amxx_i386  v1.8.3-R  pl5   ANY   ANY
 [14] ReAPI            RUN   -    reapi_amxx_i386.  v5.1.0.1  pl5   ANY   Never
 [15] ReAuthCheck      open  -    reauthcheck_mm_i  v0.1.5    ini   Start Never
15 plugins, 14 running
```

**Comment by kobra3** [comment]
why would I remove whblocker when I need it the most...what about amxx plugins,can it be from those? I got a classic server with just a few plugins.

**Comment by justgo97** [comment]
remove them temporary to see if they cause the problem or not.

**Comment by kobra3** [comment]
will try,but I have noticed now that it's only hapening on certain maps,for example I can't play fy_snow at all,server shuts down at mapchange and I'm getting this in client console : 
Netchan_CheckForCompletion:  Lost/dropped fragment would cause stall, retrying connection.
Will post here further analysis.

**Comment by csoyuncu** [comment]
no problem was at older versions @justgo97

**Comment by justgo97** [comment]
@csoyuncu try the same meta list i have and see it happens.

**Comment by Raiz3n1312** [comment]
(map "de_dust2") SZ_GetSpace: tried to write to an uninitialized sizebuf_t: ???

Version
15:26:11 Protocol version 48
         Exe version 1.1.2.7/Stdio (cstrike)
         ReHLDS version: 3.0.0.518-dev
         Build date: 20:24:57 Mar 20 2017 (1073)
         Build from: https://github.com/dreamstalker/rehlds/commit/7e05e65

meta list
15:26:40 Currently loaded plugins:
               description      stat pend  file              vers      src   load  unlod
          [ 1] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
          [ 2] VoiceTranscoder  RUN   -    VoiceTranscoder.  v2017 RC  ini   ANY   ANY  
          [ 3] Rechecker        RUN   -    rechecker_mm_i38  v2.3      ini   Chlvl ANY  
          [ 4] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-R  ini   Start ANY  
          [ 5] WHBlocker        RUN   -    whblocker_mm_i38  v1.5.684  ini   Chlvl ANY  
          [ 6] ReSemiclip       RUN   -    resemiclip_mm_i3  v2.3.8    ini   Chlvl ANY  
          [ 7] ReAuthCheck      RUN   -    reauthcheck_mm_i  v0.1.6    ini   Start Never
          [ 8] Engine           RUN   -    engine_amxx_i386  v1.8.3-R  pl4   ANY   ANY  
          [ 9] MySQL            RUN   -    mysql_amxx_i386.  v1.8.3-R  pl4   ANY   ANY  
          [10] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-R  pl4   ANY   ANY  
          [11] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-R  pl4   ANY   ANY  
          [12] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-R  pl4   ANY   ANY  
          [13] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-R  pl4   ANY   ANY  
          [14] CSX              RUN   -    csx_amxx_i386.so  v1.8.3-R  pl4   ANY   ANY  
         14 plugins, 14 running
amxx plugins

15:27:22 Currently loaded plugins:
                name                    version     author            file             status   
          [  1] BanRendszer             1.0         Exolent # Raiz3n  ban_system.amxx  running  
          [  2] Admin Login System      1.3         mforce            adminsystem.amx  running  
          [  3] Admin Commands          1.8.2       AMXX Dev Team     admincmd.amxx    running  
          [  4] Multi-Lingual System    1.8.2       AMXX Dev Team     multilingual.am  running  
          [  5] AmxMenuu                1.0         DUKKHAZ0R         menufront.amxx   running  
          [  6] Commands Menu           1.8.2       AMXX Dev Team     cmdmenu.amxx     running  
          [  7] Players Menu            1.8.2       AMXX Dev Team     plmenu.amxx      running  
          [  8] Block Advertising       1.3         Alka              hirdetesgatlo.a  running  
          [  9] Maps Menu               1.8.2       AMXX Dev Team     mapsmenu.amxx    running  
          [ 10] Plugin Menu             1.8.2       AMXX Dev Team     pluginmenu.amxx  running  
          [ 11] Admin Chat              1.8.2       AMXX Dev Team     adminchat.amxx   running  
          [ 12] Admin Votes             1.8.2       AMXX Dev Team     adminvote.amxx   running  
          [ 13] NextMap                 1.8.2       AMXX Dev Team     nextmap.amxx     running  
          [ 14] TimeLeft                1.8.2       AMXX Dev Team     timeleft.amxx    running  
15:27:22  [ 15] Pause Plugins           1.8.2       AMXX Dev Team     pausecfg.amxx    running  
          [ 16] Stats Configuration     1.8.2       AMXX Dev Team     statscfg.amxx    running  
          [ 17] Lite Admin ESP          1.0         neygomon          adminwh.amxx     running  
          [ 18] Bullet Damage with Spe  1.3         Sn!ff3r, modded   abd.amxx         running  
          [ 19] Advanced Weapon Menu    0.0.1       #YouCantStopMe    fegyomenu.amxx   running  
          [ 20] Anti-Rush               1.0         Kiki33            anti-rush_d2.am  running  
          [ 21] Lite Kill Assists       1.17        neygomon          fragfelezo.amxx  running  
          [ 22] Anti Flashbang Bug      1.1.1       Numb / ConnorMcL  noteamflash.amx  running  
          [ 23] Lite Chat               1.0         neygomon, mforce  lite_chat.amxx   running  
          [ 24] SF MultiJump            0.2         serfreeman1337    sf_multijump.am  running  
          [ 25] Parachute               1.3         KRoT@L/JTP10181   parachute.amxx   running  
          [ 26] KGB Bots                2.3         OvidiuS & Desika  specbot.amxx     running  
          [ 27] Advert Messages         1.22        neygomon          adverts.amxx     running  
          [ 28] Granathang blokk        1.0         mforce            BlockGrenadeInf  running  
          [ 29] Resetscore chat         1.0         mforce            resetscore_chat  running  
15:27:22  [ 30] Team Grenade Trail      1.2         Numb              newcsik.amxx     running  
          [ 31] Hungarian Ultimate Sou  2.0         bron              ulzihang.amxx    running  
          [ 32] HU-Language             1.0         Dave              autohu.amxx      running  
          [ 33] Karomkodas tilto        1           qKKKJ             karomkodasellen  running  
          [ 34] CSStatsX MySQL          0.5         serfreeman1337    ranksys.amxx     running  
          [ 35] Link MODT               2.6         Raiz3n            weboldal_motd.a  running  
          [ 36] AFK Kicker              1.0b        Cheesy Peteza     afkq12.amxx      running  
         36 plugins, 36 running
Game version
15:28:00 ReGameDLL version: 5.2.0.180-dev
         Build date: 04:41:17 Mar 10 2017
         Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/bf8bda0
20+ players and the server is going shut down with this error. 20 players lower nothing a problem on server going normal. Tired to fix the problem any idea?

**Comment by justgo97** [comment]
Try remove all meta plugins not in this list:
```
meta list
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] Reunion          RUN   -    reunion_mm_i386.  v0.1.75   ini   Start Never
 [ 2] hackdetector     RUN   -    hackdetector_amx  v0.15.32  ini   ANY   ANY
 [ 3] SafeNameAndChat  RUN   -    SafeNameAndChat.  v1.1      ini   ANY   ANY
 [ 4] VoiceTranscoder  RUN   -    VoiceTranscoder.  v2017 RC  ini   ANY   ANY
 [ 5] AMX Mod X        RUN   -    amxmodx_mm_i386.  v1.8.3-R  ini   Start ANY
 [ 6] Ultimate Unprec  RUN   -    libunprecacher.s  vBeta 1.  ini   ANY   ANY
 [ 7] SQLite           RUN   -    sqlite_amxx_i386  v1.8.3-R  pl5   ANY   ANY
 [ 8] Parachute        RUN   -    para_amxx_i386.s  v1.3      pl5   ANY   ANY
 [ 9] CStrike          RUN   -    cstrike_amxx_i38  v1.8.3-R  pl5   ANY   ANY
 [10] Fun              RUN   -    fun_amxx_i386.so  v1.8.3-R  pl5   ANY   ANY
 [11] FakeMeta         RUN   -    fakemeta_amxx_i3  v1.8.3-R  pl5   ANY   ANY
 [12] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.8.3-R  pl5   ANY   ANY
 [13] Engine           RUN   -    engine_amxx_i386  v1.8.3-R  pl5   ANY   ANY
 [14] ReAPI            RUN   -    reapi_amxx_i386.  v5.1.0.1  pl5   ANY   Never
 [15] ReAuthCheck      open  -    reauthcheck_mm_i  v0.1.5    ini   Start Never
15 plugins, 14 running
```

**Comment by Raiz3n1312** [comment]
okay now we testing the server whitout whb+ resemiclip.

**Comment by Raiz3n1312** [comment]
We have removed whb from server. Not freezing now. But we give extra memory for server. Next time testing whb. I think its a memory problem. Needed more memory (ram) for server.

**Comment by Raiz3n1312** [comment]
Okay. The Wallhackblocker freezing server.. We give 1024mb of ram / server and activated the whb. And the whb was killed the server again... So just disable the wallhackblocker modul and its work fine.

**Comment by csoyuncu** [comment]
@Raiz3n1312 @kobra3 @In-line @WPMGPRoSToTeMa we must report this problem to WHblocker coder. How can we contact with her ?

**Comment by Raiz3n1312** [comment]
The wallhackblocker was reported on neugomon.ru. And the developer was fixed the problem and updated the plugin to  1.5.690... Now u can download on neugomon.ru

**Comment by In-line** [comment]
[Here](http://aghl.ru/forum/viewtopic.php?f=19&t=1704) is official WHBlocker topic. If problem was solved, please click on "close issue" button.

**Comment by Raiz3n1312** [comment]
We are now on testing the whb now. We need 20+ player to server. So the test needed 2-3 day. Sry

**Comment by csoyuncu** [comment]
@In-line i am testing at 100 cs 1.6 servers now. I wıll write results now a days and later will close this issue topic.

**Comment by Raiz3n1312** [comment]
We are end the tests. Now 100% the Wallhack blocker making this problem on server.

**Comment by justgo97** [comment]
@Raiz3n1312 did you try the lastest version from here http://aghl.ru/forum/viewtopic.php?f=19&t=1704 ?

**Comment by Raiz3n1312** [comment]
Yes. Its tested. No more errors on whb close topic please

**Comment by In-line** [comment]
@csoyuncu If problem is solved, please close issue

**Comment by Raiz3n1312** [comment]
Yes its fixed :D
