### ISSUE TITLE
Bug Pseudo Players is not my Pseudo

### ISSUE THREAD

**Issue by GoRiLliAz** [dreamstalker/rehlds#425]
Hello,

I use rehlds since yesterday I realize that when a players and gag by the plugins of xpawn ( https://forums.alliedmods.net/showthread.php?t=101937 ) and that this disconnects from the server of game if a person returns ben it takes the nick of the one that left.

**Comment by In-line** [comment]
Can you describe problem more clearer ? Does it happen with hlds ?

**Comment by GoRiLliAz** [comment]
No it is not this product with HLDS

Example: Player A = Test if Player is muted on the server and it deconnect and the player B = test1 this connect, test1 becomes test

**Comment by Nemesis31** [comment]
Hi,

FYI there is a bug on CS that when a player leaves a server, the server doesn't update userinfo or playerinfo and keep it inside the cache. So, when a new player connects, he will take the name of the last disconnected player.

**Comment by spark512** [comment]
This has nothing to do with ReHLDS, your gag plugin is not properly coded for reconnect events.
