### ISSUE TITLE
Simple anti-cheat logic 

### ISSUE THREAD

**Issue by 9danst** [dreamstalker/rehlds#44]
It's just a question/request.. so

Can we have a simple code implemented to break current cheats? something like to stop sending unwanted data to clients (non-visible enemies position for e.g). This feature will get you some real popular usage besides stability and improvement.

anyway, thank you guys.

**Comment by dreamstalker** [comment]
Hi!
I don't like the idea of anti-wallhack integration into the engine for several reasons:
1) This code would not be simple. You'll probably have to do tons of TraceLines to check if players are visible to each other. Another mindblowing thing that should be kept in mind is that client does interpolation when drawing player models and therefore player models are drawn with small lag (which is controlled by ex_interp)
2) It's not up to engine to decide which entities are visible for particular player. GameDLL does this in the pfnAddToFullPack callback.

**Comment by WPMGPRoSToTeMa** [comment]
@dreamstalker what about preventing speedhack?

**Comment by johnally** [comment]
Do close this issue as all anti-cheat logic should be taken care of at a lower level (i.e GameDLL / Metamod / Amxmodx) than the engine itself.

**Comment by WPMGPRoSToTeMa** [comment]
@johnally speedhack is engine bug and should be fixed in engine.

**Comment by Raiz3n1312** [comment]
Use Rechecker :dancing_men:
