### ISSUE TITLE
net_address -> can include sv_rehlds_net_address

### ISSUE THREAD

**Issue by OsweRRR** [dreamstalker/rehlds#451]
can include that cvar, but don't must be modified how net_address. or make cvar net_address unmodifiable.

**Comment by In-line** [comment]
Reason?

**Comment by OsweRRR** [comment]
net_address is modified and you can not know the exact ip.. in amxmodx, native get_user_ip( in 0, .. , ..) return the value net_address.

**Comment by OsweRRR** [comment]
if set net_address "255.255.255.255"

the value in get_user_ip( in 0, .. , ...) will be "255.255.255.255", and not the server ip.

**Comment by LevShisterov** [comment]
Isn't it the server operator responsibility to change it (use plugins that
change it) or do not?

**Comment by WPMGPRoSToTeMa** [comment]
Real (public) ip address is accessible via Steam API. There is an [amxx module](https://forums.alliedmods.net/showthread.php?t=261044) where you can get it through `Steam_GetPublicIP` function.

**Comment by In-line** [comment]
Closing as non active.
