### ISSUE TITLE
ReHLTV not working / Couldn't load filesystem_steam.dll

### ISSUE THREAD

**Issue by krangm** [dreamstalker/rehlds#455]
hello

ReHLTV not working

im using HLTV for Adrenaline Gamer mod with these launch parameters:
`-maxfps 250 -steam -dev +rate 20000 +updaterate 40 +maxrate 10000`

but ReHLTV gives an error
Couldn't load filesystem_steam.dll.
http://i.imgur.com/WVndZr2.png

without `-steam` parameter it loads but immediately freezes and crashes
http://i.imgur.com/eCgfGyD.png
tho last line is
Steam_: BugslayerUtil.DLL not found
it was but never bothered me at regular HLTV

**Comment by In-line** [comment]
Can you provide a crash dump ?

**Comment by krangm** [comment]
crash dump
http://www26.zippyshare.com/v/MtrD62yb/file.html

btw i realised that it crashes only on several maps, tho most of them are default ones

it also doesnt show up in Spectate tab in game ServerBrowser which is kinda problem for me

**Comment by In-line** [comment]
@krangm Problem is located and s1lentq is working to fix it. Don't use -steam option it's obsolete and will be probably deleted.

**Comment by krangm** [comment]
thank you
now working

but i have a few questions left

1. is it possible to make ReHLTV visible in ServerBrowser in game ?
http://i.imgur.com/m7n4B4C.png
theres no more `forcemaster` cvar

2. i see in new ReHLDS builds theres no more split on pure / bugfixed versions.
which version is using in new build ?

**Comment by In-line** [comment]
@krangm ReHLTV was just released there are only minor bugfixes for now. Are you sure about forcemaster?

**Comment by krangm** [comment]
yes im sure theres no forcemaster, but it also absents at regular HLTV
probably outdated command, i've read about it at support.steampowered.com

i noticed ReHLTV gives an error on start about `+ip` launch parameter
which was working fine on regular HLTV
http://i.imgur.com/Qnl1deo.png
but i still can connect via client console using direct address

it also crashed 2 times within last half hour with 2 different errors
dunno if it might be helpful
here are dumps
http://www113.zippyshare.com/v/HIrDhv8b/file.html

**Comment by LevShisterov** [comment]
@krangm please do not mix issues. If this one is solved: close it and open another. Also, do not post two problems in one issue if they are unrelated. It will be much easier to track and solve.

**Comment by krangm** [comment]
@LevShisterov слушаюсь
