### ISSUE TITLE
ReHLTV not visible in ServerBrowser in game

### ISSUE THREAD

**Issue by krangm** [dreamstalker/rehlds#459]
is it possible to make ReHLTV visible in ServerBrowser in game ?
as it was on regular HLTV
http://i.imgur.com/m7n4B4C.png

(probably related)
i noticed ReHLTV gives an error on start about `+ip` launch parameter
which was working fine on regular HLTV
http://i.imgur.com/Qnl1deo.png
but i still can connect via client console using direct address

**Comment by krangm** [comment]
i see its fixed in 558
thank you

**Comment by s1lentq** [comment]
> i noticed ReHLTV gives an error on start about +ip launch parameter

this parameter does not exist in HLTV, read please [doc](https://github.com/dreamstalker/rehlds/tree/master/rehlds/HLTV#hltv-configuration).
There is only `-ip`
