### ISSUE TITLE
ReHLTV crash errors / ntdll.dll & StackHash errors

### ISSUE THREAD

**Issue by krangm** [dreamstalker/rehlds#460]
ReHLTV crashed a few times with different errors

before that server had a regular HLTV which was running fine about a year
and never ever crashed a single time
nothing was changed except move HLTV -> ReHLTV

here are dumps
http://www113.zippyshare.com/v/HIrDhv8b/file.html

**Comment by In-line** [comment]
They aren't crash dumps.

**Comment by s1lentq** [comment]
@krangm What is your OS?

**Comment by krangm** [comment]
sorry
@In-line is there any instruction how can i get proper crash dumps ?

@s1lentq Win2008r2x64

and it just crashed again
http://www71.zippyshare.com/v/9SlTLcYQ/file.html

**Comment by In-line** [comment]
@krangm There are infinite amount of guides about that. You can also find few in aghl.ru (if ylu want russian guide)

**Comment by krangm** [comment]
unfortunately none of the methods described at aghl.ru worked well for me
i edited register for getting dumps but it just not doing them
i got one after 25th or 30th crash (ReHLTV is crashing 1-2 times per every 20 minutes)
here it is
http://www5.zippyshare.com/v/pkoIIw35/file.html

**Comment by krangm** [comment]
got some more dumps via ProcDump
http://www89.zippyshare.com/v/MU6ebXOm/file.html

**Comment by In-line** [comment]
Did you update HLTV?

**Comment by krangm** [comment]
ofc, using 3.0.0.558-dev

**Comment by krangm** [comment]
thanks, since 3.0.0.567-dev not crashing every changemap
