### ISSUE TITLE
Unknow Server Error

### ISSUE THREAD

**Issue by Raiz3n1312** [dreamstalker/rehlds#462]
Error: server failed to transmit file 'AY&SY���'
Last 32 messages parsed.
654204 0301 TeamInfo
654204 0314 ScoreInfo
654204 0324 TeamInfo
654204 0337 ScoreInfo
654204 0347 TeamInfo
654204 0353 ScoreInfo
654204 0363 TeamInfo
654204 0376 ScoreInfo
654204 0386 svc_updateuserinfo
654204 0555 svc_updateuserinfo
654204 0744 svc_updateuserinfo
654204 0931 svc_updateuserinfo
654204 1118 svc_updateuserinfo
654204 1312 svc_updateuserinfo
654204 1484 svc_updateuserinfo
654204 1669 svc_updateuserinfo
654204 1848 svc_updateuserinfo
654204 2040 svc_updateuserinfo
654204 2208 AmmoX
654204 2211 CurWeapon
654204 2215 CurWeapon
654204 2219 HudTextArgs
654204 2251 Radar
654204 2259 ScoreAttrib
654204 2262 Radar
654204 2270 SendAudio
654204 2285 svc_temp_entity
654204 2294 RoundTime
654204 2297 CurWeapon
654204 2301 CurWeapon
654204 2305 svc_filetxferfailed
BAD:  2316:svc_bad
Host_Error: CL_ParseServerMessage: Illegible server message - svc_bad

I think its a vocietranscoder problem maybe? Or no?

version : 48/1.1.2.7/Stdio 6132 secure (10) -ez a build szám

**Comment by csoyuncu** [comment]
use ReVoice.

**Comment by In-line** [comment]
Why do you think it's voicetranscoder problem ?

**Comment by Raiz3n1312** [comment]
not voice transcoder the problem :/

**Comment by WPMGPRoSToTeMa** [comment]
What is the version of `ReHLDS`?
