### ISSUE TITLE
HLTV: Invalid rcon challenge

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#471]
I tried rehlds today for the first time and just copied it over my existing hlds-installation.
Everything seems to work, but the 'hltv-autorecord' (https://forums.alliedmods.net/showthread.php?p=993138?p=993138).
On the hltv-console i can see:
"Invalid rcon challenge from LOCAL_SERVER_IP"'
In the hltv.cfg i've set a 'adminpassword'.
This Setup worked on my 'original installtion' for years now.
i'm using todays build of rehlds on linux with latest amxx-git.

**Comment by LevShisterov** [comment]
Try to replace (both places)

			setc(send[28], 1, '^n')

			socket_send2(socket_address, send, 255)	

with

			setc(send[28], 1, '^n')
			send[29] = 0;
			
			socket_send2(socket_address, send, 30)	

And

		log_amx("sending: %s", send)
		socket_send2(socket_address, send, 255)

into

		log_amx("sending: %s", send)
		socket_send2(socket_address, send, 5 + strlen(send[4]))

**Comment by fred0r** [comment]
No - doesnt work :(

**Comment by fred0r** [comment]
So can you confirm that this a reHLTV-Bug ?
Or is it AMXX/Plugin related ?

**Comment by In-line** [comment]
If it's bug then s1lentq is working in silent mod to fix it :)

**Comment by fred0r** [comment]
Hm - still doesnt work for me.
I tried the 'original Plugin' and also the LevShisterov-variant.
Still getting "Invalid rcon challenge from: LOCAL_SERVER_IP:PORT"
