### ISSUE TITLE
HLTV: Invalid rcon challenge - Part 2

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#476]
Since it seems not possible to reopen the already closed Issue (#471) i open a new one.
I still get "Invalid rcon challenge from: LOCAL_SERVER_IP:PORT" when trying to initiate the demo-record using hltv-autorecord (https://forums.alliedmods.net/showthread.php?p=993138?p=993138)

ReHLDS version: 3.0.0.567-dev
AMX Mod X 1.8.3-dev+5116
Metamod v1.21p37  2013/05/30

**Comment by s1lentq** [comment]
@fred0r also i can't reproduce that issue using plugin above

**Comment by fred0r** [comment]
@s1lentq Thats strange :/
After i copied the old files back the AMXX-Plugin initiated the Demo-Recording.
Did you try on Linux or Windows ?

**Comment by fred0r** [comment]
my server runs on linux.
i doublechecked everything:
switched back to 'orig server binarys' with the amxmodx-version of hltv: works
copied the rehlds-567-dev: "Invalid rcon challenge from: LOCAL_SERVER_IP:PORT"
installed regame_dll on top of rehlds: Invalid rcon challenge from: LOCAL_SERVER_IP:PORT

:/

**Comment by s1lentq** [comment]
``Did you try on Linux or Windows ?
both

**Comment by fred0r** [comment]
@s1lentq 
Yes - i always copied the whole content of the rehlhs-archive - overwriting the old binarys

**Comment by fred0r** [comment]
i reinstalled everything and i'll report back

**Comment by fred0r** [comment]
i tested on 2 different (linux) machines with a 'clean steam install' and still:
Invalid rcon challenge from: xx.xxx.xx.xx
perhaps the plugin-settings matter - i've:
`autohltv_record 1 // - enables autorecording
autohltv_path "demos/Server-TV" // - it means, that you will have "cstrike/demos/Server-TV-12389034.dem". If you want to put the demos into ct$
//autohltv_path "Server-TV"
autohltv_ignorebots 0 // - ignore bots as real players, it means that plugin will not count them at all (look next cvar). If you have bots, $
autohltv_minplayers 2 // - minimum number of players in game to start recording hltv
autohltv_pass xxxxxx // - the pass to control hltv. Go to the hltv.cfg and find adminpassword there. Now you can change it to this or any o$
// autohltv_recording // 1|0 - automatic cvar, dont touch it if you dont know what you do. You can use it in server monitoring to find wheth$
autohltv_time 0 // 0|1|2, 2 is default. 0 - no timer show as hudmessage. 1 - timer only for hltv. 2 - for all players. This may be usefull t$
autohltv_delay 60.0 // - delay should be equal to delay in hltv.cfg (director.cfg) of HLTV-server configuration file.
`

**Comment by LevShisterov** [comment]
Do you run both hlds and hltv on the same machine?
Do you have any network packet processing that might adjust packets?

**Comment by fred0r** [comment]
The HLTV was running on the same Machine and with the same User as the hlds-session.
I used std. Distros like Debian and Ubuntu. There's no packet adjustment.

**Comment by fred0r** [comment]
version of hlds:
```
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.0.0.567-dev
Build date: 11:08:28 May 21 2017 (1135)
Build from: https://github.com/dreamstalker/rehlds/commit/8276436
```
script to start hltv:
```
#/bin/bash
BINARYPATH="$(dirname "${0}")"
cd "${BINARYPATH}"
LIBRARYPATH="$(pwd)"
export LD_LIBRARY_PATH="${LIBRARYPATH}::${LD_LIBRARY_PATH}"
./hltv $@
```

startup of hltv:
```
Console initialized.
FileSystem initialized.
Network initialized.
Master module initialized.
Server module initialized.
World module initialized.
Demo client initialized.
Executing file hltv.cfg.
hltv.cfg loaded.
Proxy module initialized.
Type 'help' for a list of commands.
Challenging 192.168.0.200:27015 (1/3).
Get challenge (HASHEDCDKEY)
Connecting to 192.168.0.200:27015 (1/3).
>* Privileges set

>
BUILD 1135 SERVER (0 CRC)
Server # 1

Added 795 resources.
Received baseline with 95 entities.
Error: /raid/server/cs/cstrike/dlls/director.so: cannot open shared object file: No such file or directory
Couldn't open config file director.cfg.
Director module initialized.
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 10
dlopen failed trying to load:
/home/cs/.steam/sdk32/libsteam.so
with error:
/home/cs/.steam/sdk32/libsteam.so: cannot open shared object file: No such file or directory
Executing rcon "say [HLTV] Starting record... " from 192.168.0.200:37441.
#Cstrike_Chat_AllSpec
Invalid rcon challenge from: 192.168.0.200:50630
>"autohltv_recording" changed to "1"

```
hltv.cfg:
```
// set HLTV proxy name as shown in score board
name "HLTV Proxy""

// set HLTV name, how it should appear in game server browsers
hostname "Proxy"

//HLTV player slots - the number of people who can connect to HLTV
maxclients "10"

// set offline info text clients will see as reject reason if HLTV isn't broadcasting yet
offlinetext "Sorry, game is delayed. Please try again later."

// Delay between actual server play and HLTV broadcast
delay 60.0

// allow 3.5 KByte/sec as client rate. This is good a value
// for internet broadcasts. On LAN you may set this value to 10000
maxrate 50000
updaterate 90

// log HLTV console in proxy.log
logfile 1

// local chatting for HLTV spectators enabled
chatmode 1

// if the server the HLTV is connecting to has a password, enter it here
serverpassword   ""

// proxy's adim password for rcon, commentator etc.
adminpassword moep123

// show message for 5 seconds each 60 seconds in center of X axis (-1) and
// above help text bar (0.85). Color given as hexadecimal RGBA .
loopcmd 1 60 localmsg "SERVER" 5 -1 0.85 FFA000FF

// hltv.tga will be shown instead of the default HLTV logo in spectator GUI
// bannerfile "hltv.tga"

// these commands will be executed on connecting spectator client and may be used
// to adjust settings for HLTV (for example voice parameters)
signoncommands "voice_scale 2; voice_overdrive 16; volume 0.5; echo Voice adjusted for HLTV"

echo hltv.cfg loaded.

//Game Server Connection Info - enter the game server ip and port in the following
// format by adding a new line below the example shown. Then start your HLTV server

connect 192.168.0.200
nomaster 1
blockvoice 1
// slowmotion 1.0

// Netsettings
maxqueries 1500
publicgame 1
```


status in hltv:
```
-- HLTV Status ---
Online 41:04, FPS 93.0, Version 1135 (Linux)
Local IP 127.0.1.1:27020, Network In 4.3, Out 0.7, Loss 0.00
Local Slots 10, Spectators 0 (max 0), Proxies 0
Total Slots 10, Spectators 0 (max 0), Proxies 1
Connected to Game Server 192.168.0.200:27015, Delay 60
Server Name "Test"
Game Time 01:99:48, Mod "cstrike", Map "de_dust2.bsp", Players 8
```

**Comment by fred0r** [comment]
I now even symlinked these *steam*.so's hlds and hltv complained about, but no luck.
Any Ideas ?

**Comment by fred0r** [comment]
i installed my servers via:
```
./steamcmd.sh +login $myREALuser +force_install_dir $PATH +app_update "90 -beta beta" +app_set_config 90 mod cstrike validate +quit
```

**Comment by xomixo** [comment]
proxy.so issue. put pure .so check again ...

**Comment by fred0r** [comment]
@xomixo: where to get this 'pure.so'.
I dont compile by myself - i downloaded from that url from the github-page:
http://nexus.rehlds.org/nexus/content/repositories/rehlds-dev/rehlds/rehlds/
Inside these Archives there's only one sort of binary.

**Comment by fred0r** [comment]
@xomixo: WOW - THANK YOU !
i now updated my default downloaded cstrike with everything BUT the the proxy.so:
It works now :D

**Comment by xomixo** [comment]
著HLTV proxy.so (pure)

```
rcon hltv signal
Online 04:05, FPS 13994.1, Version 6153 (Linux)
rcon hltv signal
Online 04:12, FPS 10855.8, Version 6153 (Linux)
rcon hltv signal
Online 04:12, FPS 8516.3, Version 6153 (Linux)

Executing rcon "signal" from IPv4:27890.
Online 04:05, FPS 13994.1, Version 6153 (Linux)
Executing rcon "signal" from IPv4:21785.
Online 04:12, FPS 10855.8, Version 6153 (Linux)
Executing rcon "signal" from IPv4:29338.
Online 04:12, FPS 8516.3, Version 6153 (Linux)
```
rehlds/HLTV/Proxy/

```
hltv signal
�
Online 00:13, FPS 12622.8, Version 1159 (Linux)
hltv signal
hltv signal

Executing rcon "signal" from IPv4:49781.
Online 00:13, FPS 12622.8, Version 1159 (Linux)
Invalid rcon challenge from: IPv4:61643
Invalid rcon challenge from: IPv4:22726
```

**Comment by s1lentq** [comment]
please let me know if still the issue persists

**Comment by fred0r** [comment]
I used the latest version (3.0.0.570-dev) and now the Demos are created.
Thank you !

**Comment by fred0r** [comment]
It looks like it still behaves a little different.
Since Ages i'm using HLSW to manage the server and the reHLTV-Instance doesnt show the configured Slots and the current delay during viewing the current players on the server.
The 'orig'HLTV also shows these Parameters as 'player-info'
