### ISSUE TITLE
voice packet unknown command 6

### ISSUE THREAD

**Issue by darth19** [dreamstalker/rehlds#481]
a guy that play in my server have this problem when use +voicerecord

my server have rehlds, reunion and voicetranscoder rc2

**Comment by In-line** [comment]
I think it doesn't refer to ReHLDS, but vtc author (@WPMGPRoSToTeMa) can help you.

https://cs.rin.ru/forum/viewtopic.php?f=10&t=63814

**Comment by darth19** [comment]
i installed "Revoice" and problem fixed, but now steams cant heard nosteams

seem an steam update happened and fucked the cs voice

**Comment by WPMGPRoSToTeMa** [comment]
Update VTC to the last version.

**Comment by In-line** [comment]
Closing as non active
