### ISSUE TITLE
Bug with func_rotating

### ISSUE THREAD

**Issue by fant1kua** [dreamstalker/rehlds#482]
There are 2 bugs that are connected between with func_rotating
1. There is no sound when was spawned.
2. After restart, there will be 2 sound rotation
Launch to the map and make sure that there is no sound. We make a restart round sound will appear and try to turn off its button and one sound remains
It is worth noting that if we add to the spawnflag `SF_BRUSH_ACCDCC 16` the 2nd bug will not be

**Comment by justgo97** [comment]
this issue isn't related to rehlds, its regamedll responsible for this stuff, go here https://github.com/s1lentq/ReGameDLL_CS
