### ISSUE TITLE
Non-sprite set to glow! Fix

### ISSUE THREAD

**Issue by ivani6651** [dreamstalker/rehlds#483]
Can fix spam in console with message 'Non-sprite set to glow!' on some maps for reHLDS with w/o plugins.

**Comment by theAsmodai** [comment]
Can you give link to one of these maps?

**Comment by ivani6651** [comment]
http://www.17buddies.net/17b2/View/Map/19196/zm_dust_winter.html

**Comment by simeonniko** [comment]
It's seems that valve tried to do something in 2011 about that spam :D
https://forums.alliedmods.net/showpost.php?p=1564016&postcount=20

**Comment by krangm** [comment]
thats entity problem. this msg appears when non-sprite entity has glow `"rendermode" "5"`.
you can fix it by editing entities of bugged map. left `"rendermode" "5"` only on sprites, other glows might be changed to `"rendermode" "1"`.
tho will be cool if this fix will be incremented to ReHLDS.

**Comment by ivani6651** [comment]
@theAsmodai Will you be able to fix this problem?

**Comment by WPMGPRoSToTeMa** [comment]
We can put this into `SV_WriteEntitiesToClient`, something like:
```C++
if (entityState.rendermode == kRenderGlow
	&& g_psv.models[entityState.modelindex]->type != mod_sprite)
	entityState.rendermode = kRenderNormal;
```
But there is also a message that we can't control - `TE_SPRAY`.

**Comment by ivani6651** [comment]
It will be great if a solution to this problem is found.

**Comment by ivani6651** [comment]
https://forums.alliedmods.net/showthread.php?t=115739

Will you do this thing in order not to use a plug-in plugin on the console. This spam is on certain zombie maps.
