### ISSUE TITLE
Spray sound bug on de_train for reHLDS

### ISSUE THREAD

**Issue by ivani6651** [dreamstalker/rehlds#484]
Can fix spray sound bug on map de_train and de_train32 for reHLDS with w/o plugins.
https://www.youtube.com/watch?v=gj-fFqi9oAo&feature=youtu.be

**Comment by In-line** [comment]
If doesn't refer to ReHLDS so please close issue and open one in ReGameDLL

**Comment by In-line** [comment]
Proposed fix: https://github.com/s1lentq/ReGameDLL_CS/pull/167
