### ISSUE TITLE
Playernames are cut / not shown completly in 1st Person

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#495]
Playernames are cut at ~18 charaters while viewing them in 1st person

**Comment by In-line** [comment]
Client side bug

**Comment by fred0r** [comment]
Hmm - i really ?
I'm pretty sure they were shown completely bore using reHLDS.
I need to switch back to test and i'll report back.

**Comment by WPMGPRoSToTeMa** [comment]
What do you mean? Can you attach a screenshot?

**Comment by fred0r** [comment]
i'll put one here later today.

**Comment by fred0r** [comment]
1. pic's playername is 'XUUUUUUEEEEEEQQQQQQQQEEEEEEEEEE'
2. pic's playername is 'GKAll1ance | [Mass] Wick'

https://imgur.com/a/iDbWW

**Comment by fred0r** [comment]
btw:
why are the ct's highlighted in that screenshot - i had 'mp_playerid 1' ?!

**Comment by fred0r** [comment]
i rechecked and its really only with reHLDS:
'long' Playernames are cut and by that the current health isnt shown either.
The 'Clientside Bug'-Label isnt right.

**Comment by WPMGPRoSToTeMa** [comment]
Hmm, it is ok for me.

**Comment by fred0r** [comment]
Perhaps this is also 'glibc-related' like the fix for #476

**Comment by fred0r** [comment]
Another thing which might be different:
I'm playing CS 1.6 under native Linux-Steam.

**Comment by fred0r** [comment]
Hmm . ..  it seems that this Bugs does even exist when using the original Linux CSgold-Server and the native Linux-Steam CS 1.6 Client. So its not caused by reHLDS.

**Comment by fred0r** [comment]
Since it works on Windows and the Problems only exists while using a 'native Linux-Steam', i'll close this.
So its really a 'cientside bug' :/
