### ISSUE TITLE
ReHLDS or new version of hlds

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#497]
Which is better the new recently released hlds or rehlds

**Comment by IgnacioFDM** [comment]
ReHLDS

**Comment by Phantomsq** [comment]
ReHLDS

**Comment by fred0r** [comment]
You still need to upgrade to the 'recently released hlds' before installing the latest reHLDS over it.
With that 'recently released hlds' comes also some updates for cstrike/dlls and cstrike/cl_dlls which aren't covered by reHLDS.
