### ISSUE TITLE
Failed GCC 6 compile

### ISSUE THREAD

**Issue by neygomon** [dreamstalker/rehlds#498]
Hi.
Я хотел скомпилировать rehlds с GCC 6, но компиляция фейлится почти в самом начале.
Вводные данные:
```
# gcc --version
gcc (Debian 6.3.0-18) 6.3.0 20170516
```
```# javac -version
javac 1.8.0_131
```
`git clone --recursive https://github.com/dreamstalker/rehlds`
`./gradlew --max-workers=1 -PuseGcc clean buildFixes`

В аттаче output.txt с включенным стектрейсом:
`./gradlew --max-workers=1 -PuseGcc clean buildFixes --stacktrace`

[output.txt](https://github.com/dreamstalker/rehlds/files/1144350/output.txt)

**Comment by In-line** [comment]
I think this PR is a reason #492 for this issue. It is interesting that GCC 6.2 builds ReHLDS without problem.
I think we should revert #492 or explicitly add `-msse=X` option.

**Comment by neygomon** [comment]
ohh... Я забыл указать про то, что с опцией -PuseGcc gradle ищет все равно ICC компилятор:
`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rehlds/HLTV/Console:compileHltvExecutableHltvHltv_common'.
> Could not find C++ compiler '/opt/intel/bin/icpc' in system path.

* Try:
Run with --info or --debug option to get more log output.`

**Comment by In-line** [comment]
@neygomon close issue

**Comment by s1lentq** [comment]
Fixed by commit a444ce0
