### ISSUE TITLE
rcon say problem

### ISSUE THREAD

**Issue by darth19** [dreamstalker/rehlds#499]
for example:

rcon say "hello" 

and only "s" appear in screen

https://s.put.re/qFh55xS.png

someone know how fix this ?

**Comment by voed** [comment]
https://github.com/dreamstalker/rehlds/issues/487

**Comment by darth19** [comment]
so i should update rehlds in my server?

**Comment by WPMGPRoSToTeMa** [comment]
Yup.

**Comment by In-line** [comment]
Closing as non active.
