### ISSUE TITLE
windows, fps stuck at 64

### ISSUE THREAD

**Issue by justgo97** [dreamstalker/rehlds#501]
so today i tried rehlds on my windows server and the fps is stuck at 64 i tried to change sys_ticrate to different values but no luck, if i set sys_ticrate to less then 64 it i will become 32 o.O.

normal hlds don't have this problem.

edit: problem happens to 32bit win 7 system too.

**Comment by voed** [comment]
Try to run any music/video player like Windows Media, it should help

**Comment by justgo97** [comment]
why ? the normal hlds doesn't need such a thing.

**Comment by voed** [comment]
Just test it. If this helps, contributors will easilly fix your problem i am sure

**Comment by justgo97** [comment]
yeah i tested it and it fixed the problem.

**Comment by voed** [comment]
Try this **but i am not response with any result etc**
run regedit, go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\PriorityControl
Create new DWORD parameter with name 'IRQ8Priority' and set its value to 1. Then reboot

![image](https://user-images.githubusercontent.com/10352360/28241882-598ac60c-69a6-11e7-991f-349026273fca.png)

**Comment by In-line** [comment]
Closing as non active.

**Comment by stambeto2006** [comment]
Any ideas with fps, nothing helps, I tried and it stands at 64 fps? #799
