### ISSUE TITLE
Chat issuE

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#502]
The chat issue that occurs in new update , does anyone knows its solution?
I dont know when and how it happened i myself didnt updated sv and I'm using rehlds but still the chat issue is there..

**Comment by txdv** [comment]
Wat exactly is the issue?

**Comment by WhiteFang1319** [comment]
Whenever rcon say command is used, the message doesn't appear and only the letter "s" can be seen in chat..

**Comment by In-line** [comment]
Don't use custom chat plugins or send pm to the author, so he might add cs beta support.

**Comment by WhiteFang1319** [comment]
I updated Rehlds today and it was fixed for me.
