### ISSUE TITLE
[feature request] Ingame speex voice with no delay

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#503]
comparing mumble/teamspeak to 'ingame voice' there's always a 'delay' while using 'ingame voice'.
it would be nice if that 'ingame voice' would be possible without that '0,5sec delay'.

**Comment by WPMGPRoSToTeMa** [comment]
In GoldSrc delay is 300 ms.

**Comment by fred0r** [comment]
ok: pls remove the 200msec delay

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r 
1. It is in the client.
2. It is needed for normal working of voice chat, but can be reduced.

**Comment by fred0r** [comment]
about 2.
Whats 'normal working of voice chat' and it can be reduced - pls yes.

**Comment by Chuvi-w** [comment]
Delay about 0.2s is on client side. It can't be reusced from server side. Only client modifications can do this.

**Comment by fred0r** [comment]
:(
