### ISSUE TITLE
resocket_amxx.dll not working?

### ISSUE THREAD

**Issue by q309418863** [dreamstalker/rehlds#509]
Cannot load properly in ReHLDS?
![fail](https://user-images.githubusercontent.com/13830499/28743603-171ee61a-7480-11e7-8f0f-01fd29993f4b.png)

How can I make it work?

[resocket_amxx.zip](https://github.com/dreamstalker/rehlds/files/1184818/resocket_amxx.zip)

**Comment by In-line** [comment]
PM resocket author

**Comment by In-line** [comment]
Closing as non active
