### ISSUE TITLE
SV_HullForBsp error

### ISSUE THREAD

**Issue by TheRedShoko** [dreamstalker/rehlds#510]
I didn't have this problem before updating to the latest version of ReHLDS. The error appears from hats plugin after setting the model of the hat. The model is being set using engine.

FATAL ERROR (shutting down): SV_HullForBsp: Hit a worldspawn with no model (models/csbgjb/hats.mdl)
Segmentation fault

**Comment by In-line** [comment]
I think it's plugin issue.

**Comment by TheRedShoko** [comment]
As I said the problem appeared after updating ReHLDS, I'm using the plugin on other servers too and there is no such a problem. The servers are using older version of ReHLDS.

**Comment by In-line** [comment]
You should mention from what version did you update.
