### ISSUE TITLE
[feature request] sv_alltalk 1: No 'Speeching-Sprites' shown

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#511]
It would be nice if during `sv_alltalk 1`is enabled, there are no 'speeching sprites' shown above players who actually talk.

**Comment by In-line** [comment]
It's client side, we can't change or block that sprite

**Comment by IgnacioFDM** [comment]
As a hack I think you could send TE_KILLPLAYERATTACHMENTS, it will however interact with other stuff if you don't take that in consideration. This is obviously not something you would do in ReHLDS however (too hacky to be an actual feature), but more as a amxmodx plugin.
