### ISSUE TITLE
ReHLTV demo not storing

### ISSUE THREAD

**Issue by abhishekdeshkar** [dreamstalker/rehlds#515]
Hi,

I tried recordd test.dem to store HLTV demo but it doesn't store HLTV demo in the cstrike folder. Why ?

**Comment by fred0r** [comment]
Did you update to the latest reHLDS ?

**Comment by abhishekdeshkar** [comment]
@fred0r  : Yes. I'm using latest ReHLDS on Windows.

**Comment by fred0r** [comment]
Hmm - ok. I had the same problems but updating to the latest reHLDS worked for me. Are you using amxmod on that server instance ? I'm using amxmod 1.8.3-5120 and had problem after updating to a higher amxmod-version.

**Comment by abhishekdeshkar** [comment]
@fred0r : I'm not even using new AMX. I have been using ReAMX !

**Comment by abhishekdeshkar** [comment]
@fred0r : Are sure this problem is with the version of AMX?

**Comment by abhishekdeshkar** [comment]
@dreamstalker : Could you suggest me some solution ?

**Comment by voed** [comment]
Provide more info.

**Comment by abhishekdeshkar** [comment]
@voed  : More info ? Server is running on windows server 2012. Sometimes on Windows 10. Running with latest ReHLDS + latest ReAMX. What else you want to know ?

**Comment by In-line** [comment]
Try it with original HLTV. If it didn't work then probably ploblem is on your side

**Comment by abhishekdeshkar** [comment]
@In-line  : Original HLTV is working fine but the problem is original HLTV lags alot but it does save demo recording file.

**Comment by xomixo** [comment]
@abhishekdeshkar 3.3.0.589-dev

**Comment by In-line** [comment]
Closing as non active.
