### ISSUE TITLE
Server falling too far with GunGame AMXX

### ISSUE THREAD

**Issue by gui1porpis** [dreamstalker/rehlds#516]
I have 16 servers (8 cstrike and 8 czero) and only the gungame mode (cs and cz) is falling too much, it does not work, it does not take much time online and it already falls. Nothing is registered in sys_error.log and always the last thing that is registered is:
L 08/19/2017 - 19:01:06: "Sweet<5><STEAM_1:0:1558934993><>" connected, address "201.3.109.105:27005"
[usuario 1] autenticacao do cliente!

I've tried adding REUNION (if it solved something), disable some modules anyway, the server crashes.

**Comment by In-line** [comment]
I very doubt that this is REHLDS problem

**Comment by simeonniko** [comment]
You can try with ReGunGame http://dev-cs.ru/resources/90/

**Comment by gui1porpis** [comment]
It seems that this ReGunGame has been completely rewritten and is in Russian, the problem is that I use GunGame AMXX with database for the Web Rank that I have, so I was wondering if there is another option?

**Comment by In-line** [comment]
If you send debug.log or/and crash dump maybe we can identify your problem

**Comment by gui1porpis** [comment]
Is it debug.log and debug.cmds?
[debug.zip](https://github.com/dreamstalker/rehlds/files/1239065/debug.zip)

I left the server running with **ReGunGame**, but it still crashed, and the last record in qconsole.log is someone connecting to the server. Before starting to use reHLDS the server will not crash.

**Comment by In-line** [comment]
Add -debug to the launch options.

**Comment by gui1porpis** [comment]
**Start Command:** nice -n 0 ./hlds_run -game cstrike +ip 177.54.156.120 +port 27004 +maxplayers 24 +sys_ticrate 100 -pingboost 0 +map gg_woody +servercfgfile server.cfg -secure -condebug -debug -autoupdate &

Is correct?

Here is the debug.log already with -debug working.  [debug.zip](https://github.com/dreamstalker/rehlds/files/1245749/debug.zip)

**Comment by In-line** [comment]
It's hard to get the reason, [SO](https://stackoverflow.com/questions/10000335/how-to-use-debug-version-of-libc) suggests that installing `libc` debug version should help to get function names in backtrace.
`sudo apt-get install libc6-dbg:i386 # for debian based distros`.

In any case you should send crash dump (aka core dump), cause more experienced developers can look in it and understand where is the problem.

**Comment by LevShisterov** [comment]
At first he just need to check core dump file size - should be more than 150mb (usually, could be a bit less).
If smaller, adjust limits.

**Comment by gui1porpis** [comment]
In case it would be the core.PID? (PID = any numbering)
[core_and_debug.zip](https://github.com/dreamstalker/rehlds/files/1246856/core_and_debug.zip)


It's that I'm sort of lazy about this and do not understand much about crash or similar dump, just know that the server bug breaks is 2 ~ 3 hours at most, the longest times would be the times that there is no movement on the server. I had it say that ReGunGame had not resolved, but it took a little longer to close the server, except that you can not use it in Russian. As soon as Brazilians understand their own English language, imagine the Russian language.

**Comment by LevShisterov** [comment]
`ulimit -c unlimited && ./hlds_run -debug ...`

**Comment by gui1porpis** [comment]
I can not understand this debug much, what do you think?
[debug.zip](https://github.com/dreamstalker/rehlds/files/1253760/debug.zip)

**Comment by In-line** [comment]
Very interesting, it seems that amxmodx mysql module is reason for the one of the segfaults. I think normally amxmodx should only emit native error. In any case, please send resent error_*.log files from amxmodx logs folder.

**Comment by gui1porpis** [comment]
There is no error log in amxmodx, I use four plugin that works with MySQL, one of it's chat sql logs (I rode with it disabled, more so anyway bug)
Two are from AMXBans (Core & Main) and the other is the GunGame AMXX.

**Comment by In-line** [comment]
Try to update amxmodx to latest 1.8.3 version

**Comment by gui1porpis** [comment]
12:50:05 AMX Mod X 1.8.3-dev+5132 (http://www.amxmodx.org)
         Authors:
         <TAB>David "BAILOPAN" Anderson, Pavol "PM OnoTo" Marko
         <TAB>Felix "SniperBeamer" Geyer, Jonny "Got His Gun" Bergstrom
         <TAB>Lukasz "SidLuke" Wlasinski, Christian "Basic-Master" Hammacher
         <TAB>Borja "faluco" Ferrer, Scott "DS" Ehlert
         Compiled: Aug  7 2017 14:43:47
         Built from: https://github.com/alliedmodders/amxmodx/commit/ba58cb0
         Build ID: 5132:ba58cb0
         Core mode: JIT+ASM32

**Comment by PM32** [comment]
Are you using a modified version of GunGame? I wanna see how this addon interacts with SQLX

**Comment by gui1porpis** [comment]
I'm using an official version of _XxAvalanchexX_, but with SQL, for web stats, I've tried using this **ReGunGame**, but it's in Russian and it does not have SQL support. I'm leaving the plugin attached.
[gungame.zip](https://github.com/dreamstalker/rehlds/files/1254012/gungame.zip)


Note: My other servers use the same base addon, with amxbans and chat logs, it only changes one or the other, but they do not close as much as this GunGame, even SuperHero that works with SQL does not close that much.

**Comment by WPMGPRoSToTeMa** [comment]
Looks like it is static linking problem, but I'm not sure.

**Comment by WPMGPRoSToTeMa** [comment]
Can you upload your hlds_linux, engine_i486.so, metamod.so and amxmodx_*.so?

**Comment by gui1porpis** [comment]
Sorry for the delay, I spent a few days away.
[gungame_cs4.cristalfrios.zip](https://github.com/dreamstalker/rehlds/files/1290146/gungame_cs4.cristalfrios.zip)

**Comment by WPMGPRoSToTeMa** [comment]
[SafeMetamodAmxmodx.zip](https://github.com/dreamstalker/rehlds/files/1290638/SafeMetamodAmxmodx.zip)
Download launcher and engine from https://github.com/dreamstalker/rehlds/pull/520.

**Comment by gui1porpis** [comment]
Just a question, will I have to use the files that are attached in your last post and update the reHLDS or only the amxmodx and metamod that you left attachment solve?

**Comment by WPMGPRoSToTeMa** [comment]
@gui1porpis you need do both: update rehlds engine and launcher and replace metamod&amxmodx with attached.

**Comment by gui1porpis** [comment]
The last one is final build 592, but I ended up finding one that you were testing for final build 595, which one should I enter?

**Comment by WPMGPRoSToTeMa** [comment]
@gui1porpis use 595 now.

**Comment by gui1porpis** [comment]
I followed his advice, but still I still have problems with mysql_amxx, I ran my server with GunGame without SQL and it worked normally, I'm going to leave my server running with the same internal GunGame Stats and use the gameME as the same Web Rank.

I'll leave the debug attached, [debug.zip](https://github.com/dreamstalker/rehlds/files/1307983/debug.zip).

Thank you for your help.

**Comment by xomixo** [comment]
revert back to 3.3.0.589-dev.  #513 need test.

**Comment by gui1porpis** [comment]
I was using version 3.3.0.589-dev already. I removed the MySQL from the GunGame AMXX stopped it from falling, further forward I might go back and use it.

**Comment by In-line** [comment]
Your issue doesn't refer to ReHLDS, I suggest you to report about this matter to AMX Mod X devs.

**Comment by di57inct** [comment]
Why is this stupid thread still going?

**Comment by In-line** [comment]
Closing as non active.
