### ISSUE TITLE
SV_InitBoxHull missing usage of constant

### ISSUE THREAD

**Issue by Sh1ft0x0EF** [dreamstalker/rehlds#517]
https://github.com/dreamstalker/rehlds/blob/3d4e4ae8e893f32943bb78a8fb058fa496a75cb5/rehlds/engine/world.cpp#L99

-1 should be CONTENTS_EMPTY

**Comment by theAsmodai** [comment]
Check me please
https://github.com/dreamstalker/rehlds/pull/519
