### ISSUE TITLE
Crashes: corrupted double-linked list & double free or corruption

### ISSUE THREAD

**Issue by aron9forever** [dreamstalker/rehlds#522]
I've been having these crashes since installing reHLDS. They happen pretty often (every 1-2 days) and always happen during mapchange, from what I've noticed in SV_SpawnServer. I am unsure whether this is really a reHLDS issue however I don't really know where else to ask.

As far as I know, all the components are fine and compatible. Please correct me if I'm wrong. I am very picky with plugins so there aren't many, considering it's a jailbreak server. 
I used to have reGameDLL as well, but reverted to stock after the crashes started. 

Below are some crash dumps:
https://pastebin.com/UFcw1b4q (after removing reGameDLL)
https://pastebin.com/L90DHP7K (before removing reGameDLL)
https://pastebin.com/zfdZNxge (before removing reGameDLL)
there are more if needed, it happens quire often

Here are some informations about the server:
**version**
`Protocol version 48`
`Exe version 1.1.2.7/Stdio (cstrike)`
`ReHLDS version: 3.3.0.592-dev`
`Build date: 11:22:29 Aug 24 2017 (1230)`
`Build from: https://github.com/dreamstalker/rehlds/commit/4246a44`
**meta version**
`Metamod v1.21p37 2013/05/30 (5:13)`
`Patch: Metamod-P (mm-p) v37`
`compiled: May 30 2013, 11:41:16 EET (optimized)`
**amxx version**
`AMX Mod X 1.8.2 (http://www.amxmodx.org)`
`Compiled: Feb 14 2013, 00:55:09`
`Build ID: 1.8.2 61:2ae84f7c0a97`
`Core mode: JIT+ASM32`
**meta list**
`descriptionstat pend file verssrcload unlod`
`[ 1] AMX Mod X RUN- amxmodx_mm_i386. v1.8.2 iniStart ANY `
`[ 2] Reunion RUN- reunion_mm_i386. v0.1.75iniStart Never`
`[ 3] ReAuthCheckRUN- reauthcheck_mm_i v0.1.6 iniStart Never`
`[ 4] VoiceTranscoder RUN- VoiceTranscoder. v2017RC3 iniANYANY `
`[ 5] Fun RUN- fun_amxx_i386.so v1.8.2 pl1ANYANY `
`[ 6] CStrike RUN- cstrike_amxx_i38 v1.8.2 pl1ANYANY `
`[ 7] CSX RUN- csx_amxx_i386.so v1.8.2 pl1ANYANY `
`[ 8] FakeMetaRUN- fakemeta_amxx_i3 v1.8.2 pl1ANYANY `
`[ 9] Engine RUN- engine_amxx_i386 v1.8.2 pl1ANYANY `
`[10] Ham Sandwich RUN- hamsandwich_amxx v1.8.2 pl1ANYANY `
`[11] MySQRUN- mysql_amxx_i386. v1.8.2 pl1ANYANY `
`11 plugins, 11 running`
**amxx plugins**
`name version authorfile status`
`[ 1] r4ge Server Guard - li 3.5Carnaciorr4ge-server-gua running `
`[ 2] B-Zone Gag 1.0Carnaciorbz_gag.amxxrunning `
`[ 3] Anti Flood 1.8.2 AMXX Dev Team antiflood.amxxrunning `
`[ 4] Advanced Bans 0.8.1 Exolent advanced_bans.a running `
`[ 5] Map Spawns Editor 1.0.16iG_os Map_Spawns_Edit running `
`[ 6] JailBreak Jail Open AP 2.0Carnaciorjail_open_api.a running `
`[ 7] [CS] Teams API 1.2WiLS cs_teams_api.am running `
`[ 8] Admin Base (SQL) 1.8.2 AMXX Dev Team admin_sql.amxxrunning `
`[ 9] Admin Commands 1.8.2 AMXX Dev Team admincmd.amxx running `
`[ 10] Admin Help 1.8.2 AMXX Dev Team adminhelp.amxxrunning `
`[ 11] Menus Front-End1.8.2 AMXX Dev Team menufront.amxxrunning `
`[ 12] Commands Menu 1.8.2 AMXX Dev Team cmdmenu.amxx running `
`[ 13] Players Menu1.8.2 AMXX Dev Team plmenu.amxxrunning `
`[ 14] Maps Menu1.8.2 AMXX Dev Team mapsmenu.amxx running `
`[ 15] Admin Chat 1.8.2 AMXX Dev Team adminchat.amxxrunning `
`[ 16] Admin Votes 1.8.2 AMXX Dev Team adminvote.amxxrunning `
`[ 17] NextMap 1.8.2 AMXX Dev Team nextmap.amxx running `
`[ 18] Nextmap Chooser1.8.2 AMXX Dev Team mapchooser.amxx running `
`[ 19] TimeLeft 1.8.2 AMXX Dev Team timeleft.amxx running `
`[ 20] JailBreak B-Zone 6.9Carnaciorjailbreak_bz.am debug `
`[ 21] AMX Super4.2 Nospee Bmann_420amx_super.amxxrunning `
`[ 22] Show IP 1.0$uicid3 amx_showip.amxx running `
`[ 23] Ultimele Harti 1.0M@$t3r_@dy last_maps.amxxrunning `
`[ 24] Last IP 1.0Alka lastip.amxxrunning `
`[ 25] Private Chat[Room]1.0Alka private_chat.am running `
`[ 26] ULTIMATE WHO1.1P.Of.Pw ultimate_who.am running `
`[ 27] Glow Menuv1.2 Carnaciorglow_menu.amxxrunning `
`[ 28] Reset Score 1.0Silenttt resetscore.amxx running `
`[ 29] Loading Sound 2.0TiruLipe loadingsound.am running `
`[ 30] Restart 2.0Alka SayRestart.amxx running `
`[ 31] FakeFull Original 1.7.6 JTP10181/Freecod fakefull_origin running `
`[ 32] Parasuta 1.4b cyby amx_parachute.a running `
`[ 33] JailMod-Ball3.0ButterZ ball.amxx running `
`[ 34] Real Nade Drops0.4VENrealnadedrops.a running `
`[ 35] Vehicle Real Killer 1.1xPaw VehicleRealKill running `
`35 plugins, 35 running`

The server is running on 
`CentOS release 6.9 (Final)`
`2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

Please let me know what further steps to take to debug and I will gladly post the results.
Please also keep in mind that this is a production server and therefore some extreme tests can't be done. I can not reproduce the crashes so it's a waiting game.

**Comment by WPMGPRoSToTeMa** [comment]
You need last ReHLDS build (both engine and launcher), patched metamod (or metamod-r) and patched amxmodx. Please upload your amxmodx and metamod here.

**Comment by aron9forever** [comment]
Hi, many thanks for your reply. The metamod version seems to be the same as the one you posted in https://github.com/dreamstalker/rehlds/issues/516#issuecomment-328349662 as it is the same size down to the last byte.
The amxx is the default 1.8.2 downloaded from amxmodx website. I had reamxmodx before, but it was crashing with it as well, so I reverted to 1.8.2 (I asked a friend with a top5 server about his configuration, and he has the same amxmodx version).

Is there any point in uploading the binaries or should I just install the latest reHLDS? (I am only one version behind the last PR regarding safe DLL loading)

**Comment by gui1porpis** [comment]
Use amxx 1.8.3-dev last build (http://www.amxmodx.org/snapshots.php)
Because?!: https://github.com/alliedmodders/amxmodx/pull/417

**Comment by aron9forever** [comment]
I have updated to the latest amxmodx dev version, I will keep you updated with whether it crashes or not. It stayed on for a while longer now but eventually crashed again today so I took the opportunity to update amxmodx.

Does it matter if some plugins are compiled under older versions such as 1.8.1 and 1.8.2 ?

**Comment by gui1porpis** [comment]
Some may even work, but others will work with errors or not.

**Comment by aron9forever** [comment]
Okay, so the server crashed again today, this time with no more output. The process just died and the last messages were from fakefull_original noting that the bots are being kicked for changelevel. 

I reverted to 589-dev as suggested to another issue here https://github.com/dreamstalker/rehlds/issues/516#issuecomment-330508267

I will keep you posted

**Comment by aron9forever** [comment]
Crashes continue after reverting to 589-dev and updating to amxmodx latest dev
https://pastebin.com/6GFP4GyD

**Comment by WPMGPRoSToTeMa** [comment]
> Okay, so the server crashed again today, this time with no more output.

Did you use patched amxmodx?

**Comment by RauliTop** [comment]
> Crashes continue after reverting to 589-dev and updating to amxmodx latest dev
https://pastebin.com/6GFP4GyD

Crash not related to ReHLDS or regamedll. I have similar crashes on a jailbreak server
Probably caused by Vehicle Real Killer

**Comment by aron9forever** [comment]
@RauliTop I very much doubt that, since it's a short and well written plugin
If it's any amxmodx plugin then it's definitely the jailbreak mod which I based on jbextreme (which is already really old and badly coded with today's standards) 

@WPMGPRoSToTeMa sorry bro, I missed your reply. I'm not sure what you mean by patched amxmodx, I am now using 589-dev downloaded from amxmodx website. If other components are necessary for reHLDS to run properly I'd respectfully ask you to include that in the readme, it's hard to find proper documentation in English.

I am however beginning to think more and more that it has nothing to do with reHLDS, but I have no idea how to debug further, is it just normal behavior for heavy load (fat mod) and heavy usage(many players a day) HLDS to eventually crash? Should I just set an auto-restart every night at some hour when it's empty and hope that will minimise crashes? The only reason I'm annoyed is that the top servers are non stop online and I can't comprehend how that's possible since I've never had a server run more than a week or two without crashing.

**Comment by WPMGPRoSToTeMa** [comment]
> I'm not sure what you mean by patched amxmodx, I am now using 589-dev downloaded from amxmodx website.

Can you upload amxmodx_mm_i386.so here? And metamod too.

**Comment by In-line** [comment]
It's better to set daily restarts in any case.

We can try to use address sanitizers to detect problem or some tool like valgrind.

I think HLDS wasn't designed for long running. In ReHLDS some bugs related to "long run" were fixed and situation is a bit better, but it's still not good idea.

It's not about heavy load or heavy usage, it's about complexity. Large mods have many working parts, testing and writing them is hard. It's nearly impossible to not make mistakes. But you are right. If you use or push software to it's limits, you will certainly increase chance to catch a bug.

**Comment by RauliTop** [comment]
@aron9forever I said you probably it's that plugin because it's the only plugin we have on the two servers. My server it's using HLDS and isn't based on jbextreme.

Try disabling Vehicle Real Killer, my server started to crash like yours after doing an huge update on the server which included adding that plugin...
I can't disable the plugin on my server because it's edited and is necessary with some functions on my jailbreak mod.

**Comment by aron9forever** [comment]
https://forums.alliedmods.net/showthread.php?p=2552213 might be related if not even the cause, please have a look

@WPMGPRoSToTeMa [bins.zip](https://github.com/dreamstalker/rehlds/files/1350514/bins.zip)

@RauliTop if this ends nowhere then I will remove the plugin and let you know if anything changes

@In-line thanks for the reply, I will eventually set it up, the only issue is that I might not be able to do it with the hosting provider so I'd have to do something hacky like write a plugin to quit the server and let auto-restart turn it back on.

**Comment by WPMGPRoSToTeMa** [comment]
@aron9forever 
[bins.zip](https://github.com/dreamstalker/rehlds/files/1354049/bins.zip)

**Comment by aron9forever** [comment]
@WPMGPRoSToTeMa Can you please do this one for amxmodx? It includes the fix for the issue I reported there(last dev version). 
[bin.zip](https://github.com/dreamstalker/rehlds/files/1366547/bin.zip)

**Comment by WPMGPRoSToTeMa** [comment]
@aron9forever [amxmodx_mm_i386.zip](https://github.com/dreamstalker/rehlds/files/1367069/amxmodx_mm_i386.zip).

**Comment by aron9forever** [comment]
@WPMGPRoSToTeMa  I'm really sorry to keep bothering you with this. Would I need another patched version for https://github.com/alliedmodders/amxmodx/pull/464 or can I just use the one from here? https://www.amxmodx.org/snapshots.php

**Comment by WPMGPRoSToTeMa** [comment]
[amxmodx_mm_i386.zip](https://github.com/dreamstalker/rehlds/files/1367227/amxmodx_mm_i386.zip)

**Comment by In-line** [comment]
Closing as non active.
