### ISSUE TITLE
Error Windows XP SP 3

### ISSUE THREAD

**Issue by 81x08** [dreamstalker/rehlds#53]
Hello.
These errors appear after replacing the file swds.dll folder "bugfixed" and "pure".

An error occurred when the server starts:
"The procedure entry point K32GetModuleInformation not be located in the dynamic link library KERNEL32.dll"

Configuration OS:
Windows XP SP 3

**Comment by dreamstalker** [comment]
Fixed binaries:
http://nexus.rehlds.org/nexus/content/repositories/rehlds-snapshots/rehlds/rehlds/0.2-SNAPSHOT/rehlds-0.2-20150713.230110-58.zip

**Comment by xkpx64** [comment]
Thank You- i got the same problemv :)
