### ISSUE TITLE
HLTV and maxplayers / sv_visiblemaxplayers

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#533]
It seems like HLTV is unable to connect to a 'full server'.
For ages i'm running a HLTV and i have the impression that the 'Connect-behavior' changed since using rehlds.

Server runs with 'maxplayers 26' and 'sv_visiblemaxplayers 25' - the overall goal are 24 players + HLTV + the possibility to let a admin join (while the most recent player gets kicked).

So: Did this really change or does it just came to my attention ?
Would it be possible to implement to let 'a proxy' join regardless of the 'sv_visiblemaxplayers' ?

**Comment by spark512** [comment]
Slot reservation have never been an hlds feature, rather an amxx one. Why not simply reserve 2 slots for admins, and give your hltv the appropriate admin flag?
