### ISSUE TITLE
BugfixedHL dll

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#539]
Is it good to use this with rehlds, regamedll_cs, reapi....
https://github.com/LevShisterov/BugfixedHL

**Comment by WPMGPRoSToTeMa** [comment]
How do you want to use it with ReGameDLL_CS?

**Comment by ish12321** [comment]
Like we replace dll,so in regamedll_cs i do same for it.. The respected files..

**Comment by WPMGPRoSToTeMa** [comment]
ReGameDLL_CS replaces gamedll .dll/.so, BugfixedHL replaces them too.

**Comment by LevShisterov** [comment]
@ish12321 if you are running HL server then you can/should use BugfixedHL. If CS then BugfixedHL is not needed. You can't "use" ReGameDLL_CS and BugfixedHL together on the same server.

**Comment by ish12321** [comment]
Is bugfixedhl needed fir a cs client? Will it help their?

**Comment by ish12321** [comment]
there*

**Comment by LevShisterov** [comment]
BugfixedHL is for Half-Life mod. Will it help in Counter-Strike? No.

**Comment by In-line** [comment]
Will you stop creating issue with bad titles? No.
