### ISSUE TITLE
I can not find a function by name - Не получается найти функцию по имени.

### ISSUE THREAD

**Issue by GoDtm666** [dreamstalker/rehlds#540]
I can not find a function by name.
Не получается найти функцию в engine_i486.so по имени.

```
C_DLLEXPORT void GiveFnptrsToDll(enginefuncs_t * pengfuncsFromEngine, globalvars_t * pGlobals)
{
	void * vBuffer;

	lib_t * lib = new lib_t;

	lib_load_info((void *)pGlobals, lib);

	if (lib == NULL)
	{
		printf("Переменная pGlobals не найдена!\n");
		return;
	}

	vBuffer = (void *)lib_find_symbol(lib, "_Z15COM_BuildNumberv");
	
	if (vBuffer == NULL)
	{
		printf("Функция COM_BuildNumber не найдена!\n");
		delete lib;
		return;
	}

	vBuffer = (void *)lib_find_symbol(lib, "host_client");

	if (vBuffer == NULL)
	{
		printf("Переменная host_client не найдена!\n");
		delete lib;
		return;
	}

	vBuffer = (void *)lib_find_symbol(lib, "_Z14MSG_ReadStringv");

	if (vBuffer == NULL)
	{
		printf("Функция MSG_ReadString не найдена!\n");
		delete lib;
		return;
	}

	vBuffer = (void *)lib_find_symbol(lib, "_Z10Con_PrintfPKcz");

	if (vBuffer == NULL)
	{
		printf("Функция Con_Printf не найдена!\n");
		delete lib;
		return;
	}

	vBuffer = (void *)lib_find_symbol(lib, "_Z2vaPcz");

	if (vBuffer == NULL)
	{
		printf("Функция va не найдена!\n");
		delete lib;
		return;
	}
	/* ...... */

	delete lib;

	return;
}
```

Previously, the function found without problems, now does not find.
Раньше функцию находил без проблем, теперь не находит.

Tried to link engine_i486.so and in a plug-in to register.
Пробовал линковать engine_i486.so и в плагине прописывать.

```
extern "C++" 
{
	char *va(char *format, ...);
	char *MSG_ReadString(void);
	char *COM_Parse(char *data);
	void SV_DropClient(client_t *cl, qboolean crash, const char *fmt, ...);
	void Con_Printf(const char *fmt, ...);
	char *SV_GetClientIDString(client_t *client);
}
```

Выводит ошибку не найдена функция в engine_i486.so
Displays an error the function is not found in engine_i486.so

There are source codes of the loader with search of functions: http://rgho.st/8cNK9ylP8
Есть исходники загрузчика с поиском функций: http://rgho.st/8cNK9ylP8

Пробовал настроить version_script.lds
I tried to configure version_script.lds

```
HLDS_ABI_1.0 {
	global: 
		CreateInterface;
		F;
		NET_Sleep_Timeout;
        extern "C" {
           COM_BuildNumber;
        };
		
	local: 
		*;
};
```
и так 
so

```
HLDS_ABI_1.0 {
	global: 
		CreateInterface;
		F;
		NET_Sleep_Timeout;
        extern "C++" {
           COM_BuildNumber;
        };
		
	local: 
		*;
};
```
и так
so

```
HLDS_ABI_1.0 {
	global: 
		CreateInterface;
		F;
		NET_Sleep_Timeout;
		COM_BuildNumber;
	local: 
		*;
};
```

Безрезультатно.
of no effect

Если компилировать без параметра '-Wl,--version-script=../version_script.lds' то все функции находит без проблем.
If you compile without the parameter '-Wl, - version-script = .. / version_script.lds', then all functions are found without problems.

**Comment by LevShisterov** [comment]
You should better try to switch to ReHLDS API.

**Comment by s1lentq** [comment]
Duplicate #538 
You can search for them by the [Elf32](https://gist.github.com/s1lentq/6e8aff31ae6a8ab570b73e5c62ec5cf4#file-memory-cpp-L25), but as said above @LevShisterov better use API

**Comment by zik32** [comment]
Not all functions are in api
just delete the comit

**Comment by zik32** [comment]
https://github.com/dreamstalker/rehlds/commit/cf4a94d8c1ecdbfe6d57e21afc780015a8382693

**Comment by GoDtm666** [comment]
In api, there are no variables and some functions, for example:

netadr_t net_local_adr;
char *MSG_ReadString(void);
qboolean s_com_token_unget;
command_t clcommands[23];
netadr_t net_from;
sizebuf_t net_message;
edict_t *sv_player;
char com_token[COM_TOKEN_LEN];
client_t *host_client;

Maybe it's just better to delete this parameter: '-Wl, - version-script = .. / version_script.lds ??

**Comment by In-line** [comment]
Just add what you lack in the API. 

Commit can be reverted, but it will increase ReHLDS size and possibly disable some optimizations.

**Comment by GoDtm666** [comment]
Output to the API these functions and variables.

extern netadr_t net_local_adr;
extern char *va(char *format, ...);
extern char *MSG_ReadString(void);
extern void Cmd_ExecuteString(char *text, cmd_source_t src);
extern void Cmd_TokenizeString(char *text);
extern void Cbuf_InsertText(char *text);
extern char *COM_Parse(char *data);
extern void SV_DropClient(client_t *cl, qboolean crash, const char *fmt, ...);
extern void Con_Printf(const char *fmt, ...);
extern char *SV_GetClientIDString(client_t *client);
extern int COM_CheckParm(char *parm);
extern cmd_function_t *Cmd_FindCmdPrev(const char *cmd_name);
extern const char* Cmd_Argv(int arg);
extern void SV_RejectConnection(netadr_t * adr, char * fmt, ...);
extern qboolean Cvar_Command(void);
extern cvar_t * Cvar_FindVar(const char *var_name);
extern qboolean s_com_token_unget;
extern int A_stricmp(const char *s1, const char *s2);
extern int A_strlen(const char *str);
extern command_t clcommands[23];
extern netadr_t net_from;
extern sizebuf_t net_message;
extern edict_t *sv_player;
extern char com_token[COM_TOKEN_LEN];
extern client_t *host_client;


For example, there are no such functions in the engine ...

char *MSG_ReadString(void);
void Cmd_ExecuteString(char *text, cmd_source_t src);
int COM_CheckParm(char *parm);
cmd_function_t *Cmd_FindCmdPrev(const char *cmd_name);
qboolean Cvar_Command(void);
cvar_t * Cvar_FindVar(const char *var_name);

Still, it was better without without the -Wl option, - version-script = .. / version_script.lds'

**Comment by WPMGPRoSToTeMa** [comment]
> client_t *host_client;

`IGameClient*(*GetHostClient)();`
> char *MSG_ReadString(void);

This is really strange, why we have only:
```C++
int(*MSG_ReadShort)();
int(*MSG_ReadBuf)(int iSize, void *pbuf);
```
But temporarily `MSG_ReadString` can be emulated via:
```C++
sizebuf_t*(*GetNetMessage)();
int*(*GetMsgReadCount)();
int*(*GetMsgBadRead)();
```
> netadr_t net_local_adr;

`net_address` cvar?
> sizebuf_t net_message;

`sizebuf_t*(*GetNetMessage)();`
> netadr_t net_from;

`IRehldsServerData::GetNetFrom`
> command_t clcommands[23];
qboolean s_com_token_unget;
char com_token[COM_TOKEN_LEN];

What is the purpose of getting them?
> edict_t *sv_player;

It can be semi-emulated via `host_client->edict`.

**Comment by WPMGPRoSToTeMa** [comment]
@GoDtm666 maybe just hook `HandleNetCommand` with `clc_stringcmd` and partially reimplement `SV_ParseStringCommand`?

**Comment by In-line** [comment]
Closing as non active.
