### ISSUE TITLE
CONNECTION TO STEAM SERVER UNSUCCESSFUL : VAC PORT ISSUE

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#543]
Hey,
I read on hlds documentation to.open port 26900on udp for vac connections. I did it but it still says connection to steamervers unsuccessful. When I allow all ports it works but I'm unable to figure which port does vac works.. Please someone help me finding that

**Comment by theAsmodai** [comment]
Show your firewall rules please.

**Comment by ish12321** [comment]
Inbound : https://i.imgur.com/UdMgPxf.jpg
Outbound : https://i.imgur.com/e6U0mx9.jpg

**Comment by ish12321** [comment]
Please check.

**Comment by theAsmodai** [comment]
Are you serious? Why did you open 27095 TCP insted of 26900 UDP?

**Comment by ish12321** [comment]
I opened 26900 but closed due to not working.. Shall i reopen? 27095 is server port

**Comment by ish12321** [comment]
Added 26900 in tcp in and out

**Comment by OsweRRR** [comment]
only open udp and close tcp unless you need it for others..

**Comment by ish12321** [comment]
You mean for vac it requires udp in and out?

**Comment by ish12321** [comment]
Found this here https://developer.valvesoftware.com/wiki/Half-Life_Dedicated_Server

The ports HLDS officially requires are:
27015 UDP (game transmission, pings)
27015 TCP (RCON)
27020 UDP (HLTV transmission)
26900 UDP (VAC service) -- automatically increments if used in case of additional server processes

**Comment by WPMGPRoSToTeMa** [comment]
> 27015 TCP (RCON)

RCON uses UDP.

**Comment by ish12321** [comment]
Hmm. What about 26900 i opened udp 26900 still vac aint working..

**Comment by ish12321** [comment]
Connection to steam servers unsuccessful

**Comment by voed** [comment]
Try to open 27005-27105 outbound UDP. Anyway, VAC is completely useless, it just gives shield icon in server list

**Comment by ish12321** [comment]
People cant connect on invites if connection to steam servers is unsuccessful
On invite when they clivk in steam it shows as not responding..

I'll try those ports but is there no specific port for vac?

**Comment by voed** [comment]
Ah, right
I think "VAC" can use any available port but anyway try it, nothing bad will happen

**Comment by ish12321** [comment]
Hmm. I'll try asap and report. Also, it'll be great if in rehlds a specific port is specified for vac..

**Comment by voed** [comment]
https://github.com/dreamstalker/rehlds/blob/f48ddcfaddd95f48ef86ffc4d923ba11f3fe8510/rehlds/engine/sv_steam3.cpp#L264
Well, default port must be 26900 and you can change it by `-sport 27xxx` launch parameter

**Comment by ish12321** [comment]
I'm using sport 26900 :/

**Comment by ish12321** [comment]
Could not establish connection to Steam servers.

**Comment by LevShisterov** [comment]
`+ip 0.0.0.0`

**Comment by ish12321** [comment]
With opengamepanel it is :/

hlds_linux -game cstrike -pidfile ogp_game_startup.pid +map de_dust2 +ip localhost +port 27095 +maxplayers 32 -condebug -pingboost 2

**Comment by ish12321** [comment]
I dont get option to manually do it.

**Comment by ish12321** [comment]
Just to inform : My all issues are solved as i totally allow all ports but I cant do that as with it comes few ddos'es

**Comment by ish12321** [comment]
@theAsmodai

**Comment by ish12321** [comment]
Anyone please help..

**Comment by di57inct** [comment]
just use a non-steam cs. they're better in every way possible.

**Comment by ish12321** [comment]
We've steam players on server. We cant invite them via steam app as wgen he tries via that it shows not responding due to "Could not establish connection to Steam servers."

**Comment by ish12321** [comment]
Found something in syslog.. Maybe now i could be helped?
 Nov 28 06:25:10 ip-172-31-0-228 kernel: [683845.895000] Firewall: *UDP_OUT Blocked* IN= OUT=eth0 SRC=172.31.0.228 DST=103.28.54.10 LEN=64 TOS=0x00 PREC=0x00 TTL=64 ID=49077 DF PROTO=UDP SPT=26900 DPT=27017 LEN=44 UID=1001 GID=1001

**Comment by theAsmodai** [comment]
@ish12321, what's the problem to open 26900 UDP in both directions? I don't understand what's here can been discussed for so long.

**Comment by ish12321** [comment]
I've opened it already in both directions.

**Comment by ish12321** [comment]
Solved.
