### ISSUE TITLE
HLTV not loading libsteam_api.so and proxy.so

### ISSUE THREAD

**Issue by krangm** [dreamstalker/rehlds#554]
debian 9.3
rehlds build: 3.3.0.624-dev
`$ ldd hltv`
> 	linux-gate.so.1 (0xf76f5000)
> 	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf76d4000)
> 	libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf755a000)
> 	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7505000)
> 	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf734d000)
> 	/lib/ld-linux.so.2 (0xf76f7000)
> 	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf732f000)

on regular launch HLTV gives error
`Error: libsteam_api.so: cannot open shared object file: No such file or directory`
if use `-dev` param it also gives
`WARNING! System::GetLibrary: coulnd't load library (proxy.so).`

with `LD_PRELOAD` working fine, but you know...

**Comment by In-line** [comment]
Closing as non active.
