### ISSUE TITLE
Pink Boxes on Maps, textures missing

### ISSUE THREAD

**Issue by WhiteFang1319** [dreamstalker/rehlds#556]
Hello.
When I install Rehlds and it's stuff. for the first time in a clean server, there are pink boxes on spawns and bomb sites and in other maps like aa_dima 2 ladder doesn't look proper. I had got this problem before too on a server with Linux. I did try removing all of them one by one by the default ones but it didn't work. So I did a reinstall of Rehlds and it's stuff and it was normal. But this time it is not working ( now sv is on Windows)
Rehlds:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.3.0.624-dev
Build date: 15:23:36 Dec 15 2017 (1343)
Build from: https://github.com/dreamstalker/rehlds/commit/a761c5d

ReGameDLL version: 5.3.0.276-dev
Build date: 16:19:11 Dec  8 2017
Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/adeb09a

Metamod-r v1.3.0.104, API (5:13)
Metamod-r build: 17:08:37 Nov 19 2017
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/3ff4f67

![20171217163900_1](https://user-images.githubusercontent.com/25999621/34078949-8bf80b3c-e349-11e7-9440-88d84846b5e0.jpg)
![20171217163905_1](https://user-images.githubusercontent.com/25999621/34078950-8c1f4760-e349-11e7-81fa-85a409b0d3ad.jpg)
![20171217163908_1](https://user-images.githubusercontent.com/25999621/34078951-8c458362-e349-11e7-9d5c-4c6420653632.jpg)
![20171217163914_1](https://user-images.githubusercontent.com/25999621/34078952-8c6c8da4-e349-11e7-87e9-e9255cc15981.jpg)
![20171217163918_1](https://user-images.githubusercontent.com/25999621/34078953-8c9ae23a-e349-11e7-9c14-04ae804cd203.jpg)
![20171217163920_1](https://user-images.githubusercontent.com/25999621/34078954-8cc2e352-e349-11e7-8b18-326cdff12dbf.jpg)
![20171217163932_1](https://user-images.githubusercontent.com/25999621/34078955-8ceaf1a8-e349-11e7-8b0f-44029cc219cb.jpg)
![20171217163936_1](https://user-images.githubusercontent.com/25999621/34078956-8d124528-e349-11e7-8565-c5bd5ba14dc8.jpg)
![20171217163943_1](https://user-images.githubusercontent.com/25999621/34078957-8d3dd8fa-e349-11e7-97d7-a209c7bfc56f.jpg)
![20171217164000_1](https://user-images.githubusercontent.com/25999621/34078958-8d6f35e4-e349-11e7-8481-39aa2f639fae.jpg)
![20171217164331_1](https://user-images.githubusercontent.com/25999621/34078959-8d9e70a2-e349-11e7-8e45-7d07acef6f84.jpg)

**Comment by s1lentq** [comment]
disable cvar `showtriggers` from regamedll

**Comment by WhiteFang1319** [comment]
Thanks. Solved.
