### ISSUE TITLE
Problem in new update

### ISSUE THREAD

**Issue by lspublic** [dreamstalker/rehlds#557]
Hello s1lent i put new update in my server : » ReHLDS (1347):
Reversed CIPRateLimit Minor refactoring 

But not allow to connect player i make boost server stay 2/32 with 2 bots i try to connect my friend not working now i change version working good maybe you need to check where is problem in connect

**Comment by s1lentq** [comment]
show current value of cvar's `max_queries_sec`, `max_queries_window`, `max_queries_sec_global`

**Comment by lspublic** [comment]
I dont know what happen in my server official not accept to connect players in my clanwar same ip working i test in clawnar your and this show : 
12:02:31 CVar List
         --------------
         max_queries_sec              :              3.0, sv
         max_queries_sec_global       :               30, sv
         max_queries_window           :               60, sv
         --------------
           3 CVars for [max_]
         CvarList ? for syntax

My offical server : 
12:03:49 CVar List
         --------------
         max_queries_sec              :                0, sv
         max_queries_sec_global       :                0, sv
         max_queries_window           :               60, sv
         --------------
           3 CVars for [max_]
         CvarList ? for syntax

**Comment by s1lentq** [comment]
well, actually these values and are not by default

https://github.com/dreamstalker/rehlds/blob/f5784be364afcdb9895b2fca8fe26493aea3d7c0/rehlds/engine/ipratelimit.cpp#L33-L35

remove these cvar's from server.cfg or somewhere are sets

**Comment by lspublic** [comment]
Cab you check my cvar in server.cfg and to put new cvar i dont know how to put if you not have problem ?

hostname "..:: LS Public Server ::.."

rcon_password ""

mp_timelimit 35
mp_startmoney 1200
mp_c4timer 35
mp_forcecamera 2
mp_freezetime 2
mp_autokick 0
sv_voiceenable 0
mp_roundtime 2
mp_friendlyfire 0
sv_allowdownload 1
sv_allowupload 1
sv_downloadurl "http://fastdl.e-trail.eu/fdl_srv_34839_VWs/cstrike/"
sv_cheats 0
sv_aim 0
pausable 0
sv_maxspeed 320
sv_lan 0
sv_maxrate 80000
sv_minrate 70000
sv_maxupdaterate 100
sv_minupdaterate 60
sv_region 3
sv_proxies 0
exec banned.cfg
exec listip.cfg
exec lscycles.cfg
lrs_hud_color "96 96 176"
csstats_maxsize 9000

amx_gamename "lspublic.com"
//show
amx_task 20 "amx_csay yellow NXEMJE - Nuk eshte LIVE !" s
amx_task 20 "amx_say NXEMJE - Nuk eshte LIVE !" s
amx_task 20 "amx_say NXEMJE - Nuk eshte LIVE !" s
amx_task 20 "amx_say NXEMJE - Nuk eshte LIVE !" s
amx_task 20 "amx_say NXEMJE - Nuk eshte LIVE !" s
amx_task 20 "amx_say NXEMJE - Nuk eshte LIVE !" s
amx_task 25 "amx_csay green LIVE Per: 15" s
amx_task 25 "amx_say LIVE Per: 15 sekonda" s
amx_task 26 "amx_csay green LIVE Per: 14" s
amx_task 27 "amx_csay green LIVE Per: 13" s
amx_task 28 "amx_csay green LIVE Per: 12" s
amx_task 29 "amx_csay green LIVE Per: 11" s
amx_task 31 "amx_csay green LIVE Per: 10" s
amx_task 31 "amx_say LIVE Per: 10 sekonda" s
amx_task 32 "amx_csay green LIVE Per: 9" s
amx_task 33 "amx_csay green LIVE Per: 8" s
amx_task 34 "amx_csay green LIVE Per: 7" s
amx_task 35 "amx_csay green LIVE Per: 6" s
amx_task 36 "amx_csay green LIVE Per: 5" s
amx_task 36 "amx_say LIVE Per: 5 sekonda" s
amx_task 37 "amx_csay green LIVE Per: 4" s
amx_task 38 "amx_csay green LIVE Per: 3" s
amx_task 39 "amx_csay green LIVE Per: 2" s
amx_task 40 "amx_csay green LIVE Per: 1" s
amx_task 41 "sv_restartround 1" s
amx_task 45 "amx_csay yellow LIVE LIVE LIVE !!! GL ^ HF by c0d3!" s
amx_task 45 "amx_say LIVE LIVE LIVE !!! GL ^ HF !" s
amx_task 45 "amx_say LIVE LIVE LIVE !!! GL ^ HF !" s
amx_task 45 "amx_say LIVE LIVE LIVE !!! GL ^ HF !" s
amx_task 45 "amx_say LIVE LIVE LIVE !!! GL ^ HF !" s
amx_task 45 "amx_say LIVE LIVE LIVE !!! GL ^ HF !" s

**Comment by s1lentq** [comment]
@lspublic these cvar's somewhere set, just look up to each configuration file what you have

**Comment by lspublic** [comment]
@s1lentq  okey thanks very much for information and for help you are the best ;)
