### ISSUE TITLE
Same sky on all maps (sv_skyname)

### ISSUE THREAD

**Issue by Zetz512** [dreamstalker/rehlds#560]
Hi!, i will report a problem what i see a such strange...

When i change a map the sky are the same.. and i check the sv_skyname and don't change the value
And still on "desert" regardless of the map.

Some screens on de_aztec:
http://prntscr.com/hr4ya8

http://prntscr.com/hr4yfb

**Comment by Daniele386** [comment]
I cannot reproduce it; with and without metamod I'm not experiencing that problem.
Have you tried to disable metamod? Maybe it is a plugin?

**Comment by Zetz512** [comment]
Mmm, i will try disabling Metamod..

**Comment by hashnimmo** [comment]
As far as I know, this will happen if you don't have all sky image files in the following server/client directories:

cstrike\gfx\env
valve\gfx\env

Make sure your client and server both contain a full installation of the game, if not the game tends to default it down to the sky that you have posted.

**Comment by Zetz512** [comment]
Ok, ty for that info!!

**Comment by WPMGPRoSToTeMa** [comment]
This is specific to ReHLDS, https://github.com/dreamstalker/rehlds/commit/7f21a5bc541068b6a047cc8faab7d322016c4fc9

**Comment by In-line** [comment]
Closing as non active.
