### ISSUE TITLE
message_health is not Avalable function.

### ISSUE THREAD

**Issue by FOXZOMBIE** [dreamstalker/rehlds#563]
Valve say this in his build 6153:
"Clamped health values to fix display issues when it dropped below 1 or above 255"

Health stay to 255 or real and i can't make fakeHealth for zombie server.
And function message_health is not avalable anymore. Please fix it this in ReHLDS.. If you can. Sorry for my bad English.

**Comment by Mistrick** [comment]
HUD Health is byte, it can't be more than 255.

**Comment by Vaqtincha** [comment]
to'g'ri

**Comment by FOXZOMBIE** [comment]
No, no, no... ... Sory for my bad english.. I trying to say.. In old build message_health is work okay... If Zombie have 4000 real health message_health say 250 in % .. And if zombie health is 3000 message health say 200 ... This working on old cs 1.6 build.. Now health stay on 255...

**Comment by Vaqtincha** [comment]
Leave a comment

**Comment by WPMGPRoSToTeMa** [comment]
@FOXZOMBIE show the code to reproduce pls.

**Comment by FOXZOMBIE** [comment]
In my zombie_plague40.sma main plugin.

new zmaxhp[33],  g_zombie_spec_health[33]

// in spawn/respawn/infect/humanized post's
zmaxhp[index] = get_user_health(index)

register_message(get_user_msgid("Health"), "message_health")

// Fix for the HL engine bug when HP is multiples of 256
public message_health(msg_id, msg_dest, msg_entity)
{
	if (!is_user_valid_alive(msg_entity)) return
	
	// Get player's health
	new health = get_msg_arg_int(1)
	
	if(g_zombie[msg_entity])
	{
		static Float:hp, Float:maxhp, p
		hp = float(get_user_health(msg_entity))
		maxhp = float(zmaxhp[msg_entity])
		p = floatround((hp / maxhp) * 250.0)
		if( p > 250 ) p = 250
		if( p == 0 ) p = 1
		
		if (health < 256) return;
		if (health % 256 == 0) fm_set_user_health(msg_entity, pev(msg_entity, pev_health) + 1)
		set_msg_arg_int(1, get_msg_argtype(1), p)
		g_zombie_spec_health[msg_entity] = p
	}else{
		// Don't bother
		if (health < 256) return;
		
		// Check if we need to fix it
		if (health % 256 == 0)
			fm_set_user_health(msg_entity, pev(msg_entity, pev_health) + 1)
		
		// HUD can only show as much as 255 hp
		set_msg_arg_int(1, get_msg_argtype(1), 255)
	}
}

This code making Real Health in %. If health is MAX(100%) 4000 HP transform in message to 250% and if you take health your HP%-- is take up to. 
This code working on all platforms before Official build 6153. And ReHLDS needed this build to working successfully. Can you fix it? Thanks. :)

**Comment by WPMGPRoSToTeMa** [comment]
@FOXZOMBIE
```C++
public message_health(msg_id, msg_dest, msg_entity) {
 if (!g_zombie[msg_entity] || get_msg_arg_int(1) == 0) {
  return;
 }
 
 new health = get_user_health(msg_entity);
 new maxHealth = zmaxhp[msg_entity];
 new percentage = health*250/maxHealth;
 percentage = clamp(percentage, 1, 250);
 set_msg_arg_int(1, get_msg_argtype(1), percentage);
}
```

**Comment by FOXZOMBIE** [comment]
Damn, it works! I would never have done it. BIG THANKS. You're a big man! :))

**Comment by Vaqtincha** [comment]
фсе кто пишет зм - быдлокодеры

**Comment by In-line** [comment]
Closing as non active.
