### ISSUE TITLE
Rehlds import ddos protection?

### ISSUE THREAD

**Issue by csoyuncu** [dreamstalker/rehlds#564]
After installing the 626 version, players begin to experience disconnected disconnect problems. This problem usually occurs after the fast "retry" command is applied. Is this a problem or do I need to protect it for DDOS?

**Comment by s1lentq** [comment]
this issue looks like #557
check out your values for these the CVar's

**Comment by csoyuncu** [comment]
@s1lentq  ok dimitry thanks :)
