### ISSUE TITLE
Hostages: Climb/Crawl-Support

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#565]
It would be nice to play with 'more intelligent' Hostages.
They should be able to follow all CT movements.

**Comment by spark512** [comment]
https://forums.alliedmods.net/showthread.php?t=50842

**Comment by In-line** [comment]
It doesn't refer to rehlds. Open issue in ReGameDLL_CS

**Comment by fred0r** [comment]
I opened it:
https://github.com/s1lentq/ReGameDLL_CS/issues/246
