### ISSUE TITLE
TSource Engine Query DDOS

### ISSUE THREAD

**Issue by ish12321** [dreamstalker/rehlds#566]
Hey, 
We got hit by a ddos/dos (not sure) which in the traffic dump showed as TSource Engine Query. Read on internet a bit about it. Found out it floods the hlds because of queries that look lile A2S queries coming too many at time.
It might be solved by storing queries in cache every 5 secs and then responding by cache. Could this be implemented in rehlds?

**Comment by theAsmodai** [comment]
It's already implemented in reunion.

**Comment by ish12321** [comment]
But my server got down by a hit from tsource engine query ddos..

**Comment by ish12321** [comment]
The network consumption was not much so I'm sure my network wasnt overloaded.

**Comment by ish12321** [comment]
https://mega.nz/#!sNUGnRiJ!4WhLjq6iyLj3zCSXOfVMIKxPD7I5YeI2pT3yxG_iOmo

https://mega.nz/#!IcE1CCKR!pBVIbon-V94YgIIgDHrDwTDB1FHlYI47mnE5UdfdVoQ

**Comment by theAsmodai** [comment]
You should filter these attacks at a higher level than game server.

**Comment by ish12321** [comment]
Then is there any script that could cache the a2s info before the packets hit server?

**Comment by In-line** [comment]
Yes. 

https://github.com/blastehh/SourceQueryCacheMono
http://www.wantedgov.it/page/62-srcds-query-cache/
https://security.stackexchange.com/questions/100519/tsource-engine-query-ddos-attack
https://hack.ovh/topic/10305-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D1%83%D0%B5%D0%BC-tsource-engine-%D1%84%D0%BB%D1%83%D0%B4-valve-source-engine-ddos-block/
