### ISSUE TITLE
Bot players change played time?

### ISSUE THREAD

**Issue by csoyuncu** [dreamstalker/rehlds#573]
how can i attach random time playe to BOTs in game ?

**Comment by In-line** [comment]
It should be done in reunion.

**Comment by csoyuncu** [comment]
how?

**Comment by In-line** [comment]
It isn't likely that this feature will be implemented

**Comment by csoyuncu** [comment]
hmmm. I think it can do. I will work for do it. Thanks.

**Comment by In-line** [comment]
Closing as non active.
