### ISSUE TITLE
Question about interpolation (ex_interp)

### ISSUE THREAD

**Issue by Freeman-AM** [dreamstalker/rehlds#577]
I saw so many times on servers, people saying fix your interp to 0.01.
Those people mean that other players playing with 0.1 interp affect THEIR personal accuracy about player position.

While from what I know and see from the code, interpolation (set by ex_interp) only have an effect about YOUR and only YOUR graphic visuals of players position. The value of other players ex_interp have NO effect on the accuracy of the other player position on your screen.

So who is right and who is wrong ? with little explanation because there is so much misunderstanding about that question.

**Comment by theAsmodai** [comment]
Yes, it's right.
