### ISSUE TITLE
mm_insane Behavior

### ISSUE THREAD

**Issue by justgo97** [dreamstalker/rehlds#580]
i want to know which part in the code i need to change to get the behavior of mmtimer

mm_insane 1
mm_insane 2

for both linux and windows

ps: i don't care how much cpu it will take

**Comment by wopox1337** [comment]
@justgo97  Please stop doing stupid things. =)

**Comment by cris840** [comment]
Here you go
https://github.com/dreamstalker/rehlds/actions/runs/5432936566
