### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Hembi** [dreamstalker/rehlds#582]
Hi,

I updated my server to latest ReHLDS, Metamod-r and ReAmxModX.
I have a GunGame mod and after the update it crashed with 'Segmentation Fault'.
How can I debug the problem?
I know that the game has a log file which contain the crash information in this case, but I do not know which file is that and where can I find it in my system (Linux). Can me anyone explain this?

version:
> Exe version 1.1.2.7/Stdio (cstrike)
> ReHLDS version: 3.4.0.638-dev
> Build date: 22:49:26 Feb 16 2018 (1406)
> Build from: https://github.com/dreamstalker/rehlds/commit/91bc288

meta version:
> Metamod-r v1.3.0.116, API (5:13)
> Metamod-r build: 23:14:23 Feb 16 2018
> Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/cdefc71

meta list:
> Currently loaded plugins:
>       description      stat pend  file                      vers            src  load  unload
>  [ 1] SafeNameAndChat  RUN   -    SafeNameAndChat.so        v1.1            ini  ANY   ANY  
>  [ 2] Rechecker        RUN   -    rechecker_mm_i386.so      v2.5            ini  Chlvl ANY  
>  [ 3] AMX Mod X        RUN   -    amxmodx_mm_i386.so        v1.8.3-Re       ini  Start ANY  
>  [ 4] Reunion          RUN   -    reunion_mm_i386.so        v0.1.0.92       ini  Start Never
>  [ 5] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so    v0.1.6          ini  Start Never
>  [ 6] Revoice          RUN   -    revoice_mm_i386.so        v0.1.0.32       ini  Start Never
>  [ 7] Fun              RUN   -    fun_amxx_i386.so          v1.8.3-Re       pl3  ANY   ANY  
>  [ 8] Engine           RUN   -    engine_amxx_i386.so       v1.8.3-Re       pl3  ANY   ANY  
>  [ 9] ReAPI            RUN   -    reapi_amxx_i386.so        v5.5.0.150-dev  pl3  ANY   Never
>  [10] FakeMeta         RUN   -    fakemeta_amxx_i386.so     v1.8.3-Re       pl3  ANY   ANY  
>  [11] CStrike          RUN   -    cstrike_amxx_i386.so      v1.8.3-Re       pl3  ANY   ANY  
>  [12] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so  v1.8.3-Re       pl3  ANY   ANY  
> 12 plugins, 12 running

**Comment by In-line** [comment]
At least don't use reamxmodx it is outdated. Latest amx x 1.8.3 has native Re* support

**Comment by In-line** [comment]
At least send us debug.log, for more info visit: #516

**Comment by Hembi** [comment]
@In-line I got a debug.log, but it does not contain any info of the problem and a splitted core.0. Can I post this file only for the moderators of this Project? It contain some private information about my server.

debug.log:

> ----------------------------------------------
> CRASH: Sat Feb 17 20:31:47 CET 2018
> Start Line: ./hlds_linux -game cstrike -secure +sv_lan 0 +maxplayers 32 +map de_dust2 +sys_ticrate 1000 -pingboost 2 -condebug -debug
> [New LWP 28971]
> [New LWP 28978]
> [New LWP 28980]
> [New LWP 28984]
> #0  0xf30f959b in ?? ()
> End of crash report
> ----------------------------------------------

**Comment by In-line** [comment]
@Hembi Did you update amxmodx?

**Comment by In-line** [comment]
From which version to which did you update your server?

**Comment by Hembi** [comment]
@In-line Yes, I updated it.

> Currently loaded plugins:
>       description      stat pend  file                      vers             src  load  unload
>  [ 1] SafeNameAndChat  RUN   -    SafeNameAndChat.so        v1.1             ini  ANY   ANY  
>  [ 2] Rechecker        RUN   -    rechecker_mm_i386.so      v2.5             ini  Chlvl ANY  
>  [ 3] AMX Mod X        RUN   -    amxmodx_mm_i386.so        v1.8.3-dev+5151  ini  Start ANY  
>  [ 4] Reunion          RUN   -    reunion_mm_i386.so        v0.1.0.92        ini  Start Never
>  [ 5] ReAuthCheck      RUN   -    reauthcheck_mm_i386.so    v0.1.6           ini  Start Never
>  [ 6] Revoice          RUN   -    revoice_mm_i386.so        v0.1.0.32        ini  Start Never
>  [ 7] Fun              RUN   -    fun_amxx_i386.so          v1.8.3-dev+5151  pl3  ANY   ANY  
>  [ 8] Engine           RUN   -    engine_amxx_i386.so       v1.8.3-dev+5151  pl3  ANY   ANY  
>  [ 9] ReAPI            RUN   -    reapi_amxx_i386.so        v5.5.0.150-dev   pl3  ANY   Never
>  [10] FakeMeta         RUN   -    fakemeta_amxx_i386.so     v1.8.3-dev+5151  pl3  ANY   ANY  
>  [11] CStrike          RUN   -    cstrike_amxx_i386.so      v1.8.3-Re        pl3  ANY   ANY  
>  [12] Ham Sandwich     RUN   -    hamsandwich_amxx_i386.so  v1.8.3-dev+5151  pl3  ANY   ANY  
> 12 plugins, 12 running

ReAmxModX to latest 1.8.3-dev build.

**Comment by In-line** [comment]
In your issue, you mentioned that you have updated your server. Information on the older versions of the relevant parts is required. Exact version will be better.

**Comment by Hembi** [comment]
Hi,

Sorry for the late answer, I have not much time. Now I tested the plugin with the older ReHLDS resources.
On older version works perfect. After I updated the ReHLDS to the latest version. The servers working properly. After the Metamod update (v1.21p37 -> MetaMod-r 1.3.0.116) the server crashed again. So the problem is in the new Metamod.
Sadly, I can not provide more information. My core file is truncated and the debug.log does not provided any important information. Please close this ticket. I will open a new one in MetaMod-r project on GitHub.

Thanks!
