### ISSUE TITLE
Engine Druken, Making Players Drunk [Video Attached]

### ISSUE THREAD

**Issue by Dr-Strange91** [dreamstalker/rehlds#585]
Earlier Using: ReHLDS 3.4.0.643 (In Merged Branch From TC Build)
Now Used ReHLDS 3.4.0.637 (Master Branch) [Druken Behaviour]

Well By Reverting Back To 3.4.0.643, The Problem Solved, But Kindly Fix It.

If person moves to right the screen tilts to right, if person moves to left screen tilts to left.

Here is what actually the problem is happeing ..!!

Video: https://youtu.be/PpTywkFeh60

**Comment by In-line** [comment]
Fixed.
