### ISSUE TITLE
Chat is not working

### ISSUE THREAD

**Issue by milutinke** [dreamstalker/rehlds#586]
I have Amx Modx 1.8.3 and ReHLDS 3.4.0.636.
Chat is not working at all.
I have turned amxmodx and it is still not working.

Edit:
Updated to 3.4.0.638 and still not working.
Here is the demonstration.
https://www.useloom.com/share/4f32c522a66b4b45b950384300adda27

Edit: 
It has something to do with the old v42 client, but still, a lot of people use it.
https://www.useloom.com/share/2ea02334a4604303866dbed065aa9cde

Edit: I remembered that I have update cs with ReGameDLL, maybe that has something to do with this.
Edit: Yep, ReGame DLL does not work well with new ReHLDS.

**Comment by Dr-Strange91** [comment]
It happens when you are using any other chat related plugin. Like: Chat Colors.

It works fine in some and in some there is problem with same Configuration. I had it in my 4 servers. From which it works in 2 and didn't work in other 2.

The problem is only with ReHLDS servers.

**Comment by milutinke** [comment]
Have you read what I said, I have turned Metamod off, I had pure ReHLDS and chat was not working at all.

**Comment by milutinke** [comment]
Yep, ReGame DLL does not work well with new ReHLDS.
