### ISSUE TITLE
protection for Proxy Clients ?

### ISSUE THREAD

**Issue by csoyuncu** [dreamstalker/rehlds#588]
Hello. I use the latest version of REHLDS. In my server, I have been working with a player who has changed the ip for proxy for a week and is constantly having trouble on my server. How can we take precautions for this? Thank you.

**Comment by csoyuncu** [comment]
is there a any fix for this problem :(

**Comment by LevShisterov** [comment]
Subnet/AS ban.

2018-02-28 1:44 GMT+05:00 csoyuncu <notifications@github.com>:

**Comment by csoyuncu** [comment]
uhh this is very bad :( because it can copy some real ip's..
