### ISSUE TITLE
How to run DemoPlayer on Goldsource 3266?

### ISSUE THREAD

**Issue by miss1ng** [dreamstalker/rehlds#590]
How to run DemoPlayer on Goldsource 3266?

**Comment by theAsmodai** [comment]
Don't understand your question. Please explain.

**Comment by miss1ng** [comment]
> Don't understand your question. Please explain.

I compiled demoplayer and core, but when they run on build3266, the game crashed.

**Comment by theshadowz** [comment]
What an on time explaining!
