### ISSUE TITLE
Precache limit for Sven Coop

### ISSUE THREAD

**Issue by Manapo74** [dreamstalker/rehlds#591]
Hello guys, I found an error when running svencoop:
![image](https://user-images.githubusercontent.com/34998786/37245033-353e0542-24cd-11e8-8e32-c90e881fe71d.png)

Could you increase the limit of the cache in Rehlds, please :(

**Comment by In-line** [comment]
No, but you can use https://github.com/In-line/metamod_unprecacher or something similar to block unused resources. Also, use search and don't create duplicate issues. 😃

**Comment by WaLkZa** [comment]
https://github.com/dreamstalker/rehlds/issues/180#issuecomment-191191838

**Comment by Manapo74** [comment]
Oh, sorry, Thanks!
