### ISSUE TITLE
10+ more ping on Windows

### ISSUE THREAD

**Issue by WhiteFang1319** [dreamstalker/rehlds#600]
I've been running ReHLDS on Linux for most of the time. I decided to try out running it on Windows. So I've installed it on Windows Server 2012 R2. I installed it first by steamcmd and then just copying over the server files from the backup and installing all the Re-related stuff. Then I saw that most players are getting more ping than usual, so I decided to know this problem by making another clean server. On a clean server( the latest build and 6153 both) players less ping, then I tried installing ReHLDS ( latest one) then players had more ping. Hosting server on Windows for first time so I may not know some stuff.. I run the server on a VPS so the ports are opened from the VPS website ( Using port 27015)

Server cfg:
https://pastebin.com/MqGY3jPg
Parameters I'm using to start server:
` -game cstrike -ip x.x.x.x +port 27015 +map de_dust2 +maxplayers 32 -exec server.cfg -pingboost 3 +fps_max 1000 sys_ticrate 1100 -condebug`
( Removed the IP from here cuz it'll seem as advt)

Will attach some other stuff if needed, guide me please.

**Comment by voed** [comment]
Looks like [this](https://github.com/dreamstalker/rehlds/issues/501)
Check your `stats`, did you stuck at 64/100 FPS?

**Comment by krangm** [comment]
iirc windows has no `pingboost` at all, so ~10 ping difference should be reasonable

**Comment by WhiteFang1319** [comment]
@voed yeah I've been facing that. Though I wasn't able to use a media player because it's not there in the Windows Server. I'll try to install it and try. Will it make a difference in ping though? 
@krangm  yeah you're right, I just copied the commandline from my Linux server. For people with stable ping it isn't a problem but for players who have already high ping then 10+ is a problem for them so was trying to fix it

**Comment by voed** [comment]
@WhiteFang1319 yes, with normal FPS ping will decrease
You can also try registry tweak from that topic, but idk, do backup before it

**Comment by WPMGPRoSToTeMa** [comment]
If you have compiler you can try this small program:
```C++
#include <Windows.h>

#pragma comment(lib, "Winmm.lib")

int main() {
	timeBeginPeriod(1);
	system("pause");
	timeEndPeriod(1);
}
```

**Comment by WhiteFang1319** [comment]
@voed I've already done the registry tweak before.. will try media player
@WPMGPRoSToTeMa I'll try it thanks

**Comment by WhiteFang1319** [comment]
@voed  I've tried using media player but there was no use. I tried using VLC media player and fps rised up to around 180.. Any other solution?
I've yet to try prostotema's solution as my PC is broken and I can't use compiler

**Comment by LevShisterov** [comment]
http://aghl.ru/files/plugins/mmtimer-1.0.zip
Plugin that rise system timer resolution. Just install as usual metamod plugin. No configuration needed.

**Comment by WhiteFang1319** [comment]
@LevShisterov it doesn't work properly with ReHLDS. 
Anyway @WPMGPRoSToTeMa  solution worked for me, why does the 64 fps thing happen though?I'd like to know. Then I'll close the issue 😁

**Comment by LevShisterov** [comment]
There is nothing incompatible with ReHLDS in this plugin.

**Comment by WhiteFang1319** [comment]
@LevShisterov  I've tried this plugin already on Linux. It wasn't loading. Now when I used it in Windows it gave me less fps than Prostotema's solution. So I wouldn't use it

**Comment by LevShisterov** [comment]
On Linux? Dll?
It doesn't gave fps. It just rise system timer resolution. It doesn't depends on plugin to which resolution timer will be changed. It depends on the system. So, this plugin or one that is above as a source - they are the same.
