### ISSUE TITLE
BOMB

### ISSUE THREAD

**Issue by ReKZNTP** [dreamstalker/rehlds#608]
> Protocol version 48
> Exe version 1.1.2.7/Stdio (cstrike)
> ReHLDS version: 3.4.0.641-dev
> Build date: 16:11:38 Apr  6 2018 (1455)
> Build from: https://github.com/dreamstalker/rehlds/commit/ce163a3

> ReGameDLL version: 5.7.0.298-dev
> Build date: 09:01:01 Apr  1 2018
> Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/b84ae95

Иногда бывает, когда заложил бомбу, но успел убить всех КТ, то в новом раунде все еще идет отчет бомбы.. потом взрыв..

Также добавлю, очень редко выдавало двоим игрокам бомбу

**Comment by voed** [comment]
It does not refer to rehlds
