### ISSUE TITLE
AMXX modules not running on latest build

### ISSUE THREAD

**Issue by BeqaGurgenidze** [dreamstalker/rehlds#611]
I Installed latest build of reHLDS (647), but after running server (game=cstrike) it says:

Error:
[AMXX] Module is not a valid library (module name)

Then installed previous build of reHLDS (643) and modules loaded without any errors.

using AMXX 1.8.3-dev+5154 (latest)
using ReGameDLL-5.7.0.301 (latest)

**Comment by di57inct** [comment]
+1 can confirm

**Comment by fred0r** [comment]
Tried also metamod-r on Linux but as the other mentioned: it doesnt load amxmodx

**Comment by fred0r** [comment]
https://github.com/dreamstalker/rehlds/commit/2fa76553709550c1eab8fe28423c26f725a32ba8 fixed it.
@s1lentq : Thank you !
