### ISSUE TITLE
Poor FPS

### ISSUE THREAD

**Issue by nksiddhant** [dreamstalker/rehlds#613]
Running quad core dedicated server.
Tried to +system_tickrate 1000, 1500 and 2000
But fps doesn't go higher then 800.
Please give some solution.

Startup cmd +system_tickrate 1500 -pingbost 2 tried pingboost 3 too
Version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.4.0.641-dev
Build date: 16:11:38 Apr  6 2018 (1455)
Build from: https://github.com/dreamstalker

Game version
ReGameDLL version: 5.7.0.301-dev
Build date: 00:28:14 Apr  9 2018
Build from: https://github.com/s1lentq

**Comment by voed** [comment]
upgrade your CPU then ¯\\\_(ツ)_/¯

**Comment by krangm** [comment]
doesnt fps cvar is called `sys_ticrate` ?
not sure `+system_tickrate 1500` will change anything

also if you want to gain fps over 1000 you probably should use `-pingboost 3`
doubt it possible to get over 1000 fps with any other pingboost option

**Comment by WhiteFang1319** [comment]
There's no setting such as system_tickrate. It should be sys_ticrate. Did you spell it properly?

**Comment by nksiddhant** [comment]
sorry I mean +sys_tickrate 1000 only. and with pingboost 3 I am getting too many losses.

**Comment by WhiteFang1319** [comment]
Maybe your setup is low-end . Heavy amxx plugins may have an effect too I guess
