### ISSUE TITLE
Invalid split packet length 8 problem

### ISSUE THREAD

**Issue by russh3l** [dreamstalker/rehlds#618]
hello, someone know how can i solve this ?

Invalid split packet length 8
Invalid split packet length 8
Invalid split packet length 8
Invalid split packet length 8
Invalid split packet length 8
Invalid split packet length 8

i installed last ReHLDS version but it didnt solve the problem. Its look like a DDoS attack but no high cpu or ram usage everything looks good and when i change server port or ip adress it disappears and its coming again ... Its look like port attack 

server ping : +600 

Game is : Half-Life

note: using lastest ReHLDS version

**Comment by PM32** [comment]
Using reunion? reauthcheck?
