### ISSUE TITLE
There are no icons on those with steam on when I tap the tab

### ISSUE THREAD

**Issue by clau69** [dreamstalker/rehlds#621]
Hello!
When I turn on reunion_mm_i386.so and reauthcheck_mm_i386.so, steam players do not appear on the tab i mean icons, it looks like they're all non-steam, when I turn off everything goes back to normal.
Can you help me?

**Comment by PM32** [comment]
This issues tab is for rehlds issues. Any other addon related, ask on his respective topic. Reunion and Reauthcheck -> http://www.dedicated-server.ru/vbb/forumdisplay.php?f=179

**Comment by Dr-Strange91** [comment]
Yes I also face the same.

Not with all steamers, but it happens with some steamers (dp is not shown) and some others dp is shown. (In a score board).

And its not from this version but its from last many versions.

Hence I'm using amx_steamers plugin, so to avoid mis-understanding.

Kindly fix it, as it effects the rush of server, as some steamers like to see other many steamers in sv, but unfortunately, many of the dps are missing.

Is it related with ReHLDS or Reunion? Or some else?

**Comment by hashnimmo** [comment]
Might be game client related. Because there is a bug in the latest CS 1.6 game client, even if you are in a fully Steam-only server, if your game video resolution is not 1024x768, the player avatars won't show up. Try setting it back to 1024x768 just to make sure it's not a server issue.

**Comment by Dr-Strange91** [comment]
But Server Actually Don't Fetch The Clients !!! Even Shift + Tab Don't Any Info.

If it is Bug With Resolution then why only those dps whom we have sent requests or they are added in our steam is seen but not of others?
