### ISSUE TITLE
After player timeout the player name remains on scoreboard.  

### ISSUE THREAD

**Issue by iclassdon** [dreamstalker/rehlds#625]
Hello,  

If a player times out from the match the players name remains on the scoreboard and the latency section reads nothing. This also applies if the player is spectating and he/she happens to timeout from the server.  The player name even remains on the scoreboard after a map change.  The only way to remove is to reboot the server.  Anything I can do to resolve this?  I am running version 3.4.0.654 

BTW thank you very much for this project its much more stable then hlds.

**Comment by hashnimmo** [comment]
This bug is also in the stock HLDS. Might be a game client-side issue, don't know much about it though. Valve is claiming that they have fixed something like this issue in their last update; [source](http://steamcommunity.com/games/10/announcements/detail/1423551455081754809)

> Fixed out of date information showing in the scoreboard after level change or changing servers

**Comment by LevShisterov** [comment]
Actually, there is a bug in the engine. It doesn't sends disconnect messages to the clients while the map change. But didn't heard about this in the middle of the game with timed out clients.
