### ISSUE TITLE
Too many connect packets from your ip address

### ISSUE THREAD

**Issue by iclassdon** [dreamstalker/rehlds#626]
Hello, 

Is there anyway around this connect message "Too many connect packets from your ip address" ? Is it possible to add an exception to an ip address or a cvar I can use to get around it?  I tried raising the ip limit using this cvar "sv_rehlds_maxclients_from_single_ip" but it doesn't resolve the problem. 

Thanks

**Comment by In-line** [comment]
No, it is problem from your side.
