### ISSUE TITLE
Precache limit error message changed?

### ISSUE THREAD

**Issue by regener** [dreamstalker/rehlds#633]
So with the recent changes the precache error message became a bit useless.

With build 3.4.0.649-dev an over the precache limit error message looked like this:
```
L 07/14/2018 - 02:39:06: -------- Mapchange to de_somewhere_clean --------
Executing ReGameDLL Configuration File 
Host_Error: PF_precache_model_I: Model 'models/p_aug.mdl' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.
FATAL ERROR (shutting down): Host_Error: PF_precache_model_I: Model 'models/p_aug.mdl' failed to precache because the item count is over the 512 limit.
Reduce the number of brush models and/or regular models in the map to correct this.
```

After 3.4.0.650-dev build now it looks like this (this is latest .654):
```
L 07/14/2018 - 02:41:35: -------- Mapchange to de_somewhere_clean --------
Executing ReGameDLL Configuration File 
Host_Error: PF_setmodel_I: no precache: *243

FATAL ERROR (shutting down): Host_Error: PF_setmodel_I: no precache: *243
```

Sidequestion:
Are you planning to "include" in-line's unpreacher by default?
Would it matter if it would be built into ReHLDS instead as a metamod addon?

**Comment by Hembi** [comment]
"Host_Error: PF_setmodel_I: no precache: *132"
I also got this error message after I updated a server to the latest ReHLDS.
This message is really useless, does not indicate any useful information.

@theAsmodai After the summer vacation please check what's wrong with this part of latest build.
