### ISSUE TITLE
% Percent sign disappear in chat

### ISSUE THREAD

**Issue by Hembi** [dreamstalker/rehlds#637]
Hi,

I have a problem on a server which running on ReHLDS 3.4.0.660-dev and ReGameDLL 5.7.0.312-dev without Metamod.
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.4.0.660-dev
Build date: 20:46:02 Jul 16 2018 (1556)
Build from: https://github.com/dreamstalker/rehlds/commit/df00681

If I wrote %s to the chat, the percent sign replaced by a space char, but if I wrote "s%" it showed properly.
When I load a % char from a lang file it also disappeared wherever it is in the sentence.

**Comment by regener** [comment]
%s is for string inject, so I don't think it can be wrote as a simple text.
Use %% in lang files.

**Comment by Hembi** [comment]
I have to reopen this issue.
The % sign bug is quite fixed in the latest build (now works in chat), but if the sign is loaded from a lang file, it is still disappear.
