### ISSUE TITLE
Replace Player Name Changer  bug

### ISSUE THREAD

**Issue by Infamous2017** [dreamstalker/rehlds#646]
Hello this Problem is in last rehlds 

ReHLDS version: 3.4.0.663-dev

Metamod-r v1.3.0.127, API (5:13)
Metamod-r build: 10:49:17 Jun 15 2018 

The Plugin said "nick changed to"  But nothing happens.  Pls fix it ....

**Comment by Infamous2017** [comment]
i did.  now 665 and dont work ....

**Comment by WPMGPRoSToTeMa** [comment]
What plugin?

**Comment by Infamous2017** [comment]
https://forums.alliedmods.net/showthread.php?t=77401
