### ISSUE TITLE
Graceful shutdown on sigterm

### ISSUE THREAD

**Issue by Maxpain177** [dreamstalker/rehlds#680]
Hi. I think ReHLDS should implement graceful shutdown in `hlds_linux` launcher when receives `SIGINT` / `SIGTERM` signals.
In SRCDS it's working normally. When a server receives this signal, all players are kicking with the appropriate message.

It's very important to implement graceful shutdown in environments like Docker with Kubernetes, etc.
Sending `exit` command to the stdin it's the ugly workaround.

**Comment by Maxpain177** [comment]
Any updates?

**Comment by Maxpain177** [comment]
It's so important for our cloud of game servers

**Comment by justgo97** [comment]
did you try this ?

http://teamcity.rehlds.org/repository/download/Rehlds_Publish/20746:id/rehlds-dist-3.7.0.697-dev.zip

**Comment by Maxpain177** [comment]
Any news?
