### ISSUE TITLE
ReHLDS Crash

### ISSUE THREAD

**Issue by DarthMan** [dreamstalker/rehlds#699]
Hello there. Everytime I connect to a non-CS server that was hosted using the latest ReHLDS dev builds, the server seems to crash. It works fine until a player connects, then it crashes with no errors. The build numbers that are causing these crashes are ending in 77 and 78.

**Comment by Infamous2017** [comment]
you should add more infos.  meta list , meta version.   without those things we cant help you.

**Comment by DarthMan** [comment]
The server crashes even without metamod and AMXX running, so giving this info is useless. So if my HL1 server has as parameter in liblist.gam dlls/hl.dll it still crashes right when a player joins. That clearely means it has nothing to do with AMXX plug-ins or metamod version.

**Comment by DarthMan** [comment]
I'm using Windows Server 2008, if that's of any help.

**Comment by Infamous2017** [comment]
Which Reunion Version u are using?  Or dproto ?   I remember long time ago i had this problem with an HLDS Server + Old Dproto.

**Comment by DarthMan** [comment]
As I said, I'm not using metamod. So that means that I'm also not using dproto / ReUnion. And yes, all of my servers are Steam-only. This doesn't happen with official ReHLDS, just with latest unnofficial branches.

**Comment by eat1k** [comment]
> As I said, I'm not using metamod. So that means that I'm also not using dproto / ReUnion. And yes, all of my servers are Steam-only. This doesn't happen with official ReHLDS, just with latest unnofficial branches.

So it’s not a problem of ReHLDS if you’re not using the official latest ReHLDS version.

**Comment by DarthMan** [comment]
> 
> 
> > As I said, I'm not using metamod. So that means that I'm also not using dproto / ReUnion. And yes, all of my servers are Steam-only. This doesn't happen with official ReHLDS, just with latest unnofficial branches.
> 
> So it’s not a problem of ReHLDS if you’re not using the official latest ReHLDS version.

Fixed with latest dev build .700

**Comment by eat1k** [comment]
Just to clarify, the latest successful build is 3.6.0.672. It's the version that should be used to have no issues.
