### ISSUE TITLE
 Questions about different REHLDS Versions from Website

### ISSUE THREAD

**Issue by Infamous2017** [dreamstalker/rehlds#702]
I use this version: # 3.6.0.679 (05 Jun 19 20:22) Fix Hitbox Visulation etc.

Now i see last REHLDS is # 3.6.0.700 (Jun 30 '17 at 17:17)

What happens when I use the last REHLDS - What happens with the fixes about Hitbox Visulations? They are lost / gone after the last update?

The same applies to ReGame versions. Is it always recommended to use the last version or the one from the master? The site is so incomprehensible to me ...

**Comment by eat1k** [comment]
The last version of ReHLDS is 3.6.0.672.

**Comment by Infamous2017** [comment]
mh u dont understand my question. ...

**Comment by eat1k** [comment]
These aren't official ReHLDS versions, because these changes are not committed. These are there because of pull requests. When someone creates a pull request it's going to build automatically. So what's the actual question? You should use the latest official ReHLDS version, which is 3.6.0.672 now.

**Comment by Infamous2017** [comment]
Yes i know BUT 672 dont have the fix about Hitbox Visulation fixes...

**Comment by eat1k** [comment]
> Yes i know BUT 672 dont have the fix about Hitbox Visulation fixes...

So what's the question? The latest official build is 3.6.0.672, others are only customized versions with changes that haven't been approved yet.

**Comment by Infamous2017** [comment]
The Question is only what happens when i use the customized version with changes from 700 Version - what happens with the hitbox visulation from 679  .  they are removed then ?!

**Comment by eat1k** [comment]
> The Question is only what happens when i use the customized version with changes from 700 Version - what happens with the hitbox visulation from 679 . they are removed then ?!

I think you didn't understand how it works. It doesn't group all the changes from all authors, from all pull requests. You select one branch and download that customized version. The answer for your question: if in the branch from which you downloaded the customized ReHLDS there is no hitbox visualization, so there will not be available that thing.

**Comment by Infamous2017** [comment]
YES this was what i want to know.     So thx for the Help.    Then i will stay this version and hope that the official rehlds will be updated soon with this all newer custom fixes..   Thread can then be closed.
