### ISSUE TITLE
[WEBSERVER PROBLEM] teamcity.rehlds.org

### ISSUE THREAD

**Issue by Hembi** [dreamstalker/rehlds#718]
504 Gateway Time-out

**Comment by eat1k** [comment]
It works fine. What is the issue?

**Comment by eat1k** [comment]
> 504 Gateway Time-out

It works fine. What is the issue?

**Comment by Hembi** [comment]
> > 504 Gateway Time-out
> 
> It works fine. What is the issue?

Now it works fine again. Today it had a shutdown.

**Comment by eat1k** [comment]
> > > 504 Gateway Time-out
> > 
> > 
> > It works fine. What is the issue?
> 
> Now it works fine again. Today it had a shutdown.

It happens sometimes. You can always download the latest version from dev-cs.ru.
