### ISSUE TITLE
add -nocrashdialog parameter

### ISSUE THREAD

**Issue by Zetz512** [dreamstalker/rehlds#726]
Pls add that to avoid close manually error dialogs...

Because I can't register an error in the logs and my control panel restart this automatically

on hlds, when i start a server like a service, when that is crash dont show any dialogs/error or anything... and its close correctly and you can see in qconsole.log what happen exactly. before the control panel restart/start this automatically and i loose any error because you need to close manually a error dialog...

note: im on windows

**Comment by voed** [comment]
https://github.com/dreamstalker/rehlds/blob/65c6ce593b5eabf13e92b03352e4b429d0d797b0/rehlds/engine/sys_dll.cpp#L437

Comment this line

**Comment by Zetz512** [comment]
Ty!
