### ISSUE TITLE
Outdated Compiled Binaries

### ISSUE THREAD

**Issue by hashnimmo** [dreamstalker/rehlds#730]
So the last official commit here for ReHLDS was made back in September 22, 2019. Doesn't it get compiled immediately and added to the [compiled binary index](http://nexus.rehlds.org/nexus/content/repositories/rehlds-dev/rehlds/rehlds/)? The last update is from September 21, 2019.

Or aren't these updates ready to be released to the public?

**Comment by Mistrick** [comment]
Different time zones. Look at current commit number and the last compiled release. They have same index.

**Comment by hashnimmo** [comment]
Would be great if they can get that download page to show the same time, date as Github to avoid confusion. Anyway thanks for confirming that the latest binaries are available.
