### ISSUE TITLE
[bug?] - gametype changes from counter-strike to condition zero

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#754]
After some runtime of rehlds, the gametype somehow switches automagically from cstrike to czero:
https://i.imgur.com/PIJ4QeO.png
HLSW then shows https://i.imgur.com/LMZiftO.png
cstrike clients are still able to connect it - dont know if czero clients are.
The `hlds_run` has `GAME="valve"` and the server is initially started with `-game cstrike`, then its also shown as 'counter-strike' in the server-browser.

This also must be the source for my other reports at regamedll_cs:
https://github.com/s1lentq/ReGameDLL_CS/issues/510
https://github.com/s1lentq/ReGameDLL_CS/issues/497

`ReHLDS version: 3.7.0.693-dev`
`ReGameDLL version: 5.14.0.456-dev`
`AMX Mod X 1.9.0.5263`
`Metamod-r v1.3.0.128`
```
meta game
GameDLL info:
                 name: cstrike
                 desc: Counter-Strike 1.6
                 gamedir: /home/game/server/cstrike
                 dll file: cs.so
                 dll pathname: /home/game/server/cstrike/dlls/cs.so
```
```
AMX Modules:
          [ 1] MySQL                   1.9.0.5263  AMX Mod X Dev Team   running    
          [ 2] ReAPI                   5.12.0.192  Asmodai & s1lent     running    
          [ 3] Ham Sandwich            1.9.0.5263  AMX Mod X Dev Team   running    
          [ 4] CSX                     1.9.0.5263  AMX Mod X Dev Team   running    
          [ 5] CStrike                 1.9.0.5263  AMX Mod X Dev Team   running    
          [ 6] FakeMeta                1.9.0.5263  AMX Mod X Dev Team   running    
          [ 7] Engine                  1.9.0.5263  AMX Mod X Dev Team   running    
          [ 8] Fun                     1.9.0.5263  AMX Mod X Dev Team   running    
          [ 9] ReAimDetector           0.2.2       ReHLDS Team          running    
          [10] RegEx                   1.9.0.5263  AMX Mod X Dev Team   running    
          [11] Sockets                 1.9.0.5263  AMX Mod X Dev Team   running
```    
```
meta list
          [ 1] AMX Mod X      RUN   -    amxmodx_mm_i386.so          v1.9.0.5263      ini  Start ANY  
          [ 2] WHBlocker      RUN   -    whblocker_mm_i386.so        v1.5.696         ini  Chlvl ANY  
          [ 3] MySQL          RUN   -    mysql_amxx_i386.so          v1.9.0.5263      pl1  ANY   ANY  
          [ 4] ReAPI          RUN   -    reapi_amxx_i386.so          v5.12.0.192-dev  pl1  ANY   Never
          [ 5] Ham Sandwich   RUN   -    hamsandwich_amxx_i386.so    v1.9.0.5263      pl1  ANY   ANY  
          [ 6] CSX            RUN   -    csx_amxx_i386.so            v1.9.0.5263      pl1  ANY   ANY  
          [ 7] CStrike        RUN   -    cstrike_amxx_i386.so        v1.9.0.5263      pl1  ANY   ANY  
          [ 8] FakeMeta       RUN   -    fakemeta_amxx_i386.so       v1.9.0.5263      pl1  ANY   ANY  
          [ 9] Engine         RUN   -    engine_amxx_i386.so         v1.9.0.5263      pl1  ANY   ANY  
          [10] Fun            RUN   -    fun_amxx_i386.so            v1.9.0.5263      pl1  ANY   ANY  
          [11] ReAimDetector  RUN   -    reaimdetector_amxx_i386.so  v0.2.2           pl1  ANY   Never
```

**Comment by fred0r** [comment]
although i was of the opinion that all my currently used amxx plugins are up to date, there were a lot running compiled on some very ancient amxx-versions below the amxx-plugin folder and many of these relied on `hamsandwich`/`fakemeta`.
now 'everything' is recompiled and until now it didnt happen again.

**Comment by eat1k** [comment]
Do you have this issue without AMX Mod X?

**Comment by fred0r** [comment]
Until now i didnt try without AmxModX, but now i created a copy of the server for testing.
The problem will be, that there will be not so many players, because of no AmxModX.

> now **everything** is recompiled and ever since it didnt happen again.

It just switched again to condition-zero after a uptime of ~1650 minutes and ~450 users.

**Comment by eat1k** [comment]
It's very strange that only you have this issue. It can be of the plugins that are on your server. We don't know what plugins are on your server.

**Comment by fred0r** [comment]
```
Currently loaded plugins:
       name                    version     author            file             status
 [  1] AMXBans                 5.0         YoMama/Lux & lan  amxbans5.amxx    running
 [  2] Hide                    1.1         xPaw              hide.amxx        running
 [  3] Admin Base              1.9.0.5263  AMXX Dev Team     admin.amxx       running
 [  4] Admin Commands          1.9.0.5263  AMXX Dev Team     admincmd.amxx    running
 [  5] Admin Help              1.9.0.5263  AMXX Dev Team     adminhelp.amxx   running
 [  6] Ultimate RSlots         1.0         OneEyed           ultimate_rslot.  running
 [  7] Multi-Lingual System    1.9.0.5263  AMXX Dev Team     multilingual.am  running
 [  8] Menus Front-End         1.9.0.5263  AMXX Dev Team     menufront.amxx   running
 [  9] Commands Menu           1.9.0.5263  AMXX Dev Team     cmdmenu.amxx     running
 [ 10] Players Menu            1.9.0.5263  AMXX Dev Team     plmenu.amxx      running
 [ 11] Maps Menu               1.9.0.5263  AMXX Dev Team     mapsmenu.amxx    running
 [ 12] Admin Chat              1.9.0.5263  AMXX Dev Team     adminchat.amxx   running
 [ 13] Anti Flood              1.9.0.5263  AMXX Dev Team     antiflood.amxx   running
 [ 14] Info. Messages          1.9.0.5263  AMXX Dev Team     imessage.amxx    running
 [ 15] Admin Votes             1.9.0.5263  AMXX Dev Team     adminvote.amxx   running
 [ 16] Pause Plugins           1.9.0.5263  AMXX Dev Team     pausecfg.amxx    running
 [ 17] Stats Configuration     1.9.0.5263  AMXX Dev Team     statscfg.amxx    running
 [ 18] Items Restrict          1.1         s1lent            items_restrict.  running
 [ 19] StatsX                  1.9.0.5263  AMXX Dev Team     statsx.amxx      running
 [ 20] CS Misc. Stats          1.9.0.5263  AMXX Dev Team     miscstats_mod.a  running
 [ 21] gameME Plugin           2.4         TTS Oetzel & Goe  gameme_cstrike.  running
 [ 22] Map Spawns Editor       1.0.16      iG_os             Map_Spawns_Edit  running
 [ 23] Loading Sound           0.1         Fusion            loadsound0.3.am  running
 [ 24] Admin ESP               1.5b_mini   KoST              admin_esp_mini.  running
 [ 25] LAN Notifier            1.0a        Brad Jones        lann.amxx        running
 [ 26] Play or Be Kicked       1.5.243     Brad Jones        pbk1.5.243.amxx  running
 [ 27] Auto Restart vl         1.4         vato loco [GE-S]  auto_restart_vl  running
 [ 28] Sank Sounds Plugin      1.6.6d      White Panther, L  sank_sounds_1.6  running
 [ 29] Team Balancer           1.8b3       Ptahhotep         ptb-1.8b3.amxx   running
 [ 30] AWP/AUTO Limit (Team/W  1.60        SD/MG/DS/KWo      sniperlimit.amx  running
 [ 31] High Ping Kicker        1.0         Shadow/Bo0m!      amx_hpk.amxx     running
 [ 32] JETB                    0.5         Janzert           jetb.amxx        running
 [ 33] AdThemes                1.8         Vet(3TT3V)        adthemes1.8.amx  running
 [ 34] Descriptive 'Fire in t  0.1         VEN               descriptive_fir  running
 [ 35] Flash Remote Control    12.0        OT                flashbang_remot  running
 [ 36] Alltalk Limit           0.1         dev00             alltalklimit.am  running
 [ 37] HLTV AutoRecord         1.7         Dr.Aft            hltv_autorecord  running
 [ 38] Reconnect Features      0.2.4 BETA  ConnorMcLeod      reconnect_featu  running
 [ 39] Files Check             1.0         ConnorMcLeod      filescheck.amxx  running
 [ 40] Galileo                 v5.9.1-929  Brad Jones/Addon  galileo.amxx     running
 [ 41] scorediffcmd            0.1         pietrmar          scorediff.amxx   running
 [ 42] ReAimDetector API       0.2.2       ReHLDS Team       reaimdetector.a  running
 [ 43] [ReAPI] AdminFreeLook   1.0         ReHLDS Team       adminfreelook.a  running
 [ 44] ATAC                    3.0.1       ATAC Team         atac.amxx        running
 [ 45] Slap                    1.1         ATAC Team         atac_slap.amxx   running
 [ 46] Slap2One                1.1         ATAC Team         atac_slap2one.a  running
 [ 47] Slay                    1.1         ATAC Team         atac_slay.amxx   running
 [ 48] Spawn Slay              1.0         ATAC Team         atac_spawnslay.  running
 [ 49] Hud Messages            1.1         ATAC Team         atac_hudmsg.amx  running
 [ 50] Team Attack             1.0         ATAC Team         atac_ta.amxx     running
 [ 51] ATAC AMXBans            1.1         ATAC Team         atac_amxbans.am  running
```
There are two 'custom' plugins:
`[ 36] Alltalk Limit` -> Turns on/off `sv_alltalk` when there are less/more than `'n'` players
`[ 41] scorediffcmd ` -> Enables `PTB 1.8b3` [ 29] if one team has more than `'n'` wins compared to opponent team.

**Comment by fred0r** [comment]
For the first time i recognized, that it switched back to `counter-strike` without restarting the hlds-process.
Now HLWS again shows: https://i.imgur.com/aEGnQ4d.png
Uptime was ~1818 minutes / ~550 users.

**Comment by fred0r** [comment]
May it be possible, that someone provides some amxx-plugin, which monitors the change of the 'gamename' ? 
Maybe its also map-related that this change is happening, so that plugin may/should should also log each map which is running.

**Comment by fred0r** [comment]
from now on i log every minute via crontab with:
`printf "%s %s\n" "$(date)" "$(quakestat -nh -R -a2s x.x.x.x:PORT)" >> log.txt 2>&1`

**Comment by fred0r** [comment]
Looks like its happening after `de_aztec`, `de_dust` or `de_dust2` are finished  - but not every time.
Maybe the Amxx-Plugin `[ 33] AdThemes` triggers it:
https://forums.alliedmods.net/showthread.php?p=456368
The purpose of that Plugin is to only cover the 'Advertisements' on Walls, which were added on these 3 Maps by Valve years ago.

**Comment by fred0r** [comment]
Since removing this Plugin it didnt happen again.

**Comment by fred0r** [comment]
Well . .. it happend again:
```
Mi 1. Apr 21:49:01 CEST 2020 x.x.x.x:27015    1/25  0/0  de_flow_b4      3 / 2  cstrike Server-Name
        protocol=30,gamedir=cstrike,gamename=Counter-Strike,bots=0,dedicated=1,sv_os=linux,secure=1,version=1.1.2.7/Stdio,game_port=27015
Mi 1. Apr 21:50:01 CEST 2020 x.x.x.x:27015    1/25  0/0  de_flow_b4      5 / 2  cstrike Server-Name
        protocol=30,gamedir=cstrike,gamename=Counter-Strike,bots=0,dedicated=1,sv_os=linux,secure=1,version=1.1.2.7/Stdio,game_port=27015
Mi 1. Apr 21:51:01 CEST 2020 x.x.x.x:27015    2/25  0/0  de_flow_b4      1 / 2  cstrike Server-Name
        protocol=30,gamedir=cstrike,gamename=Counter-Strike,bots=0,dedicated=1,sv_os=linux,secure=1,version=1.1.2.7/Stdio,game_port=27015
Mi 1. Apr 21:52:01 CEST 2020 x.x.x.x:27015    1/25  0/0  de_aztec      1 / 2  cstrike Server-Name
        protocol=30,gamedir=cstrike,gamename=Condition Zero,bots=0,dedicated=1,sv_os=linux,secure=1,version=1.1.2.7/Stdio,game_port=27015
Mi 1. Apr 21:53:01 CEST 2020 x.x.x.x:27015    1/25  0/0  de_aztec     10 / 2  cstrike Server-Name
        protocol=30,gamedir=cstrike,gamename=Condition Zero,bots=0,dedicated=1,sv_os=linux,secure=1,version=1.1.2.7/Stdio,game_port=27015
Mi 1. Apr 21:54:02 CEST 2020 x.x.x.x:27015    1/25  0/0  de_aztec      3 / 2  cstrike Server-Name
        protocol=30,gamedir=cstrike,gamename=Condition Zero,bots=0,dedicated=1,sv_os=linux,secure=1,version=1.1.2.7/Stdio,game_port=27015
Mi 1. Apr 21:55:01 CEST 2020 x.x.x.x:27015    1/25  0/0  de_aztec      8 / 2  cstrike Server-Name
```
At `Mi 1. Apr 21:52:01` it switched to `Condition-Zero` and it happend again during `de_aztec`.

**Comment by fred0r** [comment]
It seems like this time i really found the AMX-Plugin causing this issue:
https://forums.alliedmods.net/showthread.php?p=595209
This plugin compares the configured files of the game server with those of the client-side.

```
while(!feof(File))
	{
		fgets(File, szFile, 63)
		trim( szFile )
		if(!szFile[0] || szFile[0] == ';' || (szFile[0] == '/' && szFile[1] == '/'))
			continue
		if(equali(szFile[strlen(szFile)-4], ".mdl"))
		{
			force_unmodified(get_pcvar_float(g_pcvarExactModel) ? force_exactfile : force_model_samebounds, {0,0,0}, {0,0,0}, szFile)
		}
		else
		{
			force_unmodified(force_exactfile, {0,0,0}, {0,0,0}, szFile)
		}
	}
	fclose(File)
}
```
After some Runtime, the Gametype of the Server changes from cstrike to czero.
It seems like this behavior started with changes of rehlds/regamedll_cs in ~January.

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r could you please execute `serverinfo` command in the server console after gamename change happens? I'd like to see the output.

**Comment by fred0r** [comment]
@WPMGPRoSToTeMa i'm so glad that it doesnt appear anymore - is it really that important ?
well - activated it again. . .

**Comment by fred0r** [comment]
Happend again and:
```
serverinfo
23:52:17 Server info settings:
         *gamedir            cstrike
```

**Comment by WPMGPRoSToTeMa** [comment]
Thanks, could you please upload the cs.so you use?

**Comment by fred0r** [comment]
Using latest regamedll_cs:
```
03:36:33 ReGameDLL version: 5.15.0.458-dev
         Build date: 11:28:46 Apr  2 2020
         Build from: https://github.com/s1lentq/ReGameDLL_CS/commit/5bbba22
```
i'm also using latest rehlds:
```
03:37:34 Protocol version 48
         Exe version 1.1.2.7/Stdio (cstrike)
         ReHLDS version: 3.7.0.695-dev
         Build date: 15:54:29 Apr  6 2020 (2186)
         Build from: https://github.com/dreamstalker/rehlds/commit/7513e71
```
amxmodx:
`03:38:33 AMX Mod X 1.9.0.5263 (http://www.amxmodx.org)`

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r did you download it from [Releases page](https://github.com/s1lentq/ReGameDLL_CS/releases)? Anyway could you please upload it here for further analysis?

**Comment by fred0r** [comment]
@WPMGPRoSToTeMa right - but here it is.



[cs.so.zip](https://github.com/dreamstalker/rehlds/files/4467650/cs.so.zip)

**Comment by fred0r** [comment]
wEEEEEEE

**Comment by WPMGPRoSToTeMa** [comment]
I suspect that it may be caused by buffer overrun in `UTIL_dtosX` functions (presumably in `UTIL_dtos2`). I've created a [PR](https://github.com/s1lentq/ReGameDLL_CS/pull/528) with a fix for these functions, lets see if this will fix your issue.

**Comment by fred0r** [comment]
i also always head the impression, that it some sort of 'buffer overrun', that why i always mentioned the current uptime/users.
thank you so much !!

**Comment by afwn90cj93201nixr2e1re** [comment]
try this version:
[cs.zip](https://github.com/dreamstalker/rehlds/files/4468766/cs.zip)

**Comment by WPMGPRoSToTeMa** [comment]
Better use this. I've downloaded it directly from the [ReGameDLL_CS'es TeamCity](http://teamcity.rehlds.org/repository/download/ReGameDLL_Publish/23663:id/regamedll-dist-5.15.0.460-dev.zip%21/bin/linux32/cstrike/dlls/cs.so?guest=1).
[cs.zip](https://github.com/dreamstalker/rehlds/files/4469460/cs.zip)

**Comment by fred0r** [comment]
Downloaded from the last Link and installed, also activated the Amxx-Plugin.
I'll report back.

**Comment by afwn90cj93201nixr2e1re** [comment]
Seem's like they r same.

> I've downloaded it directly from

Может пока у тебя rehlds.org пингуется, ты нам еще ip адрес дашь? А то у остальных как бы всё.

**Comment by fred0r** [comment]
Until now it didnt happen again.
Uptime: 704
Users: 326

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r sounds good. Lets wait for 2 weeks at least, because as I can see there was a period where you didn't have repros for about 12 days.

**Comment by fred0r** [comment]
i didnt reply, because i sorted out one amx-plugin after another on the server, after every occurrence of that bug - i'll report back.

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r by the way, could you please execute `timeleft` and `listmaps` commands in the client console when you will be on your server and send an output here?

**Comment by afwn90cj93201nixr2e1re** [comment]
Also you can try to forse timeleft to greater value to check is issue exists or no.

**Comment by afwn90cj93201nixr2e1re** [comment]
А ты востанавливал elf из памяти/дампа до полносьтю рабочего состояния?
А то я вроде почти востановил, но, из-за статической линковки с libstdc/libc некоторые фиговины теряются при чтении и в иде можно посмотреть, строки и тп всё на месте, секции тоже, но глобальные переменные и ребейз - нет. @WPMGPRoSToTeMa

**Comment by fred0r** [comment]
> @fred0r by the way, could you please execute `timeleft` and `listmaps` commands in the client console when you will be on your server and send output here?

@WPMGPRoSToTeMa since using that fixed cs.so, the gameserver didnt change again to czero.

`timeleft` in console didnt show any output.
`listmaps`:
```
----- Nominatable Maps -----
  1: as_bate  
  2: as_oilrig  
  3: awp_india  
  4: cs_1943  
  5: cs_20fighter  
  6: cs_747  
  7: cs_alps  
  8: cs_arabstreets  
  9: cs_ark  
 10: cs_assault_nod  
 11: cs_assault_twisted  
 12: cs_assault_upc  
 13: cs_bank  
 14: cs_beersel  
 15: cs_beirut  
 16: cs_bikini  
 17: cs_bikinigirl  
 18: cs_bozart  
 19: cs_camelot_mini_cz  
 20: cs_castorv11  
 21: cs_coldera  
 22: cs_coldmansion  
 23: cs_concert  
 24: cs_costabrava  
 25: cs_crackhouse  
 26: cs_deadline  
 27: cs_deagle5  
 28: csde_gimlirats  
 29: cs_docks2k_winter  
 30: cs_expo  
----- Maps 1 - 30 of 397 -----
----- Use 'listmaps 31' or 'listmaps *' for More -----
```

**Comment by fred0r** [comment]
> i didnt reply, because i sorted out one amx-plugin after another on the server, after every occurrence of that bug - i'll report back.

wanted to say; until i knew, that this filescheck-plugin is the cause of my problem, i narrowed it down by disabling each 'non-std'-plugin and that took me ~12 Days.

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r could you please add me on Steam? (I've already sent a request to you, at least I hope that I sent it to you) I have some questions regarding this issue that would be easier to solve in PM.

**Comment by fred0r** [comment]
@WPMGPRoSToTeMa no - you didnt add me - at least i see no request.
pls paste your profile url at https://crypt.is-by.us/ and i'll add you - you can delete it afterwards.

**Comment by WPMGPRoSToTeMa** [comment]
@fred0r https://steamcommunity.com/id/pr0stotema (I have no need to hide it).

**Comment by fred0r** [comment]
@WPMGPRoSToTeMa added you

**Comment by fred0r** [comment]
Since https://github.com/s1lentq/ReGameDLL_CS/pull/528 everything works fine.
