### ISSUE TITLE
Draw_ValidateCustomLogo v2

### ISSUE THREAD

**Issue by krysteksulek** [dreamstalker/rehlds#758]
Hi,

seems that problem is still not fixed. 
Result: client game crash

Server output:
Draw_ValidateCustomLogo: Bad wad dimensions tempdecal.wad
Ignoring custom decal from XXXX
SV_ProcessFile:  Unrequested decal

Client ouput (taken from condebug with developer 1):
Requesting tempdecal.wad from server
Custom resource propagation...
Decompressing file !MD5e7f8712fc013bed83c88835d133d3752 (118 -> 1024)

Server version:
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.7.0.695-dev
Build date: 15:54:29 Apr  6 2020 (2186)
Build from: https://github.com/dreamstalker/rehlds/commit/7513e71

**Comment by s1lentq** [comment]
It seems you should manually delete custom.hpk from your server, because it already contains this invalid decal
