### ISSUE TITLE
Host_Error: PF_MessageEnd_I

### ISSUE THREAD

**Issue by Vakos321575** [dreamstalker/rehlds#760]
Hello,
Shouldn't rehlds block the message limit on SayText?

`FATAL ERROR (shutting down): Host_Error: PF_MessageEnd_I: Refusing to send user message SayText of 194 bytes to client, user message size limit is 192 bytes`

`Server shutting down`

It happened that there was even such an error:

`PF_MessageEnd_I: User Msg 'Health': 195 bytes written, expected 1`

This only happens if a person has such long prefixes and sends a message with so many characters:

[Nova |MegaPremium| - 228] [Kawaleria Szatana] [FLEX] ][_(())]{(()) : say SizeL : syndicate stara taktyka powiem tyle :D ja tu gram w chuj za przeproszeniem jeszcze tych adm nie bylo

**Comment by fl0werD** [comment]
>Shouldn't rehlds block the message limit on SayText?
It's blocked, but your plugin prevent this and send custom message.

**Comment by Vakos321575** [comment]
@fl0werD 
If there is a block, it should block even if a plugin forces it.
It doesn't make sense to block if the plugin can force it.

**Comment by fl0werD** [comment]
@Vakos321575 it's blocked by crash. Maybe you try to fix plugins?

**Comment by Vakos321575** [comment]
@fl0werD 
I fixed this, but if you created this great project and we may improve it then why don't delete message which exceeds the limit from level ReHLDS? It's better solution, think about it.

**Comment by fl0werD** [comment]
@Vakos321575 and what you want to do with packet limit? 192 is not string limit. This is limit of all arguments. Which argument will be truncated?

**Comment by Vakos321575** [comment]
@fl0werD 
Delete the entire message together with the prefix no matter the plugin forces it.
This is a better option than a server crash.
If you do not want this option, please close issue.

**Comment by fl0werD** [comment]
@Vakos321575 I mean arguments from begin to end of the message.
https://github.com/dreamstalker/rehlds/blob/65c6ce593b5eabf13e92b03352e4b429d0d797b0/rehlds/common/quakedef.h#L33
https://github.com/dreamstalker/rehlds/blob/d870d6bac9714727cb739c31cdb63677ac20422c/rehlds/engine/pr_cmds.cpp#L2150
Do you see write_string or a prefix?
Delete message isn't best solution.
Add mesage logs? Who reads sys_errors.log?

**Comment by Vakos321575** [comment]
Okay i understand. Let's leave it how it is
