### ISSUE TITLE
Bug: Auto-Aim enabled in last ReHLDS version in Half-Life

### ISSUE THREAD

**Issue by rtxa** [dreamstalker/rehlds#763]
[![](http://img.youtube.com/vi/9G6O_BX4i50/0.jpg)](http://www.youtube.com/watch?v=9G6O_BX4i50)
## Youtube Video - Courtesy from tmp64

As you can see in the video, auto-aim is enabled, this happens with last version published in releases (rehlds-dist-3.7.0.695-dev). Issue isn't present in dev version 693.

Please, this should be marked high-priority, this is really gamebreaking.

Commit 693 (SV_ConnectClient: Move function Steam_NotifyClientDisconnect):
https://github.com/dreamstalker/rehlds/tree/c4cecf5f1285393dfd78219de332e02e52a5422d

Commit 694 (Add extra checks to validate WAD3 MIP-Header):
https://github.com/dreamstalker/rehlds/tree/07539e225de17bfa1c15533a6aa4918ede847fd9

Commit 695 (Don't add an invalid decal into custom.hpk, otherwise clients may crash): 
https://github.com/dreamstalker/rehlds/tree/7513e71d3bbd5f0ddb2c95ce0ce423f4ed417d81

**Comment by Dr-Strange91** [comment]
Agree !!

**Comment by WPMGPRoSToTeMa** [comment]
Does it happen in 694?

**Comment by rtxa** [comment]
> 
> 
> Does it happen in 694?

I don't remember

**Comment by fred0r** [comment]
are you sure that `sv_aim 0` is set ?

**Comment by rtxa** [comment]
> 
> 
> are you sure that `sv_aim 0` is set on the server ?

Absolutely, when sv_aim is on, it doesn't work like that, it shows you a red crosshair and moves your aim in that place, this is not the case, you just shoot in the air, close to the player and it will hit him.

**Comment by diamond-optic** [comment]
> you just shoot in the air, close to the player and it will hit him.

sounds like what happens if too high a value is used sv_clienttrace

**Comment by rtxa** [comment]
> 
> 
> > you just shoot in the air, close to the player and it will hit him.
> 
> sounds like what happens if too high a value is used for sv_clienttrace

Maybe, but I had never changed that value. By the way, looks like the issue is only present in Linux servers.

**Comment by tmp64** [comment]
So, I did some testing.
Bug: hitscanning behaves as if `sv_clienttrace` was set to a high value.

## Setup
- Game: Half-Life (mod `valve`)
- OS: Windows 10 20H2
- OS: Ubuntu 18.04 LTS
- Base HLDS: 8684 (clean, downloaded this day)
- sv_clienttrace: 3.5

## Test 0. Control - no ReHLDS
Windows: no bug
Linux: no bug

## Test 1. Version 695 - when bug was found
Windows: no bug
Linux: **bug occures**

## Test 2. Version 694 - just before that
Windows: no bug
Linux: no bug

## Test 3. Version 696 - version just after when bug was found
Windows: no bug
Linux: no bug

## Test 4. Version 723 - latest at the moment
Windows: no bug
Linux: **bug occures**

## Test 5. Version 702 - before commit 722e19d
Windows: not tested
Linux: no bug

## Test 6. Version 711 - first with commit 722e19d
Windows: not tested
Linux: no bug

## Test 7. Version 715 - between 711 and 723
Windows: not tested
Linux: not tested
This version doesn't have a release archive so I can't test it.

## Conclusion
I only have two version of what is happening.
1) Random build errors - not sure if it's possible to get the same error twice, assuming all builds are clean.
2) UB in HLDS. Some commit in 695 caused the bug to happen, some other commit in 696 made the bug disappear, some commit in 715 or 723 caused the bug to reappear again. It would be nice if someone built and tested ReHLDS with UBSanitizer and AddressSanitizer enabled.

**Comment by tmp64** [comment]
I think it solved it. Thanks for the fix!
