### ISSUE TITLE
Can you add any way to get pev_skin work on v_ models for clients?

### ISSUE THREAD

**Issue by regener** [dreamstalker/rehlds#764]
Will it be ever possible without any negatvive side effects?

**Comment by WPMGPRoSToTeMa** [comment]
This is not possible without moving (and of course re-implementing) viewmodel stuff to the server-side (and it will be laggy). Probably you can use submodels.

**Comment by regener** [comment]
Thanks for the (sad reality) information ( :D )

Submodels aren't an option, because the weapon model is split to 5 smd files (would be too large either way), that would be a really large work to properly handle that much bodies.
For example the 2 variants for each part is already 31 body varians and I barely even started it.

**Comment by WPMGPRoSToTeMa** [comment]
It can be done without duplicating smds, not sure if that can be done in .qc, but it is definitely possible by the structure of model file. You just need to duplicate submodel and mesh (where you're changing texture index) info, but refer to the same arrays of vertexes, norms, etc.

**Comment by regener** [comment]
Sadly I don't know anything about model editing, so I will give up instead.
