### ISSUE TITLE
[TFC] No Scoreboard / No Team Colour

### ISSUE THREAD

**Issue by se7entfc** [dreamstalker/rehlds#766]
When the server is started everything seems fine, but when the map changes the scoreboard is blank. Also, if you join blue team your arm is red, and the username for chat messages is not team coloured. Refer to screenshots:

Before:
![before](https://user-images.githubusercontent.com/49589118/81502421-cb9d6280-92d5-11ea-9a1f-4e665a58d6a2.png)

After:
![hlds_bug](https://user-images.githubusercontent.com/49589118/81502312-21253f80-92d5-11ea-9550-da70117be1b8.png)

**Comment by se7entfc** [comment]
Fixed!
sv_rehlds_userinfo_transmitted_fields "\ name \ model \ * sid \ * hltv"
->
sv_rehlds_userinfo_transmitted_fields "\name\model\*sid\*hltv"

**Comment by se7entfc** [comment]
EDIT:
While that fixed the blank scoreboard bug, I noticed the arm, weapon and model of the player stays red, even on blue team (again, only on map change):

before:
![before](https://user-images.githubusercontent.com/49589118/82159739-71c60b00-9888-11ea-91aa-708f358a1115.png)

after:
![after](https://user-images.githubusercontent.com/49589118/82159743-7a1e4600-9888-11ea-8880-e81ce68e479a.png)

**Comment by WPMGPRoSToTeMa** [comment]
Try to add `\bottomcolor\topcolor` to that cvar.

**Comment by se7entfc** [comment]
Fixed!
sv_rehlds_userinfo_transmitted_fields "\name\model\*sid\*hltv"
->
sv_rehlds_userinfo_transmitted_fields "\name\model\*sid\*hltv\bottomcolor\topcolor"
