### ISSUE TITLE
Disappeared elements on maps

### ISSUE THREAD

**Issue by Kpoluk** [dreamstalker/rehlds#767]
Issue found on kreedz map, you can download it here:
https://kz-rush.ru/en/maps/cs16/prochallenge2_bhop_hard
Start platform (func_wall) and bhop blocks of the first stage (func_door) became invisible.
Another example is kz_frostbite.

Version with issue:
3.7.0.695
Apr 6 2020 (2186)

Previous used version (without issue):
3.4.0.633
Jan 24 2018 (1383)

Seems like it's only on linux, windows server with 2186 build shows no problems.

**Comment by RauliTop** [comment]
Up for visibility

**Comment by Kpoluk** [comment]
Not present on current version, closing.
