### ISSUE TITLE
Subdirs not included into sdk

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [dreamstalker/rehlds#775]

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/87601033-cef10800-c6e3-11ea-86fe-ac7e6eb2538d.png)

same in regamedll too.

You should add recursive flags.

**Comment by s1lentq** [comment]
It's fine, `./public/rehlds/` moves to `./engine`

https://github.com/dreamstalker/rehlds/blob/987ee51a6bb175fe424be0a8dc6f4baefe266cb4/publish.gradle#L83-L91

**Comment by afwn90cj93201nixr2e1re** [comment]
Ok, then why we need empty dirs?
