### ISSUE TITLE
[REQUEST] Referer for sv_downloadurl

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#782]
CSS adds a Referer when redirecting a Player for the Map-Fastdownload and by this its possible to limit the Fastdownload-URL only to Players, which connect the corresponding Server.

Apache2-Example (.htaccess):
```
SetEnvIfNoCase Referer hl2://192\.168\.0\.1 allow_download
Order Deny,Allow
Allow from env=allow_download
Deny from all
```
In this CSS-Example the Server-Ip is `192.168.0.1` and only its redirected Players are allowed to fetch Files.

It would be nice to have something similar in rehlds.

**Comment by SmileYzn** [comment]
HTTP_REFERER can be spoofed

**Comment by fred0r** [comment]
:/
