### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by jaythomas77** [dreamstalker/rehlds#785]
See file:///home/opc/rehlds-3.7.0.698/rehlds/build/tmp/linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary/output.txt for all output for linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary.
linking libengine_i486.so failed.
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: skipping incompatible /opt/rh/devtoolset-8/root/usr/lib/gcc/x86_64-redhat-linux/8/libstdc++_nonshared.a when searching for -lstdc++_nonshared
/opt/rh/devtoolset-8/root/usr/libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lstdc++_nonshared
collect2: error: ld returned 1 exit status

Finished linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary, see full log file:///home/opc/rehlds-3.7.0.698/rehlds/build/tmp/linkReleaseRehldsFixesRehlds_swds_engineSharedLibrary/output.txt.

I got this error while compiling.

I am using Centos 7

**Comment by wolverine998** [comment]
What version od GCC are you using?
