### ISSUE TITLE
Fps stuck at 64 on WINDOWS 10 with reHLDS

### ISSUE THREAD

**Issue by stambeto2006** [dreamstalker/rehlds#799]
Problem with the fps of the server, when I put rehlds does not move from 64 fps, and when I put the usual hlds there is no problem. Why fix this problem and on rehlds the fps does not stay at 64 and cannot be changed.
There is no logic for one hlds to be able to do more and the other rehlds not to be able to!

OS: Windows 10 Pro 64 bit ( last updates)

**Comment by WPMGPRoSToTeMa** [comment]
Looks like related to the timer resolution change in Windows 10 2004: https://randomascii.wordpress.com/2020/10/04/windows-timer-resolution-the-great-rule-change/. In short: `timeBeginPeriod` should now be called directly from the HLDS process.

**Comment by stambeto2006** [comment]
@WPMGPRoSToTeMa And now, in order for it to work and work, does ReHLDS need to be fixed?

**Comment by TibyXD** [comment]
Same problem for me. Last reHLDS and server FPS can't get over 65, no matter what sys_ticrate and fps_max i use. Windows 10 Home, 64bit, latest update.

**Comment by stambeto2006** [comment]
@TibyXD I have the same problem!

**Comment by stambeto2006** [comment]
@s1lentq Where can the latest version be downloaded?
