### ISSUE TITLE
3.8.0.706 and sv_logaddress / GameME

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#803]
Since https://github.com/dreamstalker/rehlds/pull/802 there are Problems with  https://gameme.com
gameME is something like StatsX and since upgrading to .706 the Maps played arent updated/listed anymore:
https://imgur.com/lAPUtvh.png
After switching back to .704 it works again.

**Comment by fred0r** [comment]
there are  remote commands issued by gameME-remote side, wich server.log shows as:
```
L 01/26/2021 - 15:33:48: Rcon: "rcon 1303772711 "RCON_PW" sv_logsecret "717678"" from "REMOTE_IP:PORT"
L 01/26/2021 - 15:33:48: Rcon: "rcon 1303772711 "RCON_PW" sv_logsecret" from "REMOTE_IP:PORT"
L 01/26/2021 - 15:33:48: Rcon: "rcon 1303772711 "RCON_PW" sv_logsecret "294642"" from "REMOTE_IP:PORT"
L 01/26/2021 - 15:33:48: Rcon: "rcon 1303772711 "RCON_PW" sv_logsecret" from "REMOTE_IP:PORT"
```
server.conf:
```
log on
logaddress_add REMOTE_IP PORT
```

Amx-Plugin is https://github.com/gamemedev/plugin-amxmodx

**Comment by theAsmodai** [comment]
https://github.com/dreamstalker/rehlds/pull/804/commits/7841446b9decfdc02259a4a0141814dc1b1f01d6

**Comment by fred0r** [comment]
@theAsmodai 
Thank you - works again.
