### ISSUE TITLE
[BUG] 3.8.0.719-dev: Doors do not open correct

### ISSUE THREAD

**Issue by fred0r** [dreamstalker/rehlds#822]
i compiled the latest git on debian10 with gcc.
```
         Exe version 1.1.2.7/Stdio (cstrike)
         ReHLDS version: 3.8.0.719-dev
         Build date: 20:13:18 Mar 22 2021 (2536)
         Build from: https://github.com/dreamstalker/rehlds/commit/77f004f
```
dont know if there are 'multiple types' of doors in cs, but since running .719  the client is able to directly go through doors on maps i played and the normal 'door animation' is played after passing, but then pushing the client.
the client-player doesnt need to wait for the door to open.

**Comment by etojuice** [comment]
can confirm

**Comment by etojuice** [comment]
Caused by this change: https://github.com/dreamstalker/rehlds/commit/2e8bd9e1eb87893ece02892c4545e1ac3d4334fa#diff-a4e6f0ed06c2e074a4e02e7c29af5bde3c25b307ea5ca7080bf6534c038f1ecc

**Comment by fred0r** [comment]
Thx

**Comment by simosalis** [comment]
Hello. I'm struggling compiling the latest version of rehlds. It seems like some dependencies shouldve downloaded from the link http://nexus.rehlds.org but the website is offline. Could you kindly provide the dependencies or bring the website back alive ? 
Here is a screenshot of that is missing : https://steamuserimages-a.akamaihd.net/ugc/1733297279894628339/B65D3CDA34C2B069A4EA0BAEBED656B67317CC66/

I see you fred0r succes at compiling it under gcc, is-it possible you provide me your whole compilation folder & builders?? That will be kindly appreciated .
Thank you

**Comment by etojuice** [comment]
@simosalis click Actions

**Comment by simosalis** [comment]
And? I wish to build locally for myself, not via the usage of other things outside. So @s1lentq, provide those missing dependencies will be welcomed.

**Comment by fred0r** [comment]
@simosalis 
my system is a current debian-buster - put this into the $HOME-folder of the user which compiles rehlds:
https://mega.nz/file/JoYykJBD#rx0Q9CxraJATY306XpaPtyPhvVy1LjEGaVjmifvcbes

**Comment by simosalis** [comment]
thank you very much, i will see if this can help me to achieve my targets .
