### ISSUE TITLE
REHLDS!!!!!!!!!

### ISSUE THREAD

**Issue by Inquisitor064** [dreamstalker/rehlds#826]
Полностью не стабильный ! с 2017 года все версии! и даже через год будет так же)

**Comment by fred0r** [comment]
Что ты имеешь в виду?

**Comment by theshadowz** [comment]
Прежде чем устанавливать рехлдс, приобретите и ознакомьтесь с пособием по выравниваю рук, и рехлдс чудом станет стабильным. Всего хорошего

**Comment by fred0r** [comment]
Ты выглядишь расстроенным - что случилось?

**Comment by Inquisitor064** [comment]
я тащусь от людей которые уже 4 года занимаются ерундой! а ставить рехлдс я умею) все добра)

**Comment by RockTheStreett** [comment]
> я тащусь от людей которые уже 4 года занимаются ерундой! а ставить рехлдс я умею) всем добра)

Я тащусь от людей, которые на протяжении всей своей жизни занимаются ерундой, и при этом даже не удосужились хотя бы раз в своей жизни воспользоваться головой.
Пока не будет аргументации с твоей стороны, никто не будет тебе адекватно отвечать.

**Comment by Inquisitor064** [comment]
уже)

**Comment by sourcepowered** [comment]
Issues are not a place for you to express your personal emotions.
