### ISSUE TITLE
Не стартует REHLDS

### ISSUE THREAD

**Issue by ykpon2** [dreamstalker/rehlds#827]
Не стартует REHLDS на более старых OC
**OC:** centos-6-x86-minimal

**Ошибка при старте:**
`Error: /root/hlds5/engine_i486.so: symbol clock_gettime, version GLIBC_2.2 not defined in file libc.so.6 with link time reference
Unable to load engine, image is corrupt.
./hlds_run: line 201: gdb: command not found
email debug.log to linux@valvesoftware.com`

**Версия либы:**
`[root@vds]# ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.`

**Дампы либы**
[dump.txt](https://github.com/dreamstalker/rehlds/files/6242405/dump.txt)
[dump2.txt](https://github.com/dreamstalker/rehlds/files/6242407/dump2.txt)

**Comment by zipper-krew** [comment]
I have same issue with new CI build from https://github.com/dreamstalker/rehlds/actions/runs/693129700
