### ISSUE TITLE
VoiceTranscoder

### ISSUE THREAD

**Issue by latinas** [dreamstalker/rehlds#84]
Do you plan to rewrite VTC for ReHLDS support?

**Comment by s1lentq** [comment]
i think it depends on the author VTC.

**Comment by latinas** [comment]
And what did he say? He will?

**Comment by omertelli** [comment]
we need offical support for non-steam ..

**Comment by latinas** [comment]
Here you go http://cs.rin.ru/forum/viewtopic.php?f=29&t=69235

**Comment by s1lentq** [comment]
@latinas I have no idea

**Comment by latinas** [comment]
It's not good

**Comment by latinas** [comment]
Thx for https://github.com/s1lentq/revoice

**Comment by WPMGPRoSToTeMa** [comment]
@latinas http://cs.rin.ru/forum/viewtopic.php?f=10&t=63814?
