### ISSUE TITLE
ReHLDS Fake Player

### ISSUE THREAD

**Issue by lspublic** [dreamstalker/rehlds#859]
Yesterday i have problem with someone i see he sent some fake player when i check in log i see he have different ip but players connect in same time, and he make name of players this : https://www.youtube.com/watch?v=MWRTCk7dEoU

i try i make some photo in logs  : http://prntscr.com/1tfarvb

If somebody know any solution tell me ;)

**Comment by amsaal** [comment]
yes i confirm i have same issue. 

Logs  attached you can see clearly what is happening to ranked server.

[L0923017.log](https://github.com/dreamstalker/rehlds/files/7224761/L0923017.log)
[L0923018.log](https://github.com/dreamstalker/rehlds/files/7224762/L0923018.log)
[L0923019.log](https://github.com/dreamstalker/rehlds/files/7224763/L0923019.log)
[L0923020.log](https://github.com/dreamstalker/rehlds/files/7224764/L0923020.log)
[L0923015.log](https://github.com/dreamstalker/rehlds/files/7224759/L0923015.log)
[L0923016.log](https://github.com/dreamstalker/rehlds/files/7224760/L0923016.log)

**Comment by wopox1337** [comment]
ReHLDS is not a problem for Non-Steam clients. The problem is not reproduced on a pure ReHLDS server without Metamod.
