### ISSUE TITLE
Server doesn't show up in server list when is paused

### ISSUE THREAD

**Issue by rtxa** [dreamstalker/rehlds#862]
# Description

Basically when the server has been paused (by issuing the command `pause` and `pausable` has been enabled), it dissapears from **server list**, in other words it shows `< not responding >`.

Apparently, this is not true as you can still enter the server manually by using the command `connect` and the server IP.

# Expected behaviour

The expected behaviour would be that the server should appear in the server list even when is paused, **just like normal HLDS does.**

# Why is important to fix it

The `pause` command is a key feature for match competition in Half-Life and CS 1.6, and mods like Adrenaline Gamer. When a match has started and a player has been disconnect from the server by some reason like game crash or lost his internet connection, the remaining players will pause the server and wait for him. When the player has returned, they will unpause the server and continue with the match. But if the server **doesn't show up in the server list**, it can be misleading for the player as he can think that the server doesn't work and probably it will end up with aborting the match.

# What could be the reason

I'm not familiarized with ReHLDS code but perhaps the issue has something to do with the server not sending more responses to the client when it request server info on server pause. I'll appreciate if someone can fix it or help to lead to the fix.

**Comment by culcj95** [comment]
> Basically when the server is paused (by using the command `pause` and `pausable` is enabled) it dissapears from **server list**, in other words it shows `< not responding >`.
> 
> This can be workaround by entering the server with the console by using the command `connect`. Take into account that this issue **doesn't happen in normal HLDS.**
> 
> The `pause` command is very used in matchs (1v1, 2v2 or more) when one of the players gets disconnect by reasons like game crash or lost of internet connection, requiring to pause the match until player comesback. But if the server doesn't show up in **server list**, it can be misleading for the player and he will think that the server doesn't work when it actually does.
> 
> What is expected is that server should still be displayed even when is paused, just like normal HLDS does.
> 
> I'm not familiarezed with HLDS code but perhaps the issue is with the server not sending more responses to the client when it request server info or something like that on pause. I'll appreciate if someone can fix this or help to guide to the fix.



DID YOU FIND ANY FIX FOR THIS???? @rtxa

**Comment by culcj95** [comment]
@dreamstalker Any fix for this??

**Comment by rtxa** [comment]
@culcj95 By the moment, I haven't found the solution. But I have updated the issue to be more descriptive and easy to understand.

**Comment by abecee** [comment]
> @culcj95 By the moment, I haven't found the solution. But I have updated the issue to be more descriptive and easy to understand.

Sorry for interrupt. I've send you an email. Can you check please?

**Comment by culcj95** [comment]
> @culcj95 By the moment, I haven't found the solution. But I have updated the issue to be more descriptive and easy to understand.

Sir, can you share?

**Comment by jonathan-up** [comment]
> Basically when the server has been paused (by issuing the command pause and pausable has been enabled), it dissapears from >server list, in other words it shows < not responding >.
>Apparently, this is not true as you can still enter the server manually by using the command connect and the server IP.

this problem is cased by _reunion's query limit_ and it has now been fixed in the [reunion open source version](https://github.com/s1lentq/reunion)

**Comment by jonathan-up** [comment]
@culcj95 if you are using `reunion of open source previous versions`,

1. just set `EnableQueryLimiter = 0`
2. check [this version](https://github.com/s1lentq/reunion/releases/tag/0.2.0.6) or newer version

**Comment by jonathan-up** [comment]
@rtxa So this issue should be closed

**Comment by culcj95** [comment]
> @culcj95 if you are using `reunion of open source previous versions`,
> 
> 1. just set `EnableQueryLimiter = 0`
> 2. update to [this version](https://github.com/s1lentq/reunion/releases/tag/0.2.0.6) or newer version

Thank you soo much...

**Comment by rtxa** [comment]
@jonathan-up Genius! 👏 Thanks for the workaround and I didn't know Reunion released his source code.

Closing issue because it was related to Reunion's query limiter and fixed in latest Reunion version which I test.
