### ISSUE TITLE
Admin slowhack bypass

### ISSUE THREAD

**Issue by tinerci** [dreamstalker/rehlds#879]
we want rehlds admin slowhack bypass.

client_cmd not working
Send_Cmd stock (steam not working)

**Comment by etojuice** [comment]
there is client side protection from slowhacking

**Comment by UnrealKaraulov** [comment]
cl_filterstuffcmd 1 ?

**Comment by UnrealKaraulov** [comment]
@tinerci 
 > we want rehlds admin slowhack bypass.
> 
> client_cmd not working Send_Cmd stock (steam not working)

for what you want use client_cmd ?

**Comment by tinerci** [comment]
> @tinerci
> 
> > we want rehlds admin slowhack bypass.
> > client_cmd not working Send_Cmd stock (steam not working)
> 
> for what you want use client_cmd ?

I just want to use bind as shortcuts. Rehlds has developed so much, at least he can do that.

**Comment by UnrealKaraulov** [comment]
> > @tinerci
> > > we want rehlds admin slowhack bypass.
> > > client_cmd not working Send_Cmd stock (steam not working)
> > 
> > 
> > for what you want use client_cmd ?
> 
> I just want to use bind as shortcuts. Rehlds has developed so much, at least he can do that.

you can use 'radio1' 'radio2' 'radio3'  or 'nightvision' buttons without slowhacking

**Comment by tinerci** [comment]
> 
> 'radio1' 'radio2' 'radio3' veya 'gece görüşü' düğmelerini yavaşlatmadan kullanabilirsiniz

I think you are a systematically very unintelligent person. This came to mind already..

**Comment by UnrealKaraulov** [comment]
> > 'radio1' 'radio2' 'radio3' veya 'gece görüşü' düğmelerini yavaşlatmadan kullanabilirsiniz
> 
> I think you are a systematically very unintelligent person. This came to mind already..

you can close your server, it make your problem is solved )

**Comment by tinerci** [comment]
> 
> you can close your server, it make your problem is solved )

retarded idiot.
