### ISSUE TITLE
 Accuracy Fix

### ISSUE THREAD

**Issue by coolmans** [dreamstalker/rehlds#88]
There is such a plugin  Accuracy Fix.
https://forums.alliedmods.net/showthread.php?t=166648
which celebrates fire in the engine, if the sense to put it, or all the corrections is or will be?

**Comment by WPMGPRoSToTeMa** [comment]
This is related only to Counter-Strike gamedll, not engine.

**Comment by Maxpain177** [comment]
@coolmans Вам [сюда](https://github.com/s1lentq/ReGameDLL_CS/issues)

**Comment by coolmans** [comment]
stupid question, and where to take the already compiled so? Or how to compile?

**Comment by Maxpain177** [comment]
@coolmans Я сам не знаю, сборок нигде не видел, а собрать под linux'ом у меня так и не получилось. Буду пробовать под Windows компилировать.
