### ISSUE TITLE
Avatar not showing after hooking SV_ConnectClient function

### ISSUE THREAD

**Issue by ShadowsAdi** [dreamstalker/rehlds#888]
Hello,
I am using [this plugin](https://github.com/ShadowsAdi/AdvancedSlotReservation/blob/master/scripting/advanced_slot_reservation.sma) which is hooking [SV_ConnectClient](https://github.com/dreamstalker/rehlds/blob/master/rehlds/engine/sv_main.cpp#L2261-L2264) in pre state. If this condition [check](https://github.com/ShadowsAdi/AdvancedSlotReservation/blob/master/scripting/advanced_slot_reservation.sma#L279-L280) is passed, a connected players is kicked out from the server and when the new one is joining it does not show his steam avatar. Otherwise, if the check is not passed, it will let the player connect ( because server is not full ) and his steam avatar will show.

**Comment by Ant1Lamer** [comment]
Avatar and show STEAM_ID_LAN
