### ISSUE TITLE
Latest build broke all Steam Avatars ?

### ISSUE THREAD

**Issue by UnrealKaraulov** [dreamstalker/rehlds#902]
@s1lentq Latest build broke all Steam Avatars ? You can fix it in new build ?!

**Comment by CirovicFG** [comment]
Same problem here.. i dont see any avatar except mine.

**Comment by wopox1337** [comment]
give more info please.
- `version`
- `sv_rehlds_userinfo_transmitted_fields` value

**Comment by UnrealKaraulov** [comment]
this version : https://github.com/dreamstalker/rehlds/commit/2f0a402f9d14f05463a3c1457694fe0d57a61012

**Comment by CirovicFG** [comment]
any fixes?

**Comment by UnrealKaraulov** [comment]
I think it can't be fixed(((

**Comment by LevShisterov** [comment]
@UnrealKaraulov, why you think that it can't be fixed? I think it will be good to give a reason.

**Comment by UnrealKaraulov** [comment]
@LevShisterov I think this repository is dead...)

**Comment by CirovicFG** [comment]
Issuse is FIXED, i didn't touched anything just went to sleep, when woke up avatars were there(i didnt even restart server), but i think that happened because VAC secured icon, yesterday i didnt have one for server(before i had ) and suddenly i have it now(when avatar started working)
