### ISSUE TITLE
Can publish available for Windows file?

### ISSUE THREAD

**Issue by bluefatcat1993** [dreamstalker/rehlds#904]
Will ReHLDS continue to publish archives available for Windows?

**Comment by ShadowsAdi** [comment]
You can download Windows archives from actions artifacts: https://github.com/dreamstalker/rehlds/actions

**Comment by bluefatcat1993** [comment]
> You can download Windows archives from actions artifacts: https://github.com/dreamstalker/rehlds/actions

I don't know how to download last version file for Windows
