### ISSUE TITLE
Notification about unknown command in server console

### ISSUE THREAD

**Issue by GoDtm666** [dreamstalker/rehlds#91]
В исходнике engine/cvar.cpp функции
qboolean Cvar_Command(void)
{
	cvar_t *v;
	const char *arg0 = Cmd_Argv(0);
	const char *firstToken = Cvar_IsMultipleTokens(arg0);

	if (firstToken)
	{
		v = Cvar_FindVar(firstToken);
		if (v)
		{
			Con_Printf("\"%s\" is \"%s\"\n", v->name, v->string);
			return TRUE;
		}
	}
	else
	{
		v = Cvar_FindVar(arg0);
		if (v)
		{
			if (Cmd_Argc() == 1)
			{
				Con_Printf("\"%s\" is \"%s\"\n", v->name, v->string);
			}
			else
			{
				if (v->flags & FCVAR_SPONLY && g_pcls.state >= ca_connecting && g_pcl.maxclients > 1)
				{
					Con_Printf("Can't set %s in multiplayer\n", v->name);
				}
				else
				{
					Cvar_Set(v->name, Cmd_Argv(1));
				}
			}

			return TRUE;
		}
	}

	return FALSE;
}

внести 2 раза код
else
{
	Con_Printf("unknown command \"%s\"\n", arg0);
}

qboolean Cvar_Command(void)
{
	cvar_t *v;
	const char *arg0 = Cmd_Argv(0);
	const char *firstToken = Cvar_IsMultipleTokens(arg0);

	if (firstToken)
	{
		v = Cvar_FindVar(firstToken);
		if (v)
		{
			Con_Printf("\"%s\" is \"%s\"\n", v->name, v->string);
			return TRUE;
		}
		else
		{
			Con_Printf("unknown command \"%s\"\n", arg0);
		}
	}
	else
	{
		v = Cvar_FindVar(arg0);
		if (v)
		{
			if (Cmd_Argc() == 1)
			{
				Con_Printf("\"%s\" is \"%s\"\n", v->name, v->string);
			}
			else
			{
				if (v->flags & FCVAR_SPONLY && g_pcls.state >= ca_connecting && g_pcl.maxclients > 1)
				{
					Con_Printf("Can't set %s in multiplayer\n", v->name);
				}
				else
				{
					Cvar_Set(v->name, Cmd_Argv(1));
				}
			}

			return TRUE;
		}
		else
		{
			Con_Printf("unknown command \"%s\"\n", arg0);
		}
	}

	return FALSE;
}

Результат этому делу.
Вводим не известную команду hg
и получаем сообщение.

unknown command "hg"

Так будет удобнее :)
Хотелось бы это видеть в релизе.
С уважением индус кодерь ;)

**Comment by theAsmodai** [comment]
Use english please. Why do you need unknown command message? Also Cvar_Command is a bad choice for this notification.

**Comment by GoDtm666** [comment]
To output a message to the console server when a user enters an invalid command. This is done on the engine, Source, very easy to work with these teams. Or anything wrong with this I do not see that the message is displayed in the server console on the wrong team than if guess hung server or not, at least I determined when I worked with Source.

Чтобы выводило сообщение в консоль сервера, когда пользователь вводит неверную команду. Это реализовано на движке Source, очень удобно работать с этими командами. Ни чего плохого в этом не вижу, чтобы выводило сообщение в консоль сервера о неверной команде, чем ежели гадать завис сервер или нет, по крайне мере я так определял, когда работал с Source.

**Comment by GoDtm666** [comment]
sv_cheats 1
L 10/30/2015 - 15:47:07: Server cvar "sv_cheats" = "1"
"sv_cheats" changed to "1"
L 10/30/2015 - 15:47:09: World triggered "Round_Start"
sv_cheat 1
unknown command "sv_cheat"

Conveniently same way

**Comment by s1lentq** [comment]
@GoDtm666 I think this will useful but with only developer mode

**Comment by GoDtm666** [comment]
Какой еще developer mode?
Администраторы серверов будут девелопить вводы команд, чтобы просто узнать ввел он правильно или нет? Не смешно ли?

What other developer mode?
Server administrators will Develop enter commands just to find out he has entered is correct or not? Is not it funny?

**Comment by s1lentq** [comment]
@GoDtm666 I mean using developer is "1" or command line "-dev" for output detailed information

**Comment by GoDtm666** [comment]
Ну я понял на счет этой переменной, но не каждый догадается активировать режим разработчика, чтобы понять где проблема, если еще и догадается.
Это получается обычному пользователю сервера нужна знать весь код сервера, чтобы понимать в какой момент нужно, что-то активировать. Это лишняя нагрузка на конечных пользователей сервера.
Well, I realized at the expense of the variable, but not everyone guess enable developer mode to understand where the problem is, if you even guess.
It turns out the average user needs to know the whole server server code in order to understand at what point you need something to activate. This is an extra burden on the end users of the server.

**Comment by zik32** [comment]
I support the idea godtm666.

**Comment by s1lentq** [comment]
@GoDtm666 

Now imagine, if you will need to temporarily disable amxx plugin/module which registers cvars and cvars are in amxx prescribed.cfg/server.cfg, you will receive a stream of useless information about "unknown cvars", this would be quite uncomfortable without the ability to turn it off.

p.s my point of view

**Comment by zik32** [comment]
n a world where the attacks are becoming more sophisticated, most people prefer hosted on hosting. Not on one host does not give access to the start line. and the developer 1 becomes useless variable

**Comment by zik32** [comment]
Maybe you do mp_logdetail 4?

**Comment by s1lentq** [comment]
@zik32 mp_logdetail refers to gamedll but not to the engine.

**Comment by GoDtm666** [comment]
You decide, I have no time to prove you useful ideas with sketches code. (programmer written code will understand without explanation.) All that I could help to explain, I have provided above.

When trying to post a product, work and so on, think about the end user that they can face the problem that they do not understand what's going on!

Example:
Aida enter the command entered! pff does not work! What have I done wrong ?? again introduced does not work, so what ?? ..........
Should come down to 2 minutes, aah, yes, I wrote the same mistake in a variable. Pfft. Humor program without displaying errors.

Personally, I see the unseen problem with the confirmation of the correct team.

Do not know, do not work with other engines do not deal with people who do not see their mistakes Why not working. Well, okay.




Решать Вам, у меня нет времени доказывать Вам полезные идеи с набросками кода. (программист сам поймет написанный код без объяснения.) Все, что я мог помочь и объяснить, я предоставил выше.

Когда выкладываете продукт, работу и тд, задумайтесь о конечных пользователей, что они могут столкнутся с проблемой которой они не поймут, что происходит! 

Пример:
Айда введу команду, ввел! пфф не работает! Что же я не так сделал?? опять ввел не работает, да, что такое??..........
Cпустя 2 минуты, ааа да, я же ошибку написал в переменной. Пфф. Юмор работы программы без вывода ошибок.

Лично я вижу невидимою проблему с подтверждением об верной команде.

Не понимаете, не работали с другими движками, не сталкивались с людьми, которые не видят свои же ошибки почему неработает. Ну и ладно.

**Comment by theAsmodai** [comment]
@GoDtm666 this is the default engine behavior, which all used to.

**Comment by GoDtm666** [comment]
И что?
В стандартном движке тоже нет фиксов и защит, которые Вы внедрили. Ведь привыкли ставить всякие плагины и защищать сервер.
So what?
The standard engine is also no fixes and protections that you have implemented. It used to put all sorts of plug-ins and to protect the server.

Это тоже самое дело привычки.
This same matter of habit.

**Comment by theAsmodai** [comment]
sv_echo_unknown_cmd:
0 - default engine behaviour
1 - echo unknown commands only from the server console
2 - echo all unknown commands
