### ISSUE TITLE
motdfile console variable can't be empty: FATAL ERROR (shutting down): COM_LoadFile: Bad path length:

### ISSUE THREAD

**Issue by SmileYzn** [dreamstalker/rehlds#919]
I was used motdfile variable to control motd.txt file name.

But for some reason in Linux (In Winodws works) the motdfile "" (Empty) cause a FATAL ERROR:

<code>
FATAL ERROR (shutting down): COM_LoadFile: Bad path length:

Segmentation fault
</code>

Ps. i used as empty variable to avoid MOTD to be show to players.

Someone can confirm this?

**Comment by PM32** [comment]
Testing on a random server:
`motdfile
"motdfile" is "motd.txt"
motdfile ""
motdfile
"motdfile" is ""
version
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
ReHLDS version: 3.8.0.711-dev
Build date: 13:13:38 Feb  6 2021 (2492)
Build from: https://github.com/dreamstalker/rehlds/commit/722e19d`

**Comment by SmileYzn** [comment]
The crash occours when player enter in game with motdfile ""

Tested on 3.11.0.776 - Latest
