### ISSUE TITLE
SV_RunThink edict free bug

### ISSUE THREAD

**Issue by a1batross** [dreamstalker/rehlds#92]
In sv_phys.cpp:124 edict must be cleared by FL_KILLME flag. But here must be FL_SPECTATOR flag. 

Let's look into HLSDK:
https://github.com/ValveSoftware/halflife/blob/5d761709a31ce1e71488f2668321de05f791b405/dlls/util.cpp#L1558

UTIL_Remove delete entity from server by setting FL_KILLME flag, and engine cleares it. When FL_SPECTATOR is only set for spectators.

**Comment by theAsmodai** [comment]
Thanks.
