### ISSUE TITLE
rehlds max player?

### ISSUE THREAD

**Issue by PQFitz** [dreamstalker/rehlds#925]
just out of curiosity, is there a way to setup a cs 1.6 server to handle more then 32 players?

if not, is there a practical way it could be done?

**Comment by hajimura** [comment]
Nope. There're too many limits linked with 32 number on the rehlds. Client-side also must be changed to handle more than 32 player. In other words, this feature will be implemented not soon, if the feature ever will be implemented

**Comment by PQFitz** [comment]
I see, thank you
