### ISSUE TITLE
No windows version?

### ISSUE THREAD

**Issue by Skumek** [dreamstalker/rehlds#938]
Why did you stop compiling for windows? Is there a guide how to do it yourself?

**Comment by ViBE-HU** [comment]
basically nobody use Windows for CS/HL servers? i guess it's possible to build but in general Windows is bad for game servers.

**Comment by Skumek** [comment]
I use local SteamCMD servers for testing mods as its much faster for working than ftp linux. They stopped compiling for windows at version 3.11x....

**Comment by pepepepito0147** [comment]
still possible to download the latest build here see "([Actions](https://github.com/dreamstalker/rehlds/actions))" locate the latest version then go to "Artifacts" both linux32 and win32 are available

**Comment by Skumek** [comment]
Thanks alot :)
