### ISSUE TITLE
make for windows

### ISSUE THREAD

**Issue by TheArtemMaps** [dreamstalker/rehlds#943]
please?

**Comment by TheArtemMaps** [comment]
> [#938 (comment)](https://github.com/dreamstalker/rehlds/issues/938#issuecomment-1241460604)

well, there's still some windows servers, windows is great too i guess. for example, i want to make a rehlds serve on windows (not hosting i have a os windows) and play with bots there or with friends through vpn. but how i can launch linux app on windows? exactly, there is no way.

**Comment by StevenKal** [comment]
The previous user linked a comment related to your problem, where you can download Windows files (& he explained how), no need to use workaround by trying to put Linux on Windows.
Just go [there](https://github.com/dreamstalker/rehlds/actions/runs/3083980652) & click on "win32" link at the end to get Windows files.
