### ISSUE TITLE
windows rehlds issue

### ISSUE THREAD

**Issue by Escap3d** [dreamstalker/rehlds#956]
rehlds windows build version can not compile 3.12.0.780 
![Screenshot 2023-03-10 194026](https://user-images.githubusercontent.com/78939962/224345192-4afdde6b-2b5f-4460-8b6f-3e928cb6cb28.png)

**Comment by rx1983** [comment]
windows build ?

**Comment by Escap3d** [comment]
> windows build ?

yes its windows build 3.12.0.780 but not show 780 in this build after compile

**Comment by rx1983** [comment]
not work with CSDM ....
