### ISSUE TITLE
update latest version plzz

### ISSUE THREAD

**Issue by Escap3d** [dreamstalker/rehlds#963]
no one can update latest version

3.13. latest for bug and crash fixes and share 

(Build date: 10:37:13 Feb 28 2023 (3244)
Version 3.13.789 TESTING: fix crash due to SZ_GetSpace console overflow)

(Build date: 20:05:57 Feb 27 2023 (3243)
Version: 3.13.786 Add SV_ClipToLinks_Point to get rid of redundant checks)

which one i use ??

**Comment by justgo97** [comment]
use the one here https://github.com/dreamstalker/rehlds/releases/latest/

The others are experimental and might not work as intended so use them at your own risk.
