### ISSUE TITLE
Server shutdown

### ISSUE THREAD

**Issue by Gawnz1** [dreamstalker/rehlds#968]
Hello guys,

I am using a linux system (Debian/Centos 7) and I want to shutdown the server after some certain time (automatically), but when I type in console "quit" or "exit" - the server restarts (the auto restart form hlds_run).

When I type "shutdownserver" everything is fine, it disconnects the client and the server is going offline. 
The problem with "shutdownserver" command is that the server still stays alive.

Is there any workaround or some "graceful shutdown" guide without accessing the SSH and stopping it manually by killing the screen session.

I will be happy if someone shares some experience or some idea/workaround.

**Comment by wopox1337** [comment]
You can just terminate without any console cmd - it will be graceful
https://github.com/dreamstalker/rehlds/issues/680

**Comment by Nord1cWarr1or** [comment]
> (the auto restart form hlds_run)

It can be disabled by `-norestart`

**Comment by Gawnz1** [comment]
@wopox1337 - Can I somehow pass a server command through AMXX that will shut it down?

@Nord1cWarr1or - Thats the last one I will do if is no other way. Just want to keep the auto restart if the server crashes in that time window to come back again. If I can't find other solution, maybe will stick with -norestart

The main idea is: Start the server, then count certain time for example lets say 10 minutes and if no players are connected when the timer ends, execute the shutdown function.

**Comment by Gawnz1** [comment]
Well I ended up using `-norestart` and it works as I want.
