### ISSUE TITLE
Update Official Rehlds!

### ISSUE THREAD

**Issue by Escap3d** [dreamstalker/rehlds#970]
Please Release official new version update in release section

**Comment by RouisIbra** [comment]
Compile it yourself, the latest commit is stable.

**Comment by Escap3d** [comment]
> Compile it yourself, the latest commit is stable.

I am not expert for compiling

**Comment by nachoverdon** [comment]
https://github.com/dreamstalker/rehlds/actions/runs/4913631651

You'll find the latest Windows and Linux build in the Artifacts sections
