### ISSUE TITLE
[Feature Request] Cross-game compatibility

### ISSUE THREAD

**Issue by SmilexGamer** [dreamstalker/rehlds#975]
As you all know, both Counter-Strike and Condition Zero have the same game dlls and little to no difference in terms of network messages.
With that in mind, I come here to ask you if it would be possible to add a feature that allows a server to accept both cstrike and czero at the same time.

**Comment by di57inct** [comment]
++ unite the communities

**Comment by StevenKal** [comment]
Seems like you would like to see CS v1.6 & CZ users able to join "one server" that could handle both games at the same time.

**Comment by SmilexGamer** [comment]
> Seems like you would like to see CS v1.6 & CZ users able to join "one server" that could handle both games at the same time.

Yes, that's exactly my request - that is, if possible to be achieved.

**Comment by s1lentq** [comment]
It's nearly impossible to implement this.
The main difficulty lies in the fact that the mod of the game is checked on the client-side.
When trying to connect to a server with a different game, the client disconnects itself.
From the server-side, this can only be implemented by spoofing the game and also if the client tells the server during the connection stage which game it is running on (e.g., through setinfo), but this does not happen.
Thus, it's impossible.

**Comment by SmilexGamer** [comment]
> It's nearly impossible to implement this. The main difficulty lies in the fact that the mod of the game is checked on the client-side. When trying to connect to a server with a different game, the client disconnects itself. From the server-side, this can only be implemented by spoofing the game and also if the client tells the server during the connection stage which game it is running on (e.g., through setinfo), but this does not happen. Thus, it's impossible.
> 
> p.s note that cross-game compatibility can cause issues with `mp_consistency 1` due to the different content of the game

I see, just a last question - could the server read the client's `gamedir` cvar and spoof its own game before the client drops the connection?

p.s yes, this feature would only properly work in a server with `mp_consistency 0`

**Comment by cris840** [comment]
> It's nearly impossible to implement this. The main difficulty lies in the fact that the mod of the game is checked on the client-side. When trying to connect to a server with a different game, the client disconnects itself. From the server-side, this can only be implemented by spoofing the game and also if the client tells the server during the connection stage which game it is running on (e.g., through setinfo), but this does not happen. Thus, it's impossible.
> 
> p.s note that cross-game compatibility can cause issues with `mp_consistency 1` due to the different content of the game

So why not create a mod for the client as well and those who prefer to play from cszero can install it?

**Comment by s1lentq** [comment]
> So why not create a mod for the client as well and those who prefer to play from cszero can install it?

As I said, this can be done only through userinfo, i.e. through setinfo. Based on this, the server can understand who to replace the game with cstrike, and who with czero.

**Comment by SmilexGamer** [comment]
> > So why not create a mod for the client as well and those who prefer to play from cszero can install it?
> 
> As I said, this can be done only through userinfo, i.e. through setinfo. Based on this, the server can understand who to spoofing the game with cstrike, and who with czero.

So, in a way, it's possible but would require the client to manually set a key on the setinfo to identify which game it's playing - `cstrike` or `czero`

**Comment by s1lentq** [comment]
> > > So why not create a mod for the client as well and those who prefer to play from cszero can install it?
> > 
> > 
> > As I said, this can be done only through userinfo, i.e. through setinfo. Based on this, the server can understand who to spoofing the game with cstrike, and who with czero.
> 
> So, in a way, it's possible but would require the client to manually set a key on the setinfo to identify which game it's playing - `cstrike` or `czero`

Yes it's the only way
It is absolutely impossible without the involving of the client himself in this process

**Comment by SmilexGamer** [comment]
> > > > So why not create a mod for the client as well and those who prefer to play from cszero can install it?
> > > 
> > > 
> > > As I said, this can be done only through userinfo, i.e. through setinfo. Based on this, the server can understand who to spoofing the game with cstrike, and who with czero.
> > 
> > 
> > So, in a way, it's possible but would require the client to manually set a key on the setinfo to identify which game it's playing - `cstrike` or `czero`
> 
> Yes it's the only way It is absolutely impossible without the involving of the client himself in this process

So, if in the best interest for everyone, we can make a pull request for such feature.

**Comment by cris840** [comment]
> 



> > > > > So why not create a mod for the client as well and those who prefer to play from cszero can install it?
> > > > 
> > > > 
> > > > As I said, this can be done only through userinfo, i.e. through setinfo. Based on this, the server can understand who to spoofing the game with cstrike, and who with czero.
> > > 
> > > 
> > > So, in a way, it's possible but would require the client to manually set a key on the setinfo to identify which game it's playing - `cstrike` or `czero`
> > 
> > 
> > Yes it's the only way It is absolutely impossible without the involving of the client himself in this process
> 
> So, if in the best interest for everyone, we can make a pull request for such feature.

It would be pretty amazing if they make it possible.

**Comment by di57inct** [comment]
well that was easy

**Comment by cris840** [comment]
> well that was easy

Maybe in the future reunion will be updated so that the server queries are compatible with cszero, steam auth should also be fixed

**Comment by SmilexGamer** [comment]
> > well that was easy
> 
> Maybe in the future reunion will be updated so that the server queries are compatible with cszero, steam auth should also be fixed

yes, the steam auth isn't working. tested with a czero client connecting to a cstrike server.

**Comment by rtxa** [comment]
From where is send the message `"Server is running game <MODNAME>. Restart in that game to connect"`. I'm trying to modify the client code to allow cross-game compatibility but not sure where to look.
