### ISSUE TITLE
My server is crashing

### ISSUE THREAD

**Issue by Alexander-56** [dreamstalker/rehlds#979]
Hi. I'm using ReGameDLL_CS and Rehlds on my server, without plugins. I have Amx mod x installed on the server. I start my server with commands [ hlds.exe -console -game cstrike -noipx +map de_dust +maxplayers 24 ] because of ipx. The server is working, until I try to join, because after it immediately crashes. I would appreciate a little help. :)

**Comment by dystopm** [comment]
@Alexander-56 

SO info?
ReHLDS version? (version in console)
ReGameDLL version? (game version in console)
AMXX version? (amxx version in console)
Any log output? Crash dump info? etcétera

**Comment by Alexander-56** [comment]
Sorry!
AMX Mod X version 1.8.2
ReGameDLL version: 5.22.0.593-dev
ReHLDS version: 3.12.0.780
I cannot find more info.

**Comment by dystopm** [comment]
> @dystopm
> 
> Sorry! AMX Mod X version 1.8.2 ReGameDLL version: 5.22.0.593-dev ReHLDS version: 3.12.0.780 I cannot find more info.

Use AMXX 1.9, AFAIK is the first one officially supporting Re binaries

**Comment by wopox1337** [comment]
Nothing to do with rehlds. The problem is the extension.

**Comment by Alexander-56** [comment]
It's working now. I never knew there are newer versions of amxmodx. 
Thank you guys!
