### ISSUE TITLE
25th Anniversarry compatibility

### ISSUE THREAD

**Issue by andreiseverin** [dreamstalker/rehlds#999]
Hello,

Is ReHLDS compatible with the new 25th Anniversary update?

**Comment by rndtrash** [comment]
it will be compatible as soon as #1000 is merged

**Comment by stamepicmorg** [comment]
> it will be compatible as soon as #1000 is merged

merged: https://github.com/dreamstalker/rehlds/commit/3f19bc1d3e254d9665893e93383487ba03d29f2a

**Comment by rndtrash** [comment]
it works great on my server with metamod and amx, so i guess it is 100% compatible now

**Comment by rndtrash** [comment]
I guess it's no longer compatible with the newest hlds_linux:

```
Error:/home/steam/steamcmd/hl/engine_i486.so: undefined symbol: SteamGameServer_Init
Unable to load engine, image is corrupt.
```

**Comment by rndtrash** [comment]
![image](https://github.com/dreamstalker/rehlds/assets/6745157/80707aa4-333d-4652-adff-7709346e5a9e)
They've removed the unsafe version of Init

**Comment by Ndrs24** [comment]
It worked for me to return the version previous to 25h
steamcmd:
app_set_config 90 mod cstrike
app_update 90 -beta steam_legacy validate

**Comment by andreiseverin** [comment]
@rndtrash any chance you still have that working build?

**Comment by rndtrash** [comment]
> @rndtrash any chance you still have that working build?

You can try downloading an older version, it's still on the Steam servers: https://steamdb.info/app/70/history/?changeid=21243851 https://www.reddit.com/r/Steam/comments/611h5e/guide_how_to_download_older_versions_of_a_game_on/

**Comment by 0Ky** [comment]
On Debian I've installed the latest dev build of reHLDS onto the latest HLDS release and it returns the following error message:
```
Error: /home/user/HLDS/engine_i486.so: undefined symbol: SteamGameServer
Unable to load engine, image is corrupt.
```
I suppose certain symbols are referenced in `engine_i486.so` but are not defined in any of the linked libraries.
```
$ ldd -r engine_i486.so
        linux-gate.so.1 (0xf7f43000)
        libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7812000)
        librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xf780d000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7705000)
        libsteam_api.so => /home/user/HLDS/././libsteam_api.so (0xf76b8000)
        libstdc++.so.6 => /home/user/HLDS/././libstdc++.so.6 (0xf75e5000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf73b0000)
        /lib/ld-linux.so.2 (0xf7f45000)
        libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf73ab000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7384000)
undefined symbol: SteamGameServer       (./engine_i486.so)
undefined symbol: SteamGameServer_Init  (./engine_i486.so)
undefined symbol: SteamApps     (./engine_i486.so)
```

The only way I was able to get the latest reHLDS to work is by following comment https://github.com/dreamstalker/rehlds/issues/999#issuecomment-1826375535 which instructs you to install the pre-25th anniversary build.

**Comment by SNMetamorph** [comment]
> On Debian I've installed the latest dev build of reHLDS onto the latest HLDS release and it returns the following error message:

Same on Ubuntu 22.04 too

**Comment by DarthMan** [comment]
Can this be integrated into the stable build, as well as the more recent fixes, such as SZ_GetSpaceOverflow ?

https://github.com/fantoro/rehlds/tree/raised_packet_entities

It increases the limit of entities to be like on the 25th update.

**Comment by feer9** [comment]
I've run into the `undefined symbol: SteamGameServer` error, but after downgrading to the steam_legacy beta version, the server just crashes on startup with no error. All I see is 

```
Auto-restarting the server on crash
Box86 with Dynarec v0.3.5 2b35400d built on Jan 21 2024 01:04:12

Console initialized.
email debug.log to linux@valvesoftware.com
sáb 27 ene 2024 21:31:13 -03: Server restart in 10 seconds
Box86 with Dynarec v0.3.5 2b35400d built on Jan 21 2024 01:04:12

Console initialized.
email debug.log to linux@valvesoftware.com
sáb 27 ene 2024 21:31:23 -03: Server restart in 10 seconds
Box86 with Dynarec v0.3.5 2b35400d built on Jan 21 2024 01:04:12

Console initialized.
email debug.log to linux@valvesoftware.com
sáb 27 ene 2024 21:31:33 -03: Server restart in 10 seconds
```

I'm running this with Box86 since it's a raspberry pi I'm trying to set up.
I have no idea where to look for an error message. My startup command is
`./hlds_run -game valve +map crossfire -pidfile hlds.pid`

**Comment by LonerWolfProduction** [comment]
Oh, I'm also trying to solve this problem, it's been going on for a week now. CS 1.6, Steam beta, need ReHLDS for REUNION. Did you manage to figure out how to get rid of this problem?

**Comment by LonerWolfProduction** [comment]
This answer helped me: 

> It worked for me to return the version previous to 25h steamcmd:
> 
> ```
> app_set_config 90 mod cstrike
> app_update 90 -beta steam_legacy validate
> ```

**Comment by carl07chia** [comment]
Here is the Solution
Take the steam_api.dll from the old 8684 legacy and paste it onto the latest HLDS.
